apps/contributions/views.py
Stripe doesn't seem to support pre-filling company info the way we want here. Removing this for now.
=> [NRH-60] remove unsupported company pre-fill

spa/src/components/dashboard/Dashboard.js, spa/src/components/dashboard/DashboardSidebar.js
The sidebar was not allowing interaction based on bad var name
=> BUGFIX dashboard bad restriction

apps/contributions/tests/test_views.py, apps/contributions/tests/test_webhooks.py, apps/contributions/views.py, revengine/settings/base.py
We shouldn't return a non-200 to Stripe on their webhook requests if it's our problem, not theirs.
=> [NRH] Bugfix webhook error response

spa/cypress/integration/donation-page-edit.spec.js, spa/src/components/donationPage/pageContent/DElement.styled.js, spa/src/components/donationPage/pageContent/SBenefits.styled.js, spa/src/components/pageEditor/editInterface/EditInterface.js, spa/src/components/pageEditor/editInterface/ElementProperties.js, spa/src/components/pageEditor/elementEditors/amount/AmountEditor.js, spa/src/components/pageEditor/elementEditors/amount/AmountEditor.styled.js, spa/src/components/pageEditor/elementEditors/index.js
Adds an editable amount widget. Prevents user from removing an amount if it's the last in the list.
=> [NRH-117] Editable amount

spa/src/components/donationPage/DonationPage.styled.js, spa/src/components/paymentProviders/stripe/StripePaymentForm.js, spa/src/components/paymentProviders/stripe/StripePaymentWidget.styled.js
Just reduces padding so you can use the credit card widget on mobile. Extra small mobile is still a little challenged, but there aren't many devices that size anymore.  Also removes a debugger that was somehow still around...
=> [NRH-133] Mobile Creditcards

apps/contributions/payment_managers.py, apps/contributions/tests/test_payment_managers.py, apps/contributions/views.py
Adds the field with the payment manager's flagged date into the create for Contribution.
=> Nrh 155  flagged payments not being set

apps/contributions/payment_managers.py, apps/contributions/tests/test_payment_managers.py
Testing this is probably best done on staging.
=> refs #NRH-32 Adds the receipt_email attribute from the PI API

spa/src/components/pageEditor/PageEditor.js, spa/src/components/pageEditor/editInterface/pageSetup/PageSetup.js, spa/src/components/pageEditor/editInterface/pageSetup/PublishWidget.js, spa/src/components/pageEditor/elementEditors/frequency/FrequencyEditor.js, spa/src/components/pageEditor/elementEditors/payment/PaymentEditor.js, spa/src/elements/GlobalLoading.js, spa/src/elements/GlobalLoading.styled.js
Fixes a handful of bugs that I could find while editing a newly created page. A bit of a scattershot effort, but I'm fairly certain that at least the bug that crashes staging in the video attached to this ticket has been fixed here.
=> [NRH-159]  New page edit bugs

spa/cypress/integration/connect.spec.js, spa/cypress/integration/donation-page.spec.js, spa/src/components/Main.js, spa/src/components/connect/ProviderConnect.js, spa/src/components/connect/stripe/StripeConnect.styled.js, spa/src/components/connect/stripe/StripeProvider.js, spa/src/components/pageEditor/PageEditor.js
Just needed to update local state with a refreshed version of the user after connecting stripe account.
Also updates a cypress test and adds a new one to test that this is fixed. Also removes a bit of code that wasn't being used.
=> [NRH-64] Post-onboarding-state-issue

apps/organizations/admin.py
Adds an admin field to control the boolean
In the django-admin there will now be a form field for `uses_email_templates`
No.
=> refs #NRH-179 Adds admin field

apps/pages/views.py, spa/src/components/donationPage/live/LiveErrorFallback.js, spa/src/components/donationPage/live/LiveErrorFallback.styled.js, spa/src/components/donationPage/live/LivePage404.js, spa/src/components/donationPage/live/LivePage404.styled.js, spa/src/components/pageEditor/PageEditor.js, spa/src/components/pageEditor/editInterface/pageElements/addElementModal/AddElementModal.js, spa/src/components/pageEditor/editInterface/pageSetup/PageSetup.js, spa/src/components/pageEditor/editInterface/pageSetup/PublishWidget.js, spa/src/elements/inputs/Select.styled.js
No ticket here, just a bit of housekeeping that was bothering me.
1. Null published_date erroneous validation issue fixed
2. Logo link erroneous validation issue fixed
3. Very basic styling of live 404 page
4. Very basic styling of live 500 page
You should be able to create a new donation page, without entering a logo link or published date, without getting any errors.
Also, view the 404 page by visiting the url of an unpublished page. If you know of any bugs that triggered the "LiveErrorFallback" page, you can try to trigger that again to view the styled 500 page.
No
=> A bit of DonationPage housekeeping

spa/cypress/integration/donations.spec.js, spa/src/components/donations/Donations.js
Was that "except after C" or "especially after C"?
Fixes a misspelling of "received" in the header of the donations list
Look for yourself
No
=> [NRH-275] Payment recieved --> Payment received

spa/cypress/integration/donation-page.spec.js, spa/src/components/donationPage/DonationPageStaticText.js
Adds a period missing in the Organization address line at the bottom of the donation form.
Observe the period.
No
=> [NRH-302] Missing period in address

apps/contributions/payment_managers.py, apps/contributions/tests/test_payment_managers.py
Handles some more edge cases around flagged recurring donations. The general issue is that flagged recurring donations have a unique set of challenges involving bundling up metadata. 
Let's try to accept a flagged recurring donation again.
=> More accept flagged recurring payments

apps/contributions/models.py, spa/cypress/integration/donation-page-edit.spec.js, spa/cypress/integration/donations.spec.js, spa/src/components/donations/Donations.js, spa/src/components/donations/Donations.styled.js, spa/src/components/donations/filters/CreatedFilter.js, spa/src/components/pageEditor/elementEditors/richText/RichTextEditor.js, spa/src/utilities/formatDatetimeForDisplay.js
Adds time to the datetime columns in the donations table. This turns out to be very useful information. This is not tied to a ticket, or a request, it was just annoying this particular developer.
Observe the presence of time in the donations list
No
=> add time to datetime columns

apps/common/middleware.py, apps/organizations/serializers.py, apps/pages/tests/test_viewsets.py, apps/slack/tests/test_slack_integration.py, spa/src/components/donationPage/DonationPage.styled.js, spa/src/components/pageEditor/editInterface/pageElements/PageElements.js, spa/src/components/pageEditor/editInterface/pageElements/PageElements.styled.js, spa/src/components/pageEditor/editInterface/pageSidebarElements/PageSidebarElements.js
Ensures rev program slug on page create, so that user is navigated to the correct url for (new) page edit.
Create a new page. The url you're directed to should include the rev-program slug, not "undefined".
No.
=> [NRH-297] Page-create bugs

spa/src/components/donationPage/pageContent/DPayment.js, spa/src/utilities/calculateStripeFee.js
Ensures that calculated fees will always have 2 decimal places.
1. Enable pay fees on a page.
2. Enter an amount of $180 to contribute
3. Observe that the calculated fee is $5.30 rather than $5.3
No.
=> refs #NRH-306 Fixes the decimal places to 2

Dockerfile
Sets the NODE_ENV to production for Docker builds.
=> refs #NRH-0000 Updates the dockerfile

spa/public/index.html, spa/public/manifest.json
Try adjusting manifest.json for favicon
=> [NRH-93] manifest already present, adjusting values

spa/cypress/integration/donation-page.spec.js, spa/src/components/donationPage/DonationPage.js, spa/src/components/donationPage/pageContent/DAmount.js, spa/src/components/donationPage/pageContent/DFrequency.js, spa/src/hooks/useQueryString.js
Overall, fixes a bug in frequency/amount queryparam responses. Specifically, refactors the whole mechanism by which frequencies and amounts are set in relation to one-another.
Test the AC for the amount and frequency query string issues.
No
=> [NRH-337] Frequency queryparam bugs

spa/src/utilities/calculateStripeFee.js
Uncomments two lines of code that will enable a 0.5 percentage point rate increase if a donation is a subscription.
Select a one-time donation and a certain amount. Note the fee.
Select a recurring donation and that same amount. Note a different, higher fee.
No
=> [NRH-324] Turn on Stripe Fee Subscription upcharge

spa/src/components/donationPage/live/LivePage404.js, spa/src/components/donationPage/live/LivePage404.styled.js
Adds some additional text to the 404 page
Trigger the 404 and observe the changes.
No
=> [NRH-293] 404 page updates

apps/api/urls.py, poetry.lock, pyproject.toml, revengine/settings/base.py
Adds package [django-health-check](https://github.com/KristianOellegaard/django-health-check) for easy configurable service checks. In particular, implements checks on the following services:
1. db
2. migrations
3. celery
4. redis
The endpoint is /api/v1/healthcheck. It will respond with JSON if you send the header "Accept" with "application/json" or "format=json" as a query param.
It can take a long time if it's failing to reach one of the services-- this is because it retries for a bit.
Visit https://rev-engine-test.herokuapp.com/api/v1/healthcheck?format=json in your browser or use some other client to hit /api/v1/healthcheck with the Accept header set properly. 
No
=> [NRH-277] API health check

spa/cypress/integration/donation-page-edit.spec.js, spa/cypress/integration/donation-page.spec.js, spa/src/components/donationPage/DonationPage.js, spa/src/hooks/useClearbit.js
Adds clearbit.js script to every live donation page.
Not sure how one would test the score calculation bit of this, as that seems to be out of the scope of this effort. I suppose you'd inspect the head of a donation page and look for the clearbit.js script tag. You could also verify that same is not present when in edit mode.
No
=> [NRH-245] Clearbit.js

spa/src/components/donationPage/live/thankYou/GenericThankYou.js, spa/src/components/donationPage/live/thankYou/GenericThankYou.styled.js
Updates thank you page text to match text provided. Tones down the border around the thank you page box.
View thank-you page and note text and border.
No
=> [NRH-350] update thank you page text, tone down border

spa/src/components/donationPage/pageContent/DAmount.js, spa/src/components/donationPage/pageContent/DAmount.styled.js
Before merging to develop:
Adds the frequency for monthly and yearly donations in the amount buttons on donation pages.
Notice the frequency text in the amount buttons for recurring donations.
No
=> [NRH-363] Freq text in amount buttons

spa/src/components/donationPage/pageContent/DReason.js, spa/src/components/pageEditor/elementEditors/reason/ReasonEditor.js
updates reason for giving language
view a template such as https://support.revengine-test.org/edit/new-rev-program/caktus-donations and confirm the language changes from "excited to support" to "i support your work because…" and "inspired" to "reason for giving"
I don't think so
=> updates reason for giving language

spa/src/utilities/calculateStripeFee.js
Disables subscription upcharge
Notice the difference in the total fee
No
=> [NRH-5059] No Subscription Upcharge

spa/src/components/donationPage/DonationPageSidebar.styled.js, spa/src/components/donationPage/pageContent/DBenefits.styled.js, spa/src/components/donationPage/pageContent/DFrequency.js, spa/src/components/donationPage/pageContent/DFrequency.styled.js, spa/src/components/donationPage/pageContent/DReason.js, spa/src/components/donationPage/pageContent/DReason.styled.js, spa/src/components/donationPage/pageContent/DSwag.js, spa/src/components/donationPage/pageContent/DSwag.styled.js, spa/src/elements/inputs/Checkbox.js, spa/src/elements/inputs/Checkbox.styled.js, spa/src/elements/inputs/inputElements.styled.js
Makes the changes discussed in the following basecamp posts:
https://3.basecamp.com/3120230/buckets/21497549/todos/4308757590
https://3.basecamp.com/3120230/buckets/21497549/todos/4315572991
take a look
No
=> [NRH-5067] Additional styling tweaks

revengine/settings/base.py
Adds facebook.com to frame-src directive for social share and FB pixel bits
Verify that after completing a donation, no CSP violations appear in the console.
No
=> [NRH-5118] More CSP violations

apps/contributions/management/commands/create_stripe_webhooks.py, apps/contributions/payment_managers.py, apps/contributions/serializers.py, apps/contributions/tests/test_management_commands.py, apps/contributions/tests/test_payment_managers.py, apps/contributions/tests/test_serializers.py, apps/contributions/tests/test_views.py, revengine/settings/base.py, spa/src/components/donationPage/pageContent/DBenefits.styled.js, spa/src/components/donationPage/pageContent/DFrequency.js
Fixes a bug in which two separate stages of validation would occur when submitting a donation.
Verify that, if you make a donation without filling out any info (on a page with Member benefits and/or Swag required fields) that all validation errors appear on the first submit.
No
=> [NRH-5125] Metadata validation bugs

revengine/settings/base.py
Adds:
1. referrer-policy: strict-origin-when-cross-origin
2. x-content-type-options: nosniff
3. x-frame-options: SAMEORIGIN
Check those headers, or use one of those tools
No
=> adds three more security headers

spa/src/App.js, spa/src/components/contributor/contributorDashboard/EditRecurringPaymentModal.js, spa/src/components/paymentProviders/stripe/StripePayment.js
=> restores stripe publishable key for testing

spa/src/components/donationPage/pageContent/DSwag.js, spa/src/components/donationPage/pageContent/DSwag.styled.js, spa/src/elements/inputs/Select.js, spa/src/elements/inputs/Select.styled.js
Adds some hardcoded helptext to the swag item
Notice the helptext.
No
=> [NRH-5164] Swag helptext

spa/src/components/paymentProviders/stripe/StripePaymentForm.js
Adds fees to amount shown on thankyou page.
Incidentally (or maybe not), also made the facebook conversion event use the amount + fees.
Make a donation with fees and notice the correct total.
No
=> [NRH-5129] ThankyouPage amount fee-inclusive

apps/contributions/serializers.py, apps/contributions/tests/test_serializers.py, spa/package-lock.json
Disallows blank metadata fields (again...)
Make a donation from a page with a "Reason for giving" element but don't populate it. There should be no blank `reason_for_giving` metadata downstream.
no
=> [NRH-5125] Metadata fix bugs

spa/src/components/paymentProviders/stripe/StripePaymentForm.js, spa/src/components/paymentProviders/stripe/StripePaymentForm.styled.js
makes manual card entry text italic, slightly modifies copy 
view a donation page and make sure it works
n/a
=> make manual card entry text italic, edit copy

apps/common/tests/test_views.py, revengine/settings/dev.py, revengine/views.py, spa/public/index.html
Sets the title of the page to "Join | {{ rev program name }}"
Visit a donation page
No
=> [#9717] DonationPage <title> is RevProgram name

README.md, spa/src/components/donationPage/DonationPage.js, spa/src/components/paymentProviders/stripe/StripePaymentForm.js, spa/src/components/paymentProviders/stripe/StripePaymentForm.styled.js, spa/src/settings.js
Creates a way to set frontend env vars locally for greater parody between local and deployed environments.
This is a local development thing.
No
=> Local env vars

spa/src/components/authentication/Login.styled.js, spa/src/components/authentication/ReauthModal.styled.js, spa/src/components/content/pages/Pages.js, spa/src/components/content/styles/EditStylesModal.styled.js, spa/src/components/content/styles/StyleCard.js, spa/src/components/content/styles/StyleCard.styled.js, spa/src/components/donationPage/DonationPage.styled.js, spa/src/components/donationPage/DonationPageNavbar.js, spa/src/components/donationPage/DonationPageNavbar.styled.js, spa/src/components/donationPage/SegregatedStyles.js, spa/src/components/donationPage/pageContent/DAmount.styled.js, spa/src/components/donationPage/pageContent/DBenefits.styled.js, spa/src/components/donationPage/pageContent/DFrequency.js, spa/src/components/donationPage/pageContent/DReason.js, spa/src/components/donationPage/pageContent/SPageHeading.styled.js, spa/src/components/pageEditor/editInterface/pageStyles/AddStylesModal.styled.js, spa/src/components/stylesEditor/StylesEditor.js, spa/src/components/stylesEditor/StylesEditor.styled.js, spa/src/elements/buttons/Button.styled.js, spa/src/elements/buttons/SelectableButton.styled.js, spa/src/elements/inputs/BaseField.styled.js, spa/src/elements/modal/Modal.styled.js, spa/src/styles/DonationPageGlobalStyles.js, spa/src/styles/themes.js
Implements the changes discussed in [this basecamp post](https://3.basecamp.com/3120230/buckets/21497549/todos/4376261341).
Try out the new values in a new stylesheet. Old styles will not work anymore.
No, other than possibly reworking existing pages to whatever extent you want
=> #10749 Improve Page Style Color Settings

spa/src/components/pageEditor/editInterface/pageSetup/PageSetup.js, spa/src/components/pageEditor/editInterface/pageSetup/PageSetup.styled.js, spa/src/components/paymentProviders/stripe/StripePaymentForm.styled.js, spa/src/styles/AdminGlobalStyles.js
Implements the changes mentioned in [this basecamp post](https://3.basecamp.com/3120230/buckets/21497549/todos/4506902808). In particular, moves some items around in the setup tab and renames a few things.
Observe the changes in the setup tab. Maybe make some changes to the fields to verify that they still do what they're supposed to do.
No
=> #10750 Additional Styling Updates

revengine/settings/base.py, spa/src/settings.js
Fixes a javascript error resolving strings in env vars that caused donation pages to crash.
Check that donation pages can be viewed.
No
=> Hotfix--JS env var str resolution

apps/contributions/tests/test_payment_managers.py, apps/contributions/tests/test_serializers.py, apps/contributions/tests/test_views.py, apps/pages/defaults.py
Adds a missed requirement regarding the default page state for phone number. It is not on and required by default.
=> #11614 newly created pages default phone present and required

spa/src/components/stylesEditor/StylesEditor.js, spa/src/components/stylesEditor/StylesEditor.styled.js
Color pickers were disappearing behind the modal. Now they are not
=> #11635 Styles form color picker off-screen

apps/common/static/common/admin-limited-select.js, apps/organizations/admin.py, apps/pages/admin.py
Fixes a series of missed edge cases for Django Admin dropdown limitations.
Test the parent ticket
No
=> #11864 bug: dropdown limits issues

apps/organizations/serializers.py
Adds benefit levels to the serializer for revenue_programs
=> sc-12104 add benefit levels to the RP serializer

apps/organizations/serializers.py, apps/public/serializers.py
Exposes the benefit level id on the public api.
=> sc-12104 Moves the source of information into the public serializer

apps/common/tests/test_views.py, apps/organizations/views.py, apps/pages/serializers.py, apps/pages/views.py
Makes revenue program on the Style serializer context dependent
1. Open a style and make changes to the style
2. Save the changes.
3. Observe that they are applied.
=> refs #sc-12302 Bug Fix style update

revengine/settings/base.py
=> disable email logging

README.md, apps/users/management/commands/bootstrap-review-app.py, revengine/settings/base.py
Removes the automatic creation of the qatester user.
=> Dev 1438 rm qatester

.github/PULL_REQUEST_TEMPLATE.md, .sentryclirc, README.md, apps/api/views.py, email_templates/nrh-default-otd.html, email_templates/nrh-manage-donations-magic-link.html, email_templates/nrh-v1-default-thank-you-for-donation.html, email_templates/nrh-v2-default-one-time-donation.html, revengine/settings/base.py, spa/cypress/integration/02 - donation-page-edit.spec.js, spa/cypress/integration/10 - connect.spec.js, spa/src/components/analytics/Analytics.spec.js, spa/src/components/analytics/plugins/facebookPixel.js, spa/src/components/connect/stripe/StripeProvider.js, spa/src/components/content/pages/AddPageModal.js, spa/src/components/dashboard/sidebar/DashboardSidebar.js, spa/src/components/donationPage/pageContent/DAmount.js, spa/src/components/donationPage/pageContent/DFrequency.js, spa/src/components/donationPage/pageContent/DPayment.js, spa/src/components/donationPage/pageContent/DRichText.js, spa/src/components/donationPage/pageContent/DSwag.js, spa/src/components/donationPage/pageContent/SHeaderBar.js, spa/src/components/donationPage/pageContent/SPageHeading.js, spa/src/components/donations/DonationDetail.js, spa/src/components/donations/Donations.js, spa/src/hooks/useSentry.js, spa/src/settings.js
Merges `develop` into `main`
We're switching to use `main` as the primary branch to branch from and merge into. This catches `main` up to `develop`
No testing should be necessary since all of these changes have already been through code review.
Yes.
N/A
No.
No.
[DEV-1450]
No.
[DEV-1450]: https://news-revenue-hub.atlassian.net/browse/DEV-1450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Merge develop into main

Dockerfile, Makefile, app.json, apps/common/tests/test_utils.py, apps/common/utils.py, apps/contributions/management/commands/create_stripe_webhooks.py, apps/contributions/tests/test_management_commands.py, apps/users/management/commands/bootstrap-review-app.py, apps/users/management/commands/teardown-review-app.py, deployment-tasks.sh, docker-entrypoint.sh, heroku.yml, poetry.lock, pyproject.toml, revengine/settings/base.py, review-tasks.sh, scripts/heroku-postdeploy.sh
Merges outstanding code in `develop` into `main`. I believe that's only DEV-1420.
=> Release 2022 03 30

spa/src/components/pageEditor/PageEditor.js
Fixes a typo in the page editor.
We like things to be spelled correctly.
- create or edit a page
- click the save icon
- confirm that the popup reads "Your page has be updated" (spelled correctly)
No.
N/A
No.
N/A
[DEV-1656]
No.
No.
[DEV-1656]: https://news-revenue-hub.atlassian.net/browse/DEV-1656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix typo in page editor

spa/src/components/dashboard/DashboardSection.styled.js, spa/src/components/stylesEditor/StylesEditor.js, spa/src/elements/table/PaginatedTable.styled.js
DRAFT
Fixes regression bug 
Critial issue
Login to dashboard
no
na
na
no
[DEV-1777]
no
[DEV-1777]: https://news-revenue-hub.atlassian.net/browse/DEV-1777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DEV-1777 dev-1111 regression on content-dashboard

spa/src/components/pageEditor/editInterface/pageSetup/PageSetup.js
Complete
Updates text shown as aid for "uploading of logo-image" for  a donation page
To inform end user about preferred sizing of logo image
Go to Edit-Page and try to change header.  The new text should show in that section
N/A
N/A
No
[DEV-772]
N/A
N/A
[DEV-772]: https://news-revenue-hub.atlassian.net/browse/DEV-772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Edit Page -  header logo text change

apps/users/tests/test_serializers.py, spa/cypress/integration/04 - donations.spec.js, spa/src/components/donations/filters/CreatedFilter.js, spa/src/components/donations/filters/Filters.js, spa/src/utilities/formatDatetimeForAPI.js
See https://github.com/newsrevenuehub/rev-engine/pull/436
I merged it prematurely, then reverted, so this is the second attempt.
See https://github.com/newsrevenuehub/rev-engine/pull/436
=> reapply DEV-1595

apps/pages/helpers.py
PR initially into DEV-1856 because it presupposes that larger set of changes.
Moves a log to .info from .warning and adds more specificity to log message, delineating between an unfound slug, and when there is an attempt to retrieve a default page, but none is found.
N/A
N/A
N/A
N/A
N/A
[DEV-1957 | request for non-existent page by slug none](https://news-revenue-hub.atlassian.net/jira/software/c/projects/DEV/boards/3?modal=detail&selectedIssue=DEV-1957)
N/A
N/A
=> DEV-1957 |  request for non existent page by slug none

apps/contributions/tests/test_webhooks.py, apps/contributions/views.py
PR is initially into DEV-1856 because presupposes those changes.
Changes log level to info from warning, and updates a related test.
[DEV-1960 | Could not find contribution matching provider_payment_id](https://news-revenue-hub.atlassian.net/jira/software/c/projects/DEV/boards/3?modal=detail&selectedIssue=DEV-1960)
=> DEV-1960 | Could not find contribution matching provider payment

spa/public/index.html
Removes manifest.json ref from SPA's index.html file, as there was no corresponding file, no business requirements for a manifest.json, and it was causing a console error to appear.
Cleaning up console logs ahead of launch.
Visit any page from the SPA. Open developer tools and click on the `Console`. There shouldn't be any errors complaining about manifest.json .
No. Not relevant as this only touches the index.html and removes an error.
N/A
No
N/A
[DEV-1916](https://news-revenue-hub.atlassian.net/jira/software/c/projects/DEV/boards/3?modal=detail&selectedIssue=DEV-1916)
No
N/A
=> DEV-1916 | remove unneeded manifest.json

revengine/settings/deploy.py
https://github.com/newsrevenuehub/rev-engine/pull/526
=> rm BAD_ACTOR_API_URL from deploy.py

apps/api/views.py
This PR will make magic-links for contributor portal work in Apple-Mail Client.
Right now we do not specify protocol in magic-link for contributor portal. Most mail clients default to https:// but Apple Mail client does not (it defaults to x-webdoc://) and hence link does not work.
e.g.
x-webdoc://E1AB8785-AA6F-426C-85C8-7EDF92D1DF96/](https://newsrevenuehub-dev-2184.revengine-review.org/contributor-verify?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjYwOTI3MTQzLCJpYXQiOjE2NjA5MjYyNDMsImp0aSI6ImZkZDhiMjk1YjlmYzQ3NTViN2FlODc2MTU4MGExNDdkIiwiY29udHJpYl9pZCI6ImMzZTkwYzYyLWRhNDQtNDMyNC1hMDQ4LWY5MGU1Nzg4NDU1OSIsImN0eCI6InNob3J0In0.cz9MFvar32yzODXvMv6Q26e5DUh6MIip8iiFI7BUrQM&email=gurjit.sidhu%40fund …
=> DEV-2184-contributor-email-link add https protocol to link

apps/organizations/models.py
This PR contains server-side changes for parent ticket DEV-1867. The PR's base is DEV-1867-root-branch, which is the holding branch for subtask branches, and which will eventually be merged into main.
Adds two new attributes to the `Plan` dataclass:
- `swag_options_enabled`, which defaults to `False` but is set to `True` on `PlusPlan`
- `member_benefits_enabled`, which defaults to `False` but is set to `True` on `PlusPlan`
Requirement for self-service onboarding.
There's not a good way to test this PR on its own, and testing should come with follow up ticket [DEV-2460 | Spa-side changes for DEV-1867](https://news-revenue-hub.atlassian.net/browse/DEV-2460).
That said, you should be able to see that the updates to the plan are coming …
=> DEV-2459 — Server-side changes for DEV-1867

spa/src/components/account/common/leftbar/Content.js
update total raised on the `create-account` page
it's currently a few million dollars out of date
verify that total raised changes as expected https://engine.fundjournalism.org/create-account
n/a
simple copy change
let CEO know once it's in production ;) 
n/a
n/a
https://news-revenue-hub.atlassian.net/browse/DEV-2575
n/a
n/a
=> update total raised on `create-account` page

apps/api/permissions.py
This PR solves for a regression that was introduced in [this commit](https://github.com/newsrevenuehub/rev-engine/commit/67efa3ebf0ad), where among other dependency upgrades, we upgraded from DRF 3.13 to 3.14.
Specifically, the following tests were failing:
```
FAILED apps/pages/tests/test_viewsets.py::PageViewSetTest::test_hub_admin_can_delete_a_page - AttributeError: 'HasDeletePrivilegesVi...
FAILED apps/pages/tests/test_viewsets.py::PageViewSetTest::test_org_admin_can_delete_their_orgs_page - AttributeError: 'HasDeletePri...
FAILED apps/pages/tests/test_viewsets.py::PageViewSetTest::test_rp_admin_can_delete_their_rps_page - AttributeError: 'HasDeletePrivi...
```
In each case, the tests were failing because DRF expected …
=> DEV-2531 | Fix bug that is breaking Python tests after upgrading DRF

spa/cypress/e2e/08-contributor.cy.js, spa/cypress/fixtures/donations/18-results.json, spa/src/ajax/endpoints.js, spa/src/components/contributor/contributorDashboard/ContributorDashboard.js, spa/src/components/contributor/contributorDashboard/EditRecurringPaymentModal.js
n/a
Updates the contribution cancellation code to use the correct endpoint.
Syncs UI with API.
1. Create a recurring test contribution.
2. Log into the contributor dashboard.
3. Click the pencil icon next to the contribution you created.
4. Enter a valid credit card number, expiration, etc. It can be the same info as what you used to create the initial donation.
5. Click the **Update payment method** button.
6. Confirm you see this message:
> Your new payment method will be used for the next payment. Changes may not appear in our system right away.
7. Log out of the contributor dashboard and back in.
8. Confirm the new payment info is visible there.
No.
Yes.
n/a
I had to mock part of the Stripe API in Cypress. I don't see a way …
=> Dev 1569 fix update payment method

spa/src/components/account/Verify/Verify.js, spa/src/components/account/Verify/Verify.styled.js, spa/src/styles/themes.js
n/a
Update Verify email screen to match design
Make design consistent accross the entire app
- Create new account 
- Check verify email screen
- Make sure design matches figma
n/a
n/a
n/a 
no
no
https://news-revenue-hub.atlassian.net/browse/DEV-2554
no
Parent ticket: https://news-revenue-hub.atlassian.net/browse/DEV-2107
=> DEV-2554: Verify Your Email Screen Updates

spa/src/components/donationPage/pageContent/DAmount.styled.js
n/a
Fixes appearance of contribution options on mobile viewports.
More professional appearance.
1. Go to a contribution page and turn on response design mode in your browser, and size it down to mobile viewport(s). Ideally, also open the contribution page on an actual phone.
2. Confirm that the confirmation page buttons appear as a vertical stack instead of appearing side-by-side.
3. Do steps 1-2, but on a desktop browser and confirm the buttons appear side-by-side.
No.
No, this is a CSS-only change.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-2649
No.
No.
=> DEV-2649: Fix styling of contribution options on mobile viewports

revengine/settings/base.py
n/a
Allows Google Tag Manager in our CSP configuration.
We use GTM for tracking, and this gets us closer to being able to turn on CSP enforcement.
1. Go to the donation thank-you page for Billy Penn in the review app.
2. Confirm that there is no CSP-related error in dev tools console, and the network tab in dev tools shows Google Tag Manager loading successfully.
No.
No, but I'd really like to. I'm not sure how to write a test for this kind of change, but it feels like it would be very valuable. I did some Googling around for ideas but didn't have much success.
n/a
Lack of tests
No.
https://news-revenue-hub.atlassian.net/browse/DEV-2293
I don't think so but I am not 100% sure.
No.
=> DEV-2293: Allow GTM in CSP

apps/contributions/views.py, apps/emails/templates/nrh-contribution-csv-email-body.txt, apps/emails/templates/nrh-org-portal-password-reset.html, apps/emails/templates/nrh-org-portal-password-reset.txt, apps/emails/templates/nrh-user-base-template.html, apps/emails/tests/test_tasks.py, apps/users/views.py
n/a
- Updates layout for reset password email to match figma
- Update csv email template `.txt` that was still with old copy
- Remove variable `name` from csv email because it as no longer being used
This layout update is making all emails consistent with design and before this update there wasn't even a layout done, it was only some text in the email.
- Request a reset password
- Check that the email you received has the updated layout as in figma https://www.figma.com/file/uZpKfBbZ4HxUpNIsImkVeh/%5BDES-9%5D-Transactional-Emails?node-id=3%3A101&t=H9ZCgc1qod10cTp2-0
Yes
Yes
n/a
no
no
https://news-revenue-hub.atlassian.net/browse/DEV-2775
no 
no
=> DEV-2775: Update layout for reset password email

apps/users/views.py
N/A
Remove two places where user object was being logged directly, causing passwords to be leaked in logs
Addresses a security vulnerability, passwords should never be logged in plantext
N/A
N/A - this is just adjusting log statement
N/A
N/A
N/A
[DEV-2412]
N/A
N/A
[DEV-2412]: https://news-revenue-hub.atlassian.net/browse/DEV-2412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DEV-2412: remove log files that leak user password

.github/workflows/chromatic.yml, spa/package-lock.json
n/a
Adds [TurboSnap](https://www.chromatic.com/docs/turbosnap) to our Chromatic setup in hopes of reducing our snapshots.
Also, while I was in here I ran `npx update-browserslist-db@latest` because I've been seeing warnings about it for a while.
Helps with Chromatic plan limitations.
n/a, CI only
No.
No. The change is to a GH action only.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-3200
No.
No.
=> DEV-3200 Add turbosnap

spa/cypress/e2e/02-donationPageEdit.cy.js, spa/src/components/pageEditor/editInterface/ElementEditor.styled.ts, spa/src/components/pageEditor/editInterface/ElementEditor.tsx, spa/src/components/pageEditor/elementEditors/payment/PaymentEditor.styled.ts, spa/src/components/pageEditor/elementEditors/payment/PaymentEditor.test.tsx, spa/src/components/pageEditor/elementEditors/payment/PaymentEditor.tsx, spa/src/hooks/useContributionPage/useContributionPage.types.ts
n/a
Updates the fee editor (aka the DPayment editor) to match updated comps and to use the new ElementEditor interface.
Improved UX.
1. Edit a page and the "Payment Fees" block.
2. Toggle on the "Offer to pay payment provider fees" toggle and save changes.
3. Confirm that the option to pay fees is present on the published page and that you are charged the correct amount when it's selected.
4. Edit the page and payment block as above.
5. Check the "Selected by default" checkbox and save changes.
6. Confirm that the option to pay fees is selected by default on the published page and that you are charged fees if you make no changes to the checkbox.
7. Edit the page and payment block.
8. Uncheck the "Selected by default" checkbox and …
=> DEV-2982: Revise fees editor

poetry.lock
N/A
Bump Django version to 3.2.18
Due to security vulnerability CVE-2023-24580: Potential denial-of-service vulnerability in file uploads a [new Django patch was released](https://www.djangoproject.com/weblog/2023/feb/14/security-releases/) and it is recommended to 
Since this is dependency update, relying mostly on unit tests. In addition, you can open the review app and perform some operations like making a contribution, logging in and operating the admin console
N/A
N/A
N/A
N/A
N/A
[DEV-3363]
N/A
N/A
[DEV-3363]: https://news-revenue-hub.atlassian.net/browse/DEV-3363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DEV-3363: upgrade django version to address security vulnerability

spa/src/components/common/IntegrationCard/IntegrationCard.styled.ts, spa/src/components/common/IntegrationCard/IntegrationCard.tsx, spa/src/components/common/IntegrationCard/MailchimpIntegrationCard/MailchimpIntegrationCard.styled.ts, spa/src/components/common/IntegrationCard/MailchimpIntegrationCard/MailchimpIntegrationCard.test.tsx, spa/src/components/common/IntegrationCard/MailchimpIntegrationCard/MailchimpIntegrationCard.tsx
n/a
Updates the "Upgrade to Core" prompt appearance in the Mailchimp integration card.
Improves desing.
1. Go to the integrations page.
2. Confirm that the label in the top right corner of the Mailchimp card matches Figma.
Very minor.
Yes.
Not needed.
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-3458
No.
No.
=> DEV-3458: Adjust corner message of Mailchimp integration card

spa/cypress/e2e/01-donationPage.cy.js, spa/cypress/e2e/02-donationPageEdit.cy.js, spa/package-lock.json, spa/package.json, spa/src/components/base/Button/Button.tsx, spa/src/components/base/Checkbox/Checkbox.tsx, spa/src/components/base/FormControlLabel/FormControlLabel.tsx, spa/src/components/base/Link/Link.tsx, spa/src/components/base/Modal/ModalContent.tsx, spa/src/components/base/Modal/ModalHeader.tsx, spa/src/components/base/Tabs/Tab.tsx, spa/src/components/base/Tabs/Tabs.tsx, spa/src/components/common/Badge/EnginePlanBadge/EnginePlanBadge.styled.ts, spa/src/components/common/Modal/MaxPagesReachedModal/MaxPagesReachedModal.styled.ts, spa/src/components/contributor/contributorDashboard/CancelRecurringButton.styled.ts, spa/src/components/dashboard/sidebar/SidebarCoreUpgradePrompt/SidebarCoreUpgradePrompt.styled.ts, spa/src/components/pageEditor/editInterface/EditSaveControls.styles.ts, spa/src/components/pageEditor/editInterface/EditSaveControls.test.tsx, spa/src/components/pageEditor/elementEditors/amount/AmountInterval.styled.ts, spa/src/components/pageEditor/elementEditors/contributorInfo/ContributorInfoEditor.styled.ts, spa/src/components/pageEditor/elementEditors/frequency/FrequencyEditor.styles.ts, spa/src/components/pageEditor/elementEditors/payment/PaymentEditor.styled.ts, spa/src/styles/Palette.stories.mdx, spa/src/styles/defaultTheme.d.ts, spa/src/styles/themes.ts
n/a
Adds two new keys to our theme:
- `basePalette`: core colors as spec'd in Figma. This is a work in progress, but I'd like to start using this property over some of the other existing ones, like `muiGrey`.
- `plan`: colors related to plan tiers.
I updated components that used string literals matching these new colors, but didn't touch anything beyond that to try to keep the scope of this PR manageable/testable.
Continues progress on component library.
This should not change any behavior. It would be a good idea to click around the app to ensure no color changes have happened, and that custom colors on contribution pages still look correct.
No.
No, this just defines colors.
n/a
I had to do a bunch of casts in our theme to get …
=> DEV-3487: Update theme colors

spa/src/components/donations/DonationUpgradePrompts/DonationUpgradePrompts.test.tsx
n/a
Fixes SPA build failure after merging DEV-3513 and DEV-3330.
Gets build green.
The extent of the problem looks like it's limited to our unit tests, but it would be good to kick the tires on the app in general, similar to what was done with https://github.com/newsrevenuehub/rev-engine/pull/1104.
No.
n/a
n/a
No.
No.
n/a
No.
No.
=> Fix typing in unit test

README.md, apps/emails/templates/nrh-default-contribution-confirmation-email.html, apps/emails/tests/test_tasks.py, apps/emails/urls.py, apps/emails/views.py
n/a
- Syncs up header bar in contribution receipts with the appearance on recurring contribution reminders (https://github.com/newsrevenuehub/rev-engine/pull/1111).
- Adds debug URL for contribution receipts.
- Fixes appearance for logos that are meant for a dark background.
- Makes email dev work easier.
To test styled emails for regressions:
1. Make a contribution to an org whose default page has a style set.
2. Confirm the receipt email appearance is correct (header color and logo are correct, appear above text header) and contains accurate info.
3. Make a contribution to an org whose default page has a style set, but no header logo.
4. Confirm the receipt email appearance is correct (has left-aligned NRE logo at top, no …
=> DEV-3519: add header bar to email receipts

.nvmrc, spa/src/components/authentication/logout.test.ts, spa/src/components/authentication/logout.ts, spa/src/components/donationPage/live/PaymentSuccess/PaymentSuccess.test.tsx, spa/src/components/donationPage/live/PaymentSuccess/PaymentSuccess.tsx, spa/src/hooks/useConnectMailchimp.test.tsx, spa/src/hooks/useConnectMailchimp.tsx, spa/src/hooks/useConnectStripeAccount.test.tsx, spa/src/hooks/useConnectStripeAccount.ts, spa/src/setupTests.js
Upgrades the Node version used by the SPA to 18.
Node 16 is getting end-of-lifed in September.
This PR makes changes to these workflows, but nothing should change from a user standpoint:
- Logout should send the user to the top level of the domain.
- Completing a contribution should send the user to the correct URL (both for default thank you page and user-defined ones).
- Initiating a Mailchimp connection should send the user to Mailchimp to authorize it. (I'm not sure if this is ready to test, but we have functionality there.)
No.
Updated existing tests.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-3522
No.
No.
=> DEV-3522: Upgrade Node to 18, adjust tests related to window.location

spa/cypress/e2e/01-donationPage.cy.js, spa/cypress/e2e/02-donationPageEdit.cy.js, spa/src/components/donationPage/pageContent/DSwag.js, spa/src/components/pageEditor/editInterface/EditInterfaceContextProvider.tsx, spa/src/components/pageEditor/editInterface/pageElements/addElementModal/AddElementModal.tsx
Temporarily disables the swag block while a fix for it is made.
Addresses a prod issue.
On a page that already has a swag block:
1. Confirm that the swag block is not displayed on the live page.
2. Confirm that you can make a contribution (e.g. no warning about missing required fields) and that the contribution shows correctly in Stripe.
3. Confirm that the swag block is not displayed in the page preview when you edit the page.
4. Confirm that the swag block is not shown in the block list on the right side of the page editor.
On a page that doesn't already have a swag block, and an org on the Core plan:
1. Confirm you cannot add a swag block to the page, e.g. it doesn't show as an option when adding a new block on either the main …
=> DEV-3733: Temp disable DSwag block

spa/package-lock.json, spa/src/hooks/useConnectMailchimp.test.tsx, spa/src/hooks/useConnectMailchimp.tsx
See https://github.com/newsrevenuehub/rev-engine/pull/1173
n/a
Restores functionality that got clobbered by accident.
Fixes a regression.
Copy/pasting from https://github.com/newsrevenuehub/rev-engine/pull/1173:
I'll make a table here with different user configurations and expected outcome--although laborious, we should test them all.
| Plan | Has Feature Flag? | Mailchimp toggle on Integrations page                         |
| ---- | ----------------- | ------------------------------------------------------------- |
| Free | No                | Disabled and does nothing when clicked                        |
| Free | Yes               | Disabled and does nothing when clicked                        |
| Core | No                | …
=> DEV-3801: Restore Mailchimp access criteria

apps/organizations/serializers.py, apps/organizations/tests/test_serializers.py, spa/src/components/content/customize/Customize.test.tsx, spa/src/components/content/customize/Customize.tsx, spa/src/hooks/useUser.types.ts
n/a
Updates copy of "Customize" screen if user's Org does not have "send NRE email" flag enabled
Informs the user how they can enable custom emails
Yes
yes
yes
n/a
no
no
https://news-revenue-hub.atlassian.net/browse/DEV-3059
no
no
=> DEV-3059: Account for SF sent emails in test emails UI

spa/cypress/e2e/08-contributor.cy.js, spa/src/components/contributor/ContributorEntry.tsx
n/a
Changes copy on the page users see when requesting a magic link.
Clarifies UX.
Yes.
No.
Updated a Cypress test that looked for this text.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-3929
No.
No.
=> DEV-3929: Change copy on magic link page

spa/src/components/donationPage/pageContent/DBenefits.js, spa/src/components/donationPage/pageContent/DSwag.tsx, spa/src/components/pageEditor/editInterface/ElementEditor.tsx
n/a
Revises text on page for the swag and member benefits elements.
Makes things more distinguishable in the UI.
Yes.
Yes. Names changed.
No, this was a text on page change only.
Updated docs.
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-4026
No.
No.
=> Dev 4026 swag element refinements

apps/emails/tasks.py, apps/users/views.py
Initially merge this so we can get some logs to determine where/why failure to send account verification emails.
Adds logs
Initial step to determine underlying problem causing verification emails not to send.
N/A. We just will see logs in log explorer.
No
N/A
N/A
No
No
- [DEV-4243](https://news-revenue-hub.atlassian.net/browse/DEV-4243)
- [DEV-4240](https://news-revenue-hub.atlassian.net/browse/DEV-4240)
[DEV-4243]: https://news-revenue-hub.atlassian.net/browse/DEV-4243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add diagnostic logging in support of DEV-4240 to determine why email verification emails not sending for new org users

spa/public/index.html
n/a
Corrects meta tags in our HTML so that OpenGraph tags are detected correctly by social media sites.
Fixes sharing.
Yes.
No.
This only changes content in index.html. It'd be a good candidate for a future E2E test.
n/a
Still not clear why the `description` attribute is used here. [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta) doesn't list it as an attribute on the tag.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-4271
No.
No.
=> DEV-4271: Fix social meta tags

spa/vite.config.js
n/a
Adds sourcemaps to the built SPA.
Removing them is a regression from previous behavior and makes it hard to troubleshoot issues.
Yes.
No.
Config change only.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-4297
No.
No.
=> DEV-4297: Add sourcemap to built SPA

spa/src/components/donationPage/DonationPage.jsx, spa/src/components/donationPage/DonationPage.styled.js, spa/src/components/donationPage/DonationPageForm.stories.tsx, spa/src/components/donationPage/DonationPageForm.styled.ts, spa/src/components/donationPage/DonationPageForm.test.tsx, spa/src/components/donationPage/DonationPageForm.tsx
n/a
1. Fixes a known issue where, after otherwise filling out the page, hitting Enter in the country field when it's blank and you have entered a value that doesn't match any country causes a page error.
2. Migrates the form submission logic in DonationPage to a separate component and adds unit tests/stories.
3. Removes `totalAmount` from DonationPage's context.
1. Fixes a potential problem source with contributions.
2. Improves test coverage of the contribution process.
3. We're not actually using `totalAmount` anywhere.
Yes.
No.
Yes.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-4266
No.
No.
=> DEV-4266: Factor out donation page form logic, add tests

apps/common/tests/test_utils.py, apps/common/utils.py
n/a
- Update post/patch & delete Cloudflare DNS functions to handle paginated scenarios (when total items is greater than the "per_page" value)
- Fixes the tests for `upsert_cloudflare_cnames` and `delete_cloudflare_cnames` (the assertions ware always passing, even if the asserted value was wrong)
- the bootstrap/teardown command fails to create the necessary DNS records when they are greater than the "per_page" value and fails silently
yes
no
yes
n/a
no
no
https://news-revenue-hub.atlassian.net/browse/DEV-3555
no
no
=> DEV-3555: Fix 300 record limit in Cloudflare DNS

spa/src/components/donationPage/DonationPage.jsx, spa/src/hooks/usePayment.ts
This PR touches two places in code that would cause a console.error that gets relayed to Sentry in case of 403 from NRE payments API. 403 is a normal state (got scored by bad actor too high, csrf expired) and not something we should be logging in Sentry.
Suppress Sentry noise.
Yes.
No.
No. 
I tried to spy on console.error to assert that it doesn't get called in event of 403, but that doesn't work because React default console.errors all errors, and it seems this error leaks somewhere because we end up it displayed in console.error (though not from anyplace we explicitly call this).
I looked into spying on sentry directly, and that did not seem easy. Our useSentry hook initializes sentry internally, so off the shelf solutions like …
=> DEV-4002 | Don't tell Sentry about 403 errors on payment creation

spa/src/components/donationPage/pageContent/DAmount.test.tsx, spa/src/components/donationPage/pageContent/DAmount.tsx
n/a
- Allows "Other amount" field to accept decimal numbers
- Allow contributors to enter decimal numbers 
yes
no
yes
n/a
no
no
https://news-revenue-hub.atlassian.net/browse/DEV-4233
no
no
=> DEV-4233: Allow for decimal numbers for Donations

spa/package-lock.json
n/a
Update spa's dependencies
Update spa's dependencies
n/a
no
n/a
n/a
no
n/a
https://news-revenue-hub.atlassian.net/browse/DEV-4410
no
no
=> DEV-4410: Deps upgrade

.pre-commit-config.yaml, poetry.lock
Sprintly backend dependencies update
Sprintly backend dependencies update
N/A
N/A
N/A
N/A
No
N/A
[DEV-4409](https://news-revenue-hub.atlassian.net/browse/DEV-4409)
No
N/A
[DEV-4409]: https://news-revenue-hub.atlassian.net/browse/DEV-4409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DEV-4409: update backend dependencies

apps/contributions/models.py, apps/contributions/tests/test_models.py, apps/emails/tests/test_views.py, conftest.py
This is a set of suggestions for discussion with Chris re: his original PR for DEV-4220.
=> Dev 4220 bw suggestions

spa/package-lock.json
n/a
- update dependencies
- update dependencies
- n/a
- no
- n/a
- n/a
- no
- n/a
- https://news-revenue-hub.atlassian.net/browse/DEV-4434
- no
- no
=> DEV-4434: dependencies update

spa/src/components/paymentProviders/stripe/stripeFns.test.ts, spa/src/components/paymentProviders/stripe/stripeFns.ts
n/a
Adds logging around why we're seeing errors around non-form elements getting serialized.
Gives us troubleshooting info.
Yes.
No.
Yes.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-4251
No.
No.
=> DEV-4251: Add logging around serializeData()

spa/src/hooks/usePortalAuth.test.tsx, spa/src/hooks/usePortalAuth.tsx
n/a
Sets the user identity in Sentry for contributors in the new portal.
Will help us troubleshoot issues.
Yes.
No.
Yes.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-4472
No.
No.
=> DEV-4472: Identify contributors in Sentry

spa/src/components/donationPage/pageContent/DAmount.styled.ts
n/a
- Fixes size of "other amount" field. It was inconsistent with bubbles in Firefox
- Improve UI that was broken by a browser
- Yes
- no
- No, only style changed
- n/a
- no
- no
- https://news-revenue-hub.atlassian.net/browse/DEV-4470
- no
- no
=> DEV-4470: Fix size of other amount field

spa/package-lock.json, spa/src/components/dashboard/sidebar/SidebarCoreUpgradePrompt/SidebarCoreUpgradePrompt.test.tsx
n/a
Dependencies upgrade
Fix test lint issue
Keeping spa up-to-date
yes
no
n/a
n/a
no
n/a
https://news-revenue-hub.atlassian.net/browse/DEV-4517
no
no
=> DEV-4517: Deps upgrade + lint fix

spa/package-lock.json
n/a
Update dependencies
Keeping deps up-to-date
n/a
no
n/a
n/a
no
n/a
https://news-revenue-hub.atlassian.net/browse/DEV-4556
no
no
=> DEV-4556: Deps update

spa/src/components/dashboard/sidebar/SidebarUpgradePrompt/SidebarUpgradePrompt.test.tsx, spa/src/components/dashboard/sidebar/SidebarUpgradePrompt/SidebarUpgradePrompt.tsx, spa/src/components/settings/Subscription/UpgradePlan.styled.ts, spa/src/components/settings/Subscription/UpgradePlan.test.tsx, spa/src/components/settings/Subscription/UpgradePlan.tsx
n/a
Remove Upgrade to Plus CTA
Exploring other ways of monetization
yes
no
yes
n/a
no
no
https://news-revenue-hub.atlassian.net/browse/DEV-4601
no
no
=> DEV-4601: Remove Upgrade to Plus CTA

spa/package-lock.json
n/a
Update dependencies
Update dependencies
n/a
no
n/a
n/a
no
n/a
https://news-revenue-hub.atlassian.net/browse/DEV-4728
no
no
=> DEV-4728: update deps

spa/package-lock.json
n/a
Deps update
Deps update
n/a
no
n/a
n/a
no
n/a
https://news-revenue-hub.atlassian.net/browse/DEV-4864
no
no
=> DEV-4864: Deps update

spa/package-lock.json, spa/package.json, spa/src/components/base/TextField/PhoneTextField.stories.tsx, spa/src/components/base/TextField/PhoneTextField.test.tsx, spa/src/components/base/TextField/PhoneTextField.tsx, spa/src/components/base/index.ts, spa/src/components/content/contributor-portal/ContributorPortal.test.tsx, spa/src/components/content/contributor-portal/ContributorPortal.tsx
n/a
- Implements Phone Number input and add it to Contributor Portal Edit page
- Improve the UX of adding a phone number
- Yes
- yes
- yes
- n/a
- no
- no
- https://news-revenue-hub.atlassian.net/browse/DEV-4848
- no
- no
=> DEV-4848: Implement Phone Number input

spa/package-lock.json
n/a
Deps update
Deps update
n/a
no
n/a
n/a
no
n/a
https://news-revenue-hub.atlassian.net/browse/DEV-4900
no
no
=> DEV-4900: Update FE deps

apps/contributions/management/commands/fix_incident_2445.py, apps/contributions/tests/test_management_commands.py
Adds a management command that can be run to fix contributions affected by incident 2445.
Fix data integrity on a set of affected contributions
Yes.
No
Yes
N/A
No
No
- [DEV-4963](https://news-revenue-hub.atlassian.net/browse/DEV-4963)
- [ITS-2448](https://news-revenue-hub.atlassian.net/browse/ITS-2448)
No
- [ITS-2448](https://news-revenue-hub.atlassian.net/browse/ITS-2448)
[DEV-4963]: https://news-revenue-hub.atlassian.net/browse/DEV-4963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ITS-2448]: https://news-revenue-hub.atlassian.net/browse/ITS-2448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DEV-4963 | Solve for issues created by incident 2445

apps/contributions/tests/test_views.py, apps/contributions/views.py
n/a
- Raise validation error instead of throwing error in case "interval" in unset
- Improve payment creation
- Yes
- no
- yes
- n/a
- no
- no
- https://news-revenue-hub.atlassian.net/browse/DEV-4702
- no
- no
=> DEV-4702: Assert interval is required and no exception is thrown

spa/src/components/portal/ContributionsList/ContributionsList.styled.ts, spa/src/components/portal/ContributionsList/ContributionsList.test.tsx, spa/src/components/portal/ContributionsList/ContributionsList.tsx
n/a
- Hides Impact Tracker for initial launch
- Impact tracker isn't quite working, so we are hiding it until it's fixed.
- Yes
- Yes
- Yes
- n/a
- no
- n/a
- https://news-revenue-hub.atlassian.net/browse/DEV-4973
- no
- no
=> DEV-4973: Hide Impact tracker for launch

revengine/settings/deploy.py
n/a
Fixes an issue with image thumbnail fields that caused errors when viewing pages or saving changes in the page editor.
Fixes a bug that prevents usage of the page editor.
Yes.
No.
This is a config-only change.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-5015
No.
No.
=> DEV-5015: Set Google Cloud storage settings globally

spa/package-lock.json
n/a
Routine front-end updates.
Not needed.
No.
No, dependency updates only.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-5003
No.
No.
=> DEV-5003: Front-end dep updates

.pre-commit-config.yaml, poetry.lock
n/a
Deps upgrade
n/a
no
n/a
n/a
no
n/a
[DEV-5012]
no
no
[DEV-5012]: https://news-revenue-hub.atlassian.net/browse/DEV-5012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DEV-5012: upgrade dependencies

.github/workflows/dependency-review.yml, .pre-commit-config.yaml, apps/contributions/tests/test_views.py, poetry.lock
N/A
- Deps upgrade
- Cherry-picked @GuiMend 's commit which fixes test failure on test_contributions_list_filter_by_rp - cfa0cae1e98704c302603ad50fa5b14dfccc16bd
- Sprint maintenance task
N/A
N/A
N/A
N/A
There is one test failure due to sentry vulnerability. We are currently using version 1.45.1; CVE says it's been back ported to our version but it still fails on GH action https://github.com/advisories/GHSA-g92j-qhmh-64v2
N/A
[DEV-5073]
N/A
Sentry upgrade [DEV-5102]
[DEV-5073]: https://news-revenue-hub.atlassian.net/browse/DEV-5073
[DEV-5102]: https://news-revenue-hub.atlassian.net/browse/DEV-5102
=> DEV-5073: deps upgrade

spa/package-lock.json
n/a
Deps upgrade
Deps upgrade
n/a
no
n/a
n/a
no
n/a
https://news-revenue-hub.atlassian.net/browse/DEV-5071
no
no
=> DEV-5071: Deps upgrade - RevEngine Front End

.github/workflows/chromatic.yml, .github/workflows/dependency-review.yml, .github/workflows/pre-commit.yml, .github/workflows/test-js.yml, .github/workflows/test-python.yml, .pre-commit-config.yaml, poetry.lock
N/A
- Deps upgrade
N/A
Yes
N/A
N/A
N/A
[DEV-5172]
N/A
N/A
[DEV-5172]: https://news-revenue-hub.atlassian.net/browse/DEV-5172
=> DEV-5172: deps upgrade

spa/package-lock.json
n/a
FE deps upgrade
FE deps upgrade
n/a
n/a
n/a
n/a
no
n/a
https://news-revenue-hub.atlassian.net/browse/DEV-5233
no
no
=> DEV-5233: FE deps upgrade

spa/src/components/donationPage/DonationPage.jsx
n/a
Adds error handling around deletion of a payment when an error occurs.
Gives us more data on why this is happening.
n/a
No.
Not needed imho but if I'm open to suggestions.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-5094
No.
No.
=> DEV-5094: Add try around payment deletion on error

.pre-commit-config.yaml, apps/organizations/signals.py, poetry.lock
N/A
- Deps upgrade
N/A
Yes
N/A
N/A
N/A
[DEV-5270]
N/A
N/A
[DEV-5270]: https://news-revenue-hub.atlassian.net/browse/DEV-5270
=> DEV-5270: deps upgrade

spa/package-lock.json
n/a
Update FE dependencies
Update FE dependencies
n/a
no
n/a
n/a
no
n/a
https://news-revenue-hub.atlassian.net/browse/DEV-5269
no
no
=> DEV-5269: FE deps upgrade

apps/contributions/models.py, apps/contributions/tests/test_models.py, apps/emails/templates/nrh-default-contribution-base-template.html, apps/emails/templates/nrh-default-contribution-base-template.txt, apps/emails/templates/recurring-contribution-amount-updated.html, apps/emails/templates/recurring-contribution-amount-updated.txt, apps/emails/views.py
n/a
- Sends email for contributors when they change a contribution amount
- Improve communication 
- ye
- yes
- yes
- Email is sent for contributors when they change a contribution amount
- no
- no
- https://news-revenue-hub.atlassian.net/browse/DEV-5276
- no
- no
=> DEV-5276: Send amount change email

revengine/settings/base.py
n/a
Adds config to allow Cloudflare, Parsely, and Doubleclick in CSP.
These are services we are currently using.
Yes.
No.
n/a
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-2311
No.
No.
=> DEV-2311: Update CSP for Cloudflare, Parsely, Doubleclick

apps/contributions/serializers.py, apps/contributions/tests/test_serializers.py
This PR refactors `BadActorSerializer`, removing an over-ride of `to_internal_value`. As noted in ticket for this PR, I discovered the following oddity:
```
from apps.contributions.serializers import BadActorSerializer
instance  = BadActorSerializer(data={"first_name": "foo", "last_name": "bar", "email": "foo@bar.com", "amount": "12400", "ip":  "192.0.2.1", "referer": "https://fundjournalism.org" })
instance.is_valid()
instance.errors
Out[4]: {'street': [ErrorDetail(string='This field may not be null.', code='null')], '.....
```
Not totally clear why, but somehow using the over-ride of to_internval_value cased the default values for those fields to not be present, triggering a validation error.
Unclear if any bugs directly resulted …
=> DEV-5216 | Make BadActorSerializer more idiomatic

spa/src/components/donationPage/live/GenericThankYou/GenericThankYou.test.tsx, spa/src/components/donationPage/live/GenericThankYou/GenericThankYou.tsx
n/a
Fixes error when returning to Generic Thank you page
When going back to Generic Thank you page, user saw an error and the page breaks
yes
no
yes
n/a
no
n/a
https://news-revenue-hub.atlassian.net/browse/DEV-3528
no
no
=> DEV-3528: Handle missing router state in thank you page

.pre-commit-config.yaml, poetry.lock
N/A
- Deps upgrade
N/A
Yes
N/A
N/A
N/A
[DEV-5318]
N/A
N/A
[DEV-5318]: https://news-revenue-hub.atlassian.net/browse/DEV-5318
=> DEV-5318: deps upgrade

spa/package-lock.json
n/a
FE deps upgrade
FE deps upgrade
n/a
no
n/a
n/a
no
n/a
https://news-revenue-hub.atlassian.net/browse/DEV-5312
no
no
=> DEV-5312: FE deps upgrade

spa/package-lock.json
n/a
FE deps update
FE deps update
n/a
no
n/a
n/a
no 
n/a
https://news-revenue-hub.atlassian.net/browse/DEV-5334
no
no
=> DEV-5334: FE deps update

.pre-commit-config.yaml, apps/common/tests/test_secrets.py, apps/contributions/tests/test_serializers.py, apps/contributions/tests/test_stripe_contributions_provider.py, apps/pages/tests/test_serializers.py, poetry.lock
n/a
BE deps update
BE deps update
n/a
no
n/a
n/a
no
no
https://news-revenue-hub.atlassian.net/browse/DEV-5433
no
no
=> DEV-5433: BE deps update

.pre-commit-config.yaml, apps/contributions/tests/test_serializers.py, poetry.lock
n/a
- Backend deps update
- Fixed small test error (bubble up after deps upgrade)
N/A
N/A
N/A
N/A
N/A
N/A
[DEV-5477]
N/A
N/A
[DEV-5477]: https://news-revenue-hub.atlassian.net/browse/DEV-5477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DEV-5477: deps upgrade

spa/package-lock.json
FE deps update
FE deps update
n/a
no
n/a
n/a
no
n/a
https://news-revenue-hub.atlassian.net/browse/DEV-5467
no
no
=> DEV-5467: FE deps update

apps/contributions/admin.py, apps/contributions/tests/test_admin.py
n/a
Add First Payment Date to Contribution admin
Remove Created date from Contribution admin
To make it match current contributor portal.
yes
no
n/a
n/a
no
no
https://news-revenue-hub.atlassian.net/browse/DEV-5232
no
no
=> DEV-5232: Add First Payment Date to Contribution admin

apps/contributions/admin.py, apps/contributions/tests/test_admin.py
n/a
Fix first payment date in admin search field
Search for contributions in django admin was broken
yes
no
n/a
n/a
no
n/a
https://news-revenue-hub.atlassian.net/browse/DEV-5508
no
no
=> DEV-5508: Fix first payment date in admin search field

spa/package-lock.json, spa/package.json, spa/src/components/common/GlobalLoading/GlobalLoading.test.tsx
n/a
SPA dependency updates.
I changed the version of `@types/react-dom` because it was out of sync with the version of `react-dom`, and it was giving an error message when  running `npm update`. This also required a small update to one unit test suite.
Regular task.
n/a
No.
No, deps update only.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-5500
No.
No.
=> DEV-5500: Update SPA dependencies

spa/package-lock.json
n/a
FE deps upgrade
FE deps upgrade
n/a
no
n/a
n/a
no
n/a
https://news-revenue-hub.atlassian.net/browse/DEV-5603
no
no
=> DEV-5603: FE deps upgrade

spa/package-lock.json
n/a
Routine front-end dependency updates.
Recurring task.
n/a
No.
No, dep updates only.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-5740
No.
No.
=> DEV-5740: Front end dep updates

.pre-commit-config.yaml, poetry.lock
N/A
Deps upgrade
N/A
N/A
N/A
N/A
N/A
N/A
[DEV-5797]
N/A
N/A
[DEV-5797]: https://news-revenue-hub.atlassian.net/browse/DEV-5797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DEV-5797: deps upgrade

spa/package-lock.json
n/a
Regular dep updates.
Not needed.
No.
n/a
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-5760
n/a
No.
=> DEV-5760: SPA dep updates

.pre-commit-config.yaml, poetry.lock
N/A
Deps upgrade
Maintenance task.
N/A
N/A
N/A
N/A
N/A
N/A
[DEV-5945]
N/A
[DEV-5945]: https://news-revenue-hub.atlassian.net/browse/DEV-5945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DEV-5945: deps upgrade

spa/package-lock.json
n/a
Periodic dependency updates.
QA not needed.
No.
No, deps only.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-5959
No.
No.
=> DEV-5959: SPA dep updates

revengine/settings/base.py
https://docs.sentry.io/platforms/javascript/install/loader/#content-security-policy
n/a
Configures CSP policy to match https://docs.sentry.io/platforms/javascript/install/loader/#content-security-policy.
Improves CSP policy.
n/a
No.
No, config changes only.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-3162
No.
Rest of CSP epic.
=> DEV-3162: Allow Sentry in CSP

.pre-commit-config.yaml, .talismanrc, apps/contributions/tests/test_tasks.py, poetry.lock
N/A
Deps upgrade
Maintenance task
N/A
N/A
N/A
N/A
N/A
N/A
[DEV-6043]
N/A
N/A
[DEV-6043]: https://news-revenue-hub.atlassian.net/browse/DEV-6043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DEV-6043: deps upgrade

.talismanrc, spa/package-lock.json
Regularly scheduled SPA-side deps upgrade.
Bug fixes and vulnerability patches
N/A
No
N/A
N/A
No
N/A
- [DEV-6006](https://news-revenue-hub.atlassian.net/browse/DEV-6006)
- [DEV-6102](https://news-revenue-hub.atlassian.net/browse/DEV-6102)
- [DEV-6103](https://news-revenue-hub.atlassian.net/browse/DEV-6103)
- [DEV-6104](https://news-revenue-hub.atlassian.net/browse/DEV-6104)
- [DEV-6105](https://news-revenue-hub.atlassian.net/browse/DEV-6105)
- [DEV-6106](https://news-revenue-hub.atlassian.net/browse/DEV-6106)
- [DEV-6107](https://news-revenue-hub.atlassian.net/browse/DEV-6107)
- [DEV-6108](https://news-revenue-hub.atlassian.net/browse/DEV-6108)
[DEV-6006]: https://news-revenue-hub.atlassian.net/browse/DEV-6006?atlOrigin=eyJpIjoiNWRk …
=> upgrade deps

spa/src/hooks/usePortalContribution.test.tsx, spa/src/hooks/usePortalContribution.tsx
n/a
When the SPA receives an error message from the backend when updating a contribution, it now shows that message.
Better feedback to users.
Yes.
No.
Yes.
n/a
Not sure how to handle the scenario when more than one error is returned.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-6041
No.
No.
=> DEV-6041: Show error message detail when backend returns one updating a contribution

apps/contributions/tests/fixtures/balance-transaction-for-subscription-creation.json, apps/contributions/tests/fixtures/payment-intent-for-recurring-charge.json, revengine/settings/base.py
N/A
- Added comment near GENERIC_STRIPE_PRODUCT_NAME so we remember any changes to this need to be coordinated with Switchboard
- Changed fixtures to match generic product name
- Switchboard uses the value of `GENERIC_STRIPE_PRODUCT_NAME` in the DigestBuilder integration. If the name of the product changes, then we need to coordinate changes on both repos
- Changed fixtures to match the product name we use
N/A
N/A
N/A
N/A
N/A
N/A
[DEV-6154]
N/A
N/A
[DEV-6154]: https://news-revenue-hub.atlassian.net/browse/DEV-6154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Dev 6154 update comments product names

spa/package-lock.json
n/a
Periodic deps upgrade.
n/a
No.
Not needed.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-6146
No.
No.
=> DEV-6146: Deps upgrade

.pre-commit-config.yaml, .talismanrc, apps/api/tests/test_views.py, apps/common/tests/test_utils.py, apps/contributions/models.py, apps/contributions/stripe_import.py, apps/emails/tasks.py, apps/organizations/models.py, apps/users/models.py, poetry.lock
n/a
Periodic deps upgrade + a few noqa additions due to new ruff rules
n/a
No.
Not needed.
n/a
No.
No.
[DEV-6203]
No.
No.
[DEV-6203]: https://news-revenue-hub.atlassian.net/browse/DEV-6203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DEV-6283: deps upgrade

.talismanrc, spa/package-lock.json
n/a
Periodic deps upgrade.
n/a
No.
Deps changing only.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-6362
No.
No.
=> DEV-6362: SPA deps upgrade

spa/src/components/content/emails/edit/EditEmailRoute.tsx
n/a
Removes an icon on a cancel button.
Matches things up to Figma.
Yes.
No.
Not needed since it's a cosmetic change.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-6370
No.
No.
=> DEV-6370: Remove icon from button
