apps/pages/admin.py
revengine/settings/base.py

Fixes two issues discovered in demo today:
1. "styles" inline missing from DonationPage and Template admins
2. API explorer not hooked up.

Styles inline api explorer

---

poetry.lock
pyproject.toml

3.2.1: https://www.djangoproject.com/weblog/2021/may/04/security-releases/
3.2.2: https://www.djangoproject.com/weblog/2021/may/06/security-releases/
Tests pass and smoke test of site functions as expected.

[NRH-52] Applies security patches

---

README.md
revengine/settings/base.py
revengine/settings/dev.py

Configured with plain SMTP authentication. Details are in LP.
To test locally: Get PW from LP and add to your environment run `./manage.py sendtestemail nrh-team@caktusgroup.com`

[NRH-54] Email configured to use vanilla SMTP

---

spa/src/components/authentication/Login.js

Fixes a bug with forgot password flow that stemmed from routing the URL through the SPA, rather than to the backend.

hotfix: use window.location instead of history.push on password reset in SPA

---

.github/workflows/tests.yml
spa/cypress/integration/donation-page-edit.spec.js
spa/package-lock.json
spa/package.json
spa/src/components/pageEditor/PageEditor.js
spa/src/components/pageEditor/editInterface/ElementProperties.js
spa/src/components/pageEditor/validatePage.js
spa/src/elements/alert/Alert.js
spa/src/elements/alert/Alert.styled.js

Enables page validation and enables required-element validation. Any validation beyond that is possible, but it's not clear at the moment what that would need to be.
It's worth noting that I vacillated a bit on whether or not to handle the validation on the backend with a PageElementsSerializer. I think there's lots of value in that (eg I particularly don't like front-end validation), but if we do that, fully controlled page elements start to recommend themselves. Rather than Page.elements being a flexible JSON field, Page.elements would be a one-to-many to an Element model. That's fine and all, but it's probably a bit more control than we need/want for this version. 
The way we have it now, adding more features to the donation page only requires front-end changes, and that's a big plus.

[NRH-120] Page-edit validation

---

spa/src/components/donationPage/DonationPage.js
spa/src/components/donationPage/pageContent/DFrequency.js
spa/src/components/pageEditor/PageEditor.js

If "one_time" was not an available frequency, not initial frequency was set, allowing a case where somebody could submit a donation withoiut selecting a frequency. There should always be a frequency selected.
Also fixed a missing JSON.stringify in elements data parsing.

[NRH-132] Missing initial frequency bug

---

apps/api/tests/test_views.py
apps/api/views.py
revengine/settings/base.py

Modifies the magic_link view to send using the mailgun API.
Updates tests
To test locally:
- If you care to click the link when you get the email you will need to have your settings.SITE_URL set to "http://localhost:8001" or your ngrok host if that is what you are using.
- In a terminal run `inv dc.run-celery`
- In another terminal run `make run-dev`
Then you should be able to hit the `contributor/` endpoint and send an email with the magic_link.

refs #NRH-148 Sends magic_link through Mailgun

---

apps/contributions/admin.py
revengine/settings/deploy.py

Turns out `USE_DEBUG_INTERVALS` was not being read from the env on staging. Changed that and made sure that env vars in Heroku had `USE_DEBUG_INTERVALS = True`.
This is not guaranteed to be the only issue here, but considering that there were no recurring contributions more than a month old, it seems likely that this is why we haven't seen any contributions re-up.
After this point, any recurring contributions made while `USE_DEBUG_INTERVALS = True` should be truncated (as much as Stripe allows) such that:
revengine 'Monthly' = stripe 'Daily'
revengine 'Yearly' = stripe 'Weekly'
Also removed "contributor__email" from the django admin Contributions list view as it was just really noisy, and added in the much more useful `interval` filter.

[NRH-161] Recurring payments not recurring

---

apps/api/serializers.py
apps/api/tests/test_views.py
spa/src/components/donationPage/pageContent/DAmount.js
spa/src/components/donationPage/pageContent/DPayment.js
spa/src/components/pageEditor/editInterface/pageSetup/PublishWidget.js
spa/src/components/paymentProviders/stripe/StripePaymentForm.js

Fixes hopefully two bugs:
1. A bug where, somehow, a page has gotten in to a state where a given `frequency` in `element.content?.options[frequency]` is not actually in the `options` object. This should only be possible with pretty funky stale data, and we've only seen this particular issue locally. 
2. An error in page edit mode, with sparse reporting, indicating that `<something>.stripe` is undefined. Since that pattern only occurs in a few places, we've just judiciously defaulted those chained references to null. 
We also, incidentally, update the "this field may not be blank" front facing error message to something a little less django-y
For each above:
1. It's unknown how to reproduce this bug. It hasn't occurred on staging, and locally it's only occurred once as far as we know. But …

[NRH]--bugfix--DAmount Badindex

---

spa/src/components/pageEditor/PageEditor.js
spa/src/components/pageEditor/editInterface/pageStyles/AddStylesModal.js
spa/src/components/pageEditor/editInterface/pageStyles/PageStyles.js

Fixes two bugs:
1. Newly created styles wouldn't appear in the list of styles after creation
2. Could save newly created styles
Try to do both those things
Nope

[NRH-203-205] bugfix New styles bugs

---

spa/src/components/pageEditor/elementEditors/amount/AmountEditor.js

Fixes a bug where, in the AmountEditor widget, toggling "Include 'other' option" would not save to the page.
Go in to a page editor, edit an Amount widget, toggle on or off "Include 'other' option", ensure that it is saved to the page.
Nope

[NRH-195] bugfix OtherAmount toggle not saving

---

spa/cypress/integration/donations.spec.js

Updates `donation.spec.js` to fix some flaky Cypress tests that passed sometimes and failed others, seemingly from a race condition between UI completely rendering and Cypress running test commands.
Should no longer see Cypress tests for `donation-spec.js` "randomly" failing in CI.
No.

NRH: Fix flaky cypress tests

---

spa/src/components/contributor/contributorDashboard/ContributorDashboard.js

We failed to disabled Payment method updates in the contributor/contributions table.  This disables that.
"Login" as a contributor. View your donations. Find a one-time donation and verify that clicking on the credit card info does nothing, unlike clicking on the card info for a recurring donation.
No

NRH-209 bugfix OneTime payments allow paymentmethod updates

---

spa/cypress/integration/contributor.spec.js

Gets `    it('should show update payment method modal when payment method clicked for recurring contribution',)` from contributor.spec.js to pass.
Turns out the reason it was passing locally is that there were upstream changes in develop that I was unaware of that fixed the bug whereby you could get the update payment method modal for one time payments. When the test ran in CI, it was based on merging feature branch into develop, so the two testing environments were not identical. There were no merge conflicts appearing in the PR, so I was not aware this was causing the issue. Add on top of that that there were some flaky tests that were failing in CI while passing locally (the root problem of which was solved), and that led to me not understanding the underlying issue.
Test passes in CI …

try selecting recurring donation to get test to pass

---

spa/src/components/pageEditor/editInterface/EditInterface.js
spa/src/components/pageEditor/elementEditors/payment/PaymentEditor.js

Fixes a bug that caused the payment element to explode when selected on the PageEditor.
1. Open the PageEditor
2. Add the Payment Element
3. Select the Payment Element
No.

Nrh 208  payment block causes error

---

spa/cypress/fixtures/pages/live-page-1.json
spa/cypress/integration/donation-page-edit.spec.js
spa/src/components/donationPage/pageContent/DAmount.js

Modifies a regression where fractional OtherAmounts were disabled.
1. Go to a donation page with other amount enabled
2. Add a fractional donation. (e.g 42.42)
3. Note that the donation button reflects the fractional change
No.

refs #NRH-220 Allows fractional other amounts.

---

spa/src/components/pageEditor/PageEditor.js

Fixes a bug in which the preview thumbnail in the page list view appeared to be showing the second-to-latest page version.  In fact, what was happening was that when the page preview was being generated (on page save), the page briefly displayed the unedited version (this happened to occur for just a moment, exactly when the code to generate the screenshot runs). So the screenshot saved was the unedited version.
Edit a page with something obvious, like a drastic style change. Observe that the thumbnail in the page list view shows your changed version and not the previous version.
No

[NRH-219] Bugfix Preview thumbnail

---

spa/src/utilities/calculateStripeFee.js

Makes a few tweaks the Stripe fee calculation:
- Rounds to 2 decimal places before the final fee is calculated, in addition to at the end
- Removes a mistaken redundant calculation
Maybe just calculate what you think your fee should be and compare it to what it is. (only particularly large numbers are likely to show a difference from the previous iteration).
No

[NRH-255] stripe fee calculation tweaks

---

spa/cypress/integration/donations.spec.js
spa/src/components/donations/filters/CreatedFilter.js
spa/src/components/donations/filters/CreatedFilter.styled.js

In the Org donations list view, the "Date" filter datepickers were previously not clearable. Now you can clear them.
Go to /dashboard/donations and filter to a date range, then clear out one or the other dates by clicking the red "x". Observe that the filter for that part of the range is removed from the results.
No

[NRH-223] Clearable date filters

---

spa/cypress/integration/donation-page-edit.spec.js
spa/cypress/support/commands.js
spa/src/components/donationPage/pageContent/SHeaderBar.js
spa/src/components/pageEditor/PageEditor.js
spa/src/components/pageEditor/editInterface/EditInterface.js
spa/src/components/pageEditor/editInterface/EditInterfaceTabs.js
spa/src/components/pageEditor/editInterface/pageSetup/PageSetup.js
spa/src/components/pageEditor/elementEditors/additionalInfo/AdditionalInfoEditor.js
spa/src/elements/inputs/BaseField.js

As reported in NRH-213, some images weren't displaying thumbnails after accepting changes. And some link fields in the setup tab weren't being saved, or error messages were displayed.  Each of these issues has a separate solution here. 
- The images needed to be explicitly converted to ObjectUrls when displaying browser-memory based thumbnails.
- One link type, the "Logo link" didn't have the right name attribute on its input.
- The other links were working, but they were returning validation errors (valid urls start with protocol). The bulk of the work in this PR is implementing a mechanism to show error messages inline for fields inside the EditInterface, in the Setup tab.
Try to add images in the setup tab: Thumbnails should appear.
Try to save all three link types. They should be …

[NRH-213] bugfix setup tab images and links broken

---

spa/src/components/pageEditor/PageEditor.js

Causes page screenshot to only occur if REACT_APP_CAPTURE_PAGE_SCREENSHOT is 'true'. Since REACT_APP_ env vars aren't working right now, this effectively disables screenshot capture. It is hoped that this will fix the page save 503 issue referenced in [this PR](https://github.com/newsrevenuehub/rev-engine/pull/104)
Hopefully page edits can be saved now.
set REACT_APP_CAPTURE_PAGE_SCREENSHOT to 'true' if we want to enable screen capture.

Disable page screenshot

---

apps/slack/slack_manager.py
apps/slack/tests/test_slack_integration.py

A bugfix. Contributions were stuck in processing. This was reproducible if you provided invalid Slack credentials to either an org or Hub. It seems to be the case that Contribution.save was failing because we failed to except SlackApiErrors. Those should be caught now.
Set all SlackIntegrations values to invalid values (ie empty strings) and make a contribution. Previously, this contribution would get stuck in "processing". It should now have its status updated, even if slack notifications failed to send. Additionally, warn and error level logging should occur-- which at least at time of writing, triggers sentry notifications and admin emails respectively.
No.

[NRH-249]  Contributions stuck in processing

---

spa/src/utilities/calculateStripeFee.js

One of those "typescript would have caught this, but is it really worth it?" times. The "amount" argument in calculateStripeFees can be an int or a string. The string wasn't being handled properly. 
Stripe fees should be calculated accurately now.
no

[NRH-260] handle string amount

---

apps/contributions/payment_managers.py
apps/contributions/tests/test_payment_managers.py

See [this basecamp post](https://3.basecamp.com/3120230/buckets/21497549/messages/3959124486) for some context. We are now creating a stripe.Customer for each one-time payment, associated with the org, attached to the PaymentIntent. Metadata is bundled and added to that customer.
Make a one-time donation. Observe that a stripe customer is attached to the resulting contribution. Observe that that customer has metadata in Stripe.
No.

[NRH-257] stripe.Customer for One-time payments

---

README.md
apps/contributions/serializers.py
spa/cypress/integration/donation-page.spec.js
spa/src/components/donationPage/DonationPage.js
spa/src/components/donationPage/live/LivePage404.js
spa/src/components/paymentProviders/stripe/StripePaymentForm.js
spa/src/components/paymentProviders/stripe/stripeFns.js

If a donor visits `/my-rev-program/my-donation-page?campaign=my-sf-campaign-id`, the value of the `campaign` qp is passed in the form submit request body then added to Stripe Metadata for the payment object (Subscription or PaymentIntent).  The expected query parameter is `campaign`, but this is set up to be configurable if this ever needs to change. The env var `REACT_APP_SALESFORCE_CAMPAIGN_ID_QUERYPARAM` can change the value (defaults to 'campaign' if unset).
Visit a donation page with the `campaign` queryparam set. Make a donation. Observe that sf_campaign_id is set on stripe metadata
No

[NRH-182] SF Campaign ID

---

apps/contributions/bad_actor.py
apps/contributions/tests/test_views.py
apps/contributions/views.py

This aims to fix a bug in which payments selected for rejection in the Org Dashboard ended up being marked as "paid".
Reject a flagged contribution by clicking on a list item that is flagged in the contributions list, scrolling down and clicking "Reject". Refresh the page to view the new status of that particular contribution. It should now say "Rejected" instead of "Paid".
No

[NRH-281] Reject-flagged showing as paid

---

spa/src/utilities/calculateStripeFee.js

Changes calculateStripeFees to use the rates:
NP = 2.7%
FP = 2.9%
Fixed = $0.30
And changes the formula to just use exactly what stripe says we should use to pass on fees.
Make a donation with and without paying fees. You should probably do this on an org that does not report being non-profit. Stripe won't recognize any of our test orgs as being nonprofits and will always charge the for-profit rate. If you're particularly keen to test a proper non-profit org, you can[ see here ](https://stripe.com/docs/connect/testing#test-business-tax-ids)roughly what will be necessary. Once you've made the donation successfully and it has been 'paid', go to the Stripe dashboard for that org and view the transaction. Stripe will show you a breakdown of the charges. Your final take-home should be the …

[NRH-287] Just do exactly what stripe says for passing on fees

---

spa/cypress/integration/donation-page-edit.spec.js
spa/cypress/integration/donation-page.spec.js
spa/cypress/support/commands.js
spa/src/components/donationPage/DonationPage.js
spa/src/components/donationPage/pageContent/DAmount.js
spa/src/components/donationPage/pageContent/DFrequency.js
spa/src/components/donationPage/pageContent/DRichText.styled.js
spa/src/components/pageEditor/PageEditor.js
spa/src/components/pageEditor/editInterface/pageSetup/PageSetup.js
spa/src/components/pageEditor/elementEditors/amount/AmountEditor.js
spa/src/components/pageEditor/elementEditors/amount/AmountEditor.styled.js
spa/src/components/pageEditor/elementEditors/frequency/FrequencyEditor.js
spa/src/components/pageEditor/elementEditors/frequency/FrequencyEditor.styled.js

Tickets 236, 237 and 238 are implemented on this PR. We've added the ability to select default selected amounts per frequency, default selected frequency. We're also responding to the `amount` and `frequency` query parameters as outlined in the requirements.
1. Edit a donation page.
2. Edit the Frequency element
3. Observe that you can check one or zero "default" checkboxes.
4. Edit the Amount element
5. Observe that you can click on an amount (not the X) and it will highlight, indicating that it is the default for that frequency.
6. Save your changes and visit the page live.
7. Observe that the defaults, as set above, are selected (for each frequency).
8. Next, add `amount=99` and/or `frequency=monthly` or some combination of some amount and frequency, and observe that the behavior is as …

[NRH-236-237-238] Amount and Frequency queryparams and defaults

---

spa/cypress/integration/donation-page-edit.spec.js
spa/src/components/donationPage/pageContent/DBenefits.js
spa/src/components/donationPage/pageContent/DBenefits.styled.js
spa/src/components/donationPage/pageContent/DImage.styled.js
spa/src/components/donationPage/pageContent/DRichText.styled.js
spa/src/components/donationPage/pageContent/dynamicSidebarElements.js

This PR make it so a hub admin can add the Benefits block for a revenue program to the sidebar of the page.
1. Create some Benefits `admin/organizations/benefit/`
2. Create  a/some Benefit Level(s) `admin/organizations/benefitlevel/`
3. Add the Benefits you created to the Benefit Level
4. Add the Benefit Level(s) you created to a Revenue Program.
5. Navigate a Page that is attached to that Revenue Program.
6. Open the Sidebar editor
7. Click the add button
8. Select the Donor Benefits Element.
Note: The order the Benefit Levels appear on the page right now only makes sense if the levels are ordered from least to most inclusive (i.e., Bronze is ordered before Silver and Silver's benefits include everything in Bronze plus the added silver benefits)
No.

Nrh 283  apply benefit level

---

apps/contributions/models.py
apps/contributions/tests/test_models.py

This PR fixes a bug where ContributionMetadata with the following properties:
1. Processor type of ALL
2. No Default
3. Value supplied via the Front end in a query param
was not being included in the metadata sent to stripe.
1. Add a ContributionMetadata object in the admin with the key (`sf_campaign_id`)
2. No default value
3. Go to a live donation page
4. Add the query param `?campaign=abc-123`
5. Make the donation.
6. Find the Payment, Subscription or Customer on stripe and the Metadata section should contain `sf_campaign_id = abc-123`
No

refs #NRH-301 Metadata with ALL and no default picked up.

---

spa/cypress/integration/donation-page.spec.js
spa/cypress/support/commands.js
spa/src/components/donationPage/DonationPage.js
spa/src/components/donationPage/DonationPageStaticText.js
spa/src/components/donationPage/pageContent/DPayment.js
spa/src/components/pageEditor/elementEditors/payment/PaymentEditor.js
spa/src/components/pageEditor/elementEditors/payment/PaymentEditor.styled.js
spa/src/components/paymentProviders/stripe/StripePaymentForm.js
spa/src/components/paymentProviders/stripe/stripeFns.js
spa/src/utilities/calculateStripeFee.js

First of all, this PR adds the ability to select whether or not "Pay fees" comes pre-selected.
Second, this PR adds the code to add a 0.5% upcharge for subscription fees. As per the discussion in this basecamp post, we've commented out the final piece of this code so that it does not take effect. We'll rip it out or uncomment it later depending.
For now, just check the "selected by default" toggle in the Payment editor beneath "Offer pay fees".  Observe that the live page has the Pay fees bit checked by default.
No

[NRH-269] Update fees stuff

---

spa/src/components/contributor/contributorDashboard/ContributorDashboard.styled.js

I almost punted on this, since it's contributor portal, but it turns out it was already done. This would have been fixed by fixing the "Org admin contributions list", as it's the same code. There's a PR here because I didn't like the padding when I viewed the Contributor portal and it was a tiny change.
Go to contributor portal and view it at mobile breakpoints. Observe lack of obtrusive padding around edges. More to the point of the ticket though, observe that the table is no longer a table, but in fact a list of cards. 
No

[NRH-176] fix mobile padding a little

---

spa/src/components/analytics/HubTrackedPage.js
spa/src/components/donationPage/DonationPage.js
spa/src/components/donationPage/pageContent/DAmount.js
spa/src/components/pageEditor/editInterface/pageSetup/PageSetup.js
spa/src/components/paymentProviders/stripe/stripeFns.js

Bugfix. To reproduce original bug:
Say you've got a page with a static donation option of $10. Try to type "100" in to the "Other" section, and noticed that the focus gets "stolen" by the $10 bit before you can type the second "0". 
This PR fixes that.
Do the above and observe that the focus is no longer stolen.
No

[NRH-312] Amount "other" weirdness

---

apps/contributions/payment_managers.py
apps/contributions/tests/test_payment_managers.py

We get a decent number of these Stripe InvalidRequestErrors. Without the contribution pk, the error messages aren't very useful. This ticket adds the contribution pk, as well as the original stripe response to that error log.
Don't know.
No

[NRH] Improve Stripe InvalidRequestError message

---

apps/contributions/models.py
apps/contributions/tests/test_models.py
spa/src/components/paymentProviders/stripe/stripeFns.js

Adds the `donor_selected_amount` to the frontend formData. This also handles the request for NRH-334 and renames the fields that were.
1. Add `donor_selected_amount` to Contribution Metadata as a Payment object.
2. Create a payment either subscription or one-time
3. Navigate to the Payment in Stripe and observe the `donor_selected_amount` in the Metadata.
`donor_selected_amount` needs to be added in the django admin for each deployed environment.

refs #NRH-333 and NRH-334 Adds donor_selected_amount renames fields

---

apps/contributions/models.py
apps/contributions/tests/test_models.py
spa/src/components/paymentProviders/stripe/stripeFns.js

Adds an additional empty string filter.
1. Add all the additional info items to a DonationPage
2. Make a contribution on that DonationPage. Leave all AdditionalInfo fields blank
3. Observe that none of the fields are transmitted to Stripe.
No

Nrh 338  bugfix empty metadata fields in stripe

---

spa/cypress/integration/donation-page.spec.js
spa/cypress/integration/pages.spec.js
spa/src/components/donationPage/DonationPage.js
spa/src/components/donationPage/DonationPageRouter.js
spa/src/components/donationPage/pageContent/DPayment.js
spa/src/components/paymentProviders/stripe/StripePayment.js

Addresses the issue mentioned in [this basecamp post](https://3.basecamp.com/3120230/buckets/21497549/messages/4088827225). Instead of spinning here, we'll get a 404 now. The underlying issue causing the page not to load is that the organization being used in the video in that post was missing required information for stripe to work. It shouldn't be possible to get in to that state without messing with stuff in the django admin, but just in case, we should handle that with a 404.
Try to access the page mentioned in the basecamp post and notice a 404 instead of a spinner.
No

[NRH-339] Spinning live page

---

spa/cypress/integration/donation-page.spec.js
spa/src/components/paymentProviders/stripe/StripePayment.js
spa/src/components/paymentProviders/stripe/StripePaymentForm.js
spa/src/components/paymentProviders/stripe/stripeFns.js

Fixes a misnamed key in the loadStripe configuration parameter that was causing payments to be created on Hub Stripe, not Org Stripe. Thereby disabling payments altogether.
Payments should work now.
No

Misnamed stripe_account param in loadStripe

---

apps/contributions/serializers.py
spa/cypress/integration/donation-page.spec.js
spa/src/components/paymentProviders/stripe/StripePaymentForm.js
spa/src/components/paymentProviders/stripe/stripeFns.js
spa/src/constants/genericConstants.js
spa/src/hooks/useReCAPTCHAScript.js

Adds Google reCAPTCHA v3 to donation pages. We decided to go with the "[Programmatically invoke the challenge](https://developers.google.com/recaptcha/docs/v3#programmatically_invoke_the_challenge)" method of implementation, as our for isn't quite as simple as "submit". The resultant token is added to the data sent to our API for payment completion. It's serialized in to a subsequent request to BadActor under the key `captcha_token`.
1. First, notice the presence of the reCaptcha floaty icon thing on donation pages. 
2. Next, make a donation. 
3. Then maybe inspect the request payload in the browser developer console and find the key `captcha_token`. You can filter network requests by `payment/` to get the one you want here.
4. If you're quick about it, …

[NRH-292] DonationPage reCAPTCHA

---

spa/src/components/pageEditor/editInterface/pageElements/addElementModal/AddElementModal.js
spa/src/components/pageEditor/elementEditors/richText/RichTextEditor.styled.js

The Page element RichText editor interface was a bit confusing because the text area you type in didn't have an outline. It's invisible if you don't have text in it already. So we've added a border.
Also, added incidentally-- adding new elements to the page adds them to the bottom of the list/page, rather than the top.
Check out a rich text editor and notice the border.
No

[NRH-314] Richtext outline

---

.github/workflows/cypress.yml
.github/workflows/tests.yml
README.md

Adds an action workflow for cypress that is skipped if a branch has `skipcy` in its name.
No need look at this branch. When this branch is merged to develop it should run cypress tests.
No

Nrh 346  skip cypress tests skipcy

---

spa/src/components/donationPage/pageContent/DBenefits.js

adds "per year" to benefit range
confirm "per year" appears in the benefit column where benefit ranges are displayed
i don't think so

adds "per year" to benefit range

---

apps/contributions/payment_managers.py
apps/contributions/tasks.py

Quiets warning email messages, by moving from `warning` to `info` at the level of capture. 
This seems reasonable because decisions on whether to email an admin with a logger.warning can be made higher up the call stack, and the logger at the call level reports the exact Stripe warning to the logs, which can be inspected if there is a specific problem that needs to be addressed with the individual contribution.
Note: I also edited down the previous logger output mainly to save bytes given the limited logging allocation NRH has, and most of what was in there was already captured by Stripe's error message.
Either wait for the task to run and observe that the email's have quieted down, or manually run the task from the django admin.
No.

refs #NRH-345 quiets conribution warnings. Simplifies error message.

---

apps/organizations/serializers.py
apps/pages/tests/test_serializers.py

Gets analytics ids back into donation page serializer
Org analytics will work in client after this. No need to separately test.

HOTFIX: include analytics ids in serializer

---

spa/src/components/donationPage/live/LivePage404.styled.js

Adds padding to 404 text for small screens
Go to a nonexistent url and shrink the viewport. The text should have a bit of padding around it to prevent collision with the edge of the screen.
No

[NRH-348] add padding to 404 text

---

revengine/settings/base.py

Removes celery check from healthcheck. There was a misconfiguration of the celery healthcheck. Since that particular check wasn't requested, we won't waste time fixing it. For now, remove the check. We're keeping references to the errors received for future reference.
Visit healthcheck endpoint, note no errors.
No

[NRH-352] removes celery healthcheck

---

apps/common/utils.py
apps/organizations/admin.py
apps/organizations/tests/test_org_views.py
apps/pages/admin.py
apps/pages/models.py
apps/pages/serializers.py
apps/pages/tests/test_admin.py
apps/pages/tests/test_models.py
apps/pages/tests/test_serializers.py
apps/pages/tests/test_viewsets.py
apps/pages/views.py
spa/cypress/fixtures/pages/templates.json
spa/cypress/integration/donation-page-edit.spec.js
spa/cypress/integration/donation-page-list.spec.js
spa/src/ajax/endpoints.js
spa/src/components/content/pages/AddPageModal.js
spa/src/components/content/pages/AddPageModal.styled.js
spa/src/components/pageEditor/CreateTemplateModal.js
spa/src/components/pageEditor/CreateTemplateModal.styled.js
spa/src/components/pageEditor/PageEditor.js
spa/src/components/pageEditor/editInterface/pageElements/ElementProperties.js
spa/src/components/pageEditor/editInterface/pageSetup/PageSetup.js
spa/src/components/pageEditor/editInterface/pageStyles/PageStyles.js
spa/src/components/stylesEditor/StylesEditor.js
spa/src/elements/buttons/CircleButton.js
spa/src/elements/inputs/Select.js
spa/src/elements/inputs/Select.styled.js

Implements template creation and template use from the Org Admin.
From the page edit view, notice a new button that you can use to create a template from the existing page. Try it out.
Then, from the page-create modal, notice a new optional dropdown for selecting a template from which to make your new page. Try that out too!
No

[NRH-361] OrgAdmin page templates

---

README.md
spa/cypress/fixtures/pages/live-page-element-validation.json
spa/cypress/integration/donation-page-edit.spec.js
spa/src/components/donationPage/pageContent/DPayment.js
spa/src/components/pageEditor/PageEditor.js
spa/src/components/pageEditor/validatePage.js

Modifies the page validation system to support the detection of element level mis-configurations, whereas before it simply detected the absence of a required element.
At the moment this validation is simple. First, elements that need to be validated on page save need to have two properties added to the Element definition:
- `requireContent`
- `contentMissingMsg`
If `requireContent` is true the validator will check to see if the content of the element exists. If it does not, then the element will fail validation and the `contentMissingMsg` will display in the error notification.
Currently this is only implemented on `DPayment` elements
1. Create a new page.
2. Add any element to a page
3. Add a Payment element to the page, but do not edit it. This will leave it with no payment methods …

Nrh 347  validate dpayment

---

spa/src/components/paymentProviders/stripe/StripePaymentForm.js

Thank you page urls were malformed after subdomain work.
Make a donation page. Should successfully go to thank you page
No

[NRH-410] ThankYou page redirect failure

---

spa/src/elements/inputs/Select.js

Hopefully disables the caret and keyboard for the select widget on Android devices.
Find a select widget (dropdown/picklist) on an Android phone.
No

[NRH-4865] No android-keyboard on select widget

---

spa/src/hooks/useErrorFocus.js

Autofocus on mailing_street field was broken by the addition of a hidden field with the same `name` property. If this was the first errored field on the page, it would break autoscrolling altogether. This PR accounts for the possibility of a nodelist instead of a single element.
View a page in which the Donor Address block appears _above the Donor Info block_. Make a donation without filling in any information. This should now autoscroll and autofocus to the mailing_street field.
No

[NRH-4998] Broken address autofocus

---

poetry.lock
pyproject.toml
revengine/settings/base.py
revengine/views.py
spa/public/index.html

Adds a library, `django-csp`, to easily handle content security policy directives. 
The policy is something like this:
```
Content-Security-Policy-Report-Only: 
default-src 'self'; 
img-src *; 
script-src https://js.stripe.com https://risk.clearbit.com https://www.google-analytics.com https://maps.googleapis.com https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://pay.google.com;
frame-src https://js.stripe.com https://hooks.stripe.com https://www.google.com/recaptcha/ https://recaptcha.google.com/recaptcha/ https://pay.google.com; 
report-uri https://o320544.ingest.sentry.io/api/6046263/security/?sentry_key=<sentry_key>&sentry_environment=<environment>
```
View the request headers for the page request.
No. Though there is an environment variable, …

[NRH-5057] CSP Report Only

---

apps/contributions/tests/test_views.py
apps/contributions/views.py
apps/organizations/models.py

We decided to simply disable the automatic ApplePayDomain creation for MVP. We need to register domains with Apple per revenue-program that wants to use Apple Pay. This will be a separate feature.
Not really a way to do this.
No

[NRH-5038] Disable ApplePayDomain.create for MVP

---

apps/organizations/tests/test_org_views.py
apps/organizations/views.py
spa/cypress/fixtures/org/revenue-programs-1.json
spa/cypress/integration/03 - donation-page-list.spec.js
spa/src/components/content/pages/AddPageModal.js

The bug "cannot see more than 10 revenue programs" is fixed here. It was default pagination.
View more than 10 of em.
No

[NRH-5017] Fix RP Pagination

---

spa/src/components/donationPage/DonationPageNavbar.styled.js

Fixes a bug in which the header-logo can potentially but cut off on the x-axis on smaller devices.
Test [this page](https://vosd.revengine-test.org/voice-of-san-diego-donation-page) at smaller viewport widths (assuming nobody has changed the header image)
No

[NRH-5051] DonationPage header-logo cutoff

---

apps/contributions/bad_actor.py
apps/contributions/payment_managers.py
apps/contributions/serializers.py
apps/contributions/tests/test_payment_managers.py

Pulls BadActor validation out of the `AbstractPaymentSerializer` into its own `BadActorSerializer`. This original bug was caused by removing some values from the `AbstractPaymentSerializer` and moving them to the `ContributionMetadataSerializer`. A good move, semantically, but had the unintended side-effect of removing values that were required for BadActor. So declaring an independent serializer for BadActor makes sense here. It's worth noting that failed validation for this serializer should not prevent the payment from going through. Instead, failed validation sends a sentry warning.
Verify that all required information is passed through to BadActor, or if not, we get a sentry warning.
No

[NRH-5541] Missing BadActor Fields

---

spa/src/components/donationPage/pageContent/DSwag.js

Minor adjustment to help text for t-shirt dropdown
View a donation page and verify the text says "Your contribution comes with member merchandise. Please choose an option" and not "Your contribution comes with…"
n/a

adjust t-shirt dropdown help text

---

apps/common/serializers.py

Fixes a bug in which the default hub social share image wasn't being used if the page was accessed via a page-url. 
The method building the fully qualified absolute url for the default image was itself using the absolute url of the incoming request, which obviously wouldn't work if there was additional path information in the url.
Visit a donation page via page slug and check the head of og:image, verify that the url there takes you to an actual image. You can also use the facebook share debugger to verify that facebook gets the correct image.
No

[NRH-5020] Fix default social image for pages with page slugs

---

spa/src/components/paymentProviders/stripe/StripePaymentForm.js

Makes the payment request label the rp name, not the generic "revengine donation"
Start an apple or google pay payment
No

[#9726] Apple/Google Pay Label is RevProgram

---

spa/src/components/donationPage/live/thankYou/GenericThankYou.js

rewords "take me back to the news" on thank you page
try processing a test donation and verify "return" button says "return to website" instead of "take me back to the news"
n/a

new copy for button CTA on thank you page

---

README.md
apps/organizations/tests/test_admin.py
revengine/settings/base.py
revengine/urls.py

Changes /admin to /nrhadmin.
Removes need for trailing slash on admin route as well
Visit /nrhadmin and observe that the admin is displayed. Visit /admin and observe that nothing happens.
No

#9701 Move /admin to r"nrhadmin/?"

---

revengine/settings/base.py
revengine/settings/deploy.py
spa/src/App.js
spa/src/hooks/useSentry.js
spa/src/index.js
spa/src/settings.js

Ensures that all uses of the Sentry DSN reference the SENTRY_DSN env var. Also makes the CSP_REPORT_URI a config var so that it's flexible like the SENTRY_DSN now is.
Set the env vars on staging to the desired DSN and-- maybe trigger some error? Not sure about that one.
Add the desired DSN to Heroku config vars as SENTRY_DSN to each environment. Also make sure to set the CSP_REPORT_URI env var in each env.

#10666 Configure Sentry via Env

---

spa/src/components/DashboardRouter.js
spa/src/components/DonationPageRouter.js
spa/src/components/errors/ChunkErrorBoundary.js
spa/src/components/errors/ErrorFallback.styled.js
spa/src/utilities/componentLoader.js

Creates a custom component loader to handle chunk loading errors from code splitting as well as an error boundary that shows the error and reloads the page.
You can try to test locally, I can provide the settings for throttling, though I was never able to trigger it.  My guess is that it must be tested in a deployed environment.

Create componentLoader util and ChunkErrorBoundary component + styles

---

spa/src/components/donationPage/DonationPage.js
spa/src/components/donationPage/DonationPageDisclaimer.js
spa/src/components/donationPage/DonationPageDisclaimer.styled.js
spa/src/components/donationPage/DonationPageDisclaimer.test.js
spa/src/components/paymentProviders/stripe/StripePaymentForm.js
spa/src/components/paymentProviders/stripe/StripePaymentForm.styled.js

The initial implementation of the static disclaimer text placed it at the bottom of the page no matter where the credit card form was. That didn't make sense, so we've tied the disclaimer text to the submit button (or payment request button)
Move around your Payment element and notice that the disclaimer text moves with it.
No

[#11590] Move dislcaimer text to payent widget

---

spa/src/components/donationPage/DonationPageNavbar.js
spa/src/components/donationPage/DonationPageNavbar.styled.js

Restores the option to use a header background image. If not present, defaults to stylesheet provided color

Fix header fallback

---

revengine/settings/deploy.py

Adds the logging integration for Sentry. So that `logger.warning` will show up in Sentry.
Configure Sentry; generate a log warning; confirm it shows up in Sentry.
No.

Sentry logging

---

apps/pages/models.py

Ensures that a page has a revenue program before attempting to access properties of that revenue program.
With a current staging database, visit http://localhost:8000/nrhadmin/pages/donationpage/ 
it should not 500

sc-11850 Fixes empty revenue program accessor.

---

spa/src/components/paymentProviders/stripe/StripePaymentForm.styled.js

Ticket Ref: https://app.shortcut.com/caktusgroup/story/12233/update-text-for-i-prefer-to-manually-enter-my-credit-card-to-use-system-fonts
Sets system font in styling for the PayWithCardOptions text, "I prefer to manually enter my credit card".
Go to a donation page with a custom font applied in the styles.  Check to make sure that text is displayed using the system font.

12233 - specifies system font for PayWithCardOption

---

.github/workflows/test-js.yml
spa/cypress/integration/08 - contributor.spec.js
spa/cypress/support/commands.js
spa/src/components/contributor/contributorDashboard/EditRecurringPaymentModal.js

What's this PR do?
Will not allow user to submit payment update if there are any errors or partially filled payment details.
Why are we doing this? How does it help us?
Fixing this but improves user experience.
How should this be manually tested?
Goto -> `/contributor/contributions/`-> click on payment method (card number) -> provide the card details.
`Update payment method` should not be enabled if the payment details are not completely provided.
Have automated unit tests been added?
Yes
How should this change be communicated to end users?
N/A
Are there any smells or added technical debt to note?
No
Has this been documented? If so, where?
N/A
What are the relevant tickets?
(Note: Please use syntax [JIRA-123] to link any relevant tickets)
[DEV-870]
Do any changes need to be made before …

DEV 870 - Interstitial form validation failure when changing credit card payment method from contributor portal

---

spa/src/components/contributor/ContributorEntry.js

Passes the subdomain for "DEV-1494 RP subdomain magic link email" from contributor-entry form
https://github.com/newsrevenuehub/rev-engine/pull/376
To send proper emails to RP contributor portal users
This will work after DEV-1494  is merged. And when user requests contributor portal access from rp subdomain
e.g.
https://rp1.revengine.com/contributor, the email link will take user to https://rp1.revengine.com/contributor-verify?....
And normal ways should also work 
https://support.revengine.com/contributor takes to https://support.revengine.com/contributor-verify?....
(its more of testing of DEV-1494 than this one )
n/a
n/a
n/a
n/a
[dev-1692]
n/a

dev-1692 send_subdomain_in_contributor_link_request

---

apps/emails/models.py
apps/emails/tasks.py
apps/pages/models.py
apps/slack/slack_manager.py
email_templates/nrh-default-otd.html
email_templates/nrh-manage-donations-magic-link.html
email_templates/nrh-v2-default-one-time-donation.html
revengine/settings/base.py

Rename magic link email template
Also, Rename dashboard url overlooked in DEV-1512
Also started fuller rename (cause I can't stand smelly inconsistent code) but stopped when I learned there were other tickets to correct this.
Rename donation_amount, donation_date in email templates
Rename value of GENERIC_STRIPE_PRODUCT_NAME
New / consistent terminology
1. Trigger delievery of receipt email, verify it don't say "donation" no where
2. Trigger delivery of magic link contributions portal, verify it don't say "donation" no where
no?
N/A
Nothing added
No
[DEV-1728]
No
Yes, febreeze all the smelly code using "donor" [DEV-1446]
[DEV-1728]: https://news-revenue-hub.atlassian.net/browse/DEV-1728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

DEV-1728 replace Donation with Contribution

---

spa/cypress/.eslintrc
spa/cypress/fixtures/user/hub-admin.json
spa/cypress/fixtures/user/org-admin.json
spa/cypress/fixtures/user/rp-admin.json
spa/cypress/fixtures/user/stripe-connected.json
spa/cypress/fixtures/user/stripe-verified.json
spa/cypress/integration/04 - donations.spec.js
spa/cypress/integration/06 - donation-detail.spec.js
spa/cypress/integration/11 - dashboard.spec.js
spa/src/components/dashboard/Dashboard.js
spa/src/components/dashboard/sidebar/DashboardSidebar.js
spa/src/constants/featureFlagConstants.js
spa/src/hooks/useFeatureFlags.js
spa/src/hooks/useRequest.js
spa/src/utilities/flagIsActiveForUser.js

This PR is step 2 of 2 in a sequence of PRs meant to together ship DEV-1684. The feature branch branches from the branch for the step 1 PR, which also serves as base (for rationale and additional details on the plan, [see the notes in this PR](https://github.com/newsrevenuehub/rev-engine/pull/427)).
Narrowly, it supports hiding/showing contributions section (and related sidebar entry) based on a user's flags. More broadly, it creates a generalized approach that we'll use for future  SPA-side feature flagging.
- Adds a new `useFeatureFlags` and a related utility function called `flagIsActiveForUser` that together can be used to determine if a flag with a given name is active for a user, which in turn can be used to conditionally …

DEV-1684 - protect contributions section behind a feature flag  Part 2 (SPA changes)

---

apps/api/permissions.py
apps/common/constants.py
apps/common/tests/test_resources.py
apps/contributions/tests/test_views.py
apps/flags/apps.py
apps/flags/constants.py
apps/users/serializers.py
apps/users/tests/test_serializers.py
revengine/settings/base.py
spa/cypress/.eslintrc
spa/cypress/fixtures/user/hub-admin.json
spa/cypress/fixtures/user/org-admin.json
spa/cypress/fixtures/user/rp-admin.json
spa/cypress/fixtures/user/stripe-connected.json
spa/cypress/fixtures/user/stripe-verified.json
spa/cypress/integration/04 - donations.spec.js
spa/cypress/integration/06 - donation-detail.spec.js
spa/cypress/integration/11 - dashboard.spec.js
spa/src/components/dashboard/Dashboard.js
spa/src/components/dashboard/sidebar/DashboardSidebar.js
spa/src/constants/featureFlagConstants.js
spa/src/hooks/useFeatureFlags.js
spa/src/hooks/useRequest.js
spa/src/utilities/flagIsActiveForUser.js

In working on [DEV-1684], I've decided to break up the work into two separate PRs, an initial one (this one) that is limited to the backend changes required to add active flags to a `.flags` property on serialized users.  In a separate PR, I'll tackle the SPA changes that rely on this data.  This will allow a smaller diff initially that I can pass to Norm for backend review, and then for part 2, can have a dev with React expertise review.
NB: The base for this PR is [DEV-1021] since this branches from that branch, which itself is in an unmerged PR. Once that has been merged, I will change the base for this PR to main. Until then, this approach will allow a review that focuses on narrow changes of this PR, rather than broader set of …

DEV-1684 - protect contributions section behind a feature flag Part 1 (API changes)

---

apps/pages/filters.py
apps/pages/views.py
spa/cypress/fixtures/styles/list-styles-1.json
spa/src/components/content/Content.js
spa/src/components/pageEditor/PageEditor.js
spa/src/components/stylesEditor/StylesEditor.js

This PR filters styles available in the dropdown in the page editor. It does this by including a query parameter for the current RP when making a request to retrieve styles from the server.
This required adding a filter to the styles API resource so that can be filtered by revenue program ID.
Makes the page editor easier to use for  users who have access to many styles.
Log in to the SPA as, say, an RP admin user for an org that has many styles. Either create or edit an existing page, and in the page editor, go to the styles tab. The dropdown should only include styles for the RP of the page.
No.
[DEV-956]
No
No

DEV-956: Restrict style dropdown in page editor based on active parent element

---

spa/cypress/integration/04 - donations.spec.js
spa/src/components/donations/filters/CreatedFilter.js
spa/src/components/donations/filters/Filters.js
spa/src/utilities/formatDatetimeForAPI.js

Completed
This PR does the following
1. for invalid strings, helper function returns a null date
2. while user is  manually entering a date, ajax call to fetch contributions will not be made
3. A toggle switch is inserted to disable "date filters" as backend changes are being made to handle contributions reporting
Better user experience
Go to dashboard contributions and date filters should not show up 
N/A
N/A
No
No
DEV-1595
No

DEV-1595 fixes manual input broken for datepicker

---

revengine/views.py

Base is provisionally `DEV-1856` because it makes a bunch of changes to logs, and this PR presupposes one of those changes.
Changes a log level from warning to info.
N/A
N/A
N/A
N/A
N/A
[DEV-1952 | ReactAppView failed to retrieve RevenueProgram by subdomain "support"](https://news-revenue-hub.atlassian.net/jira/software/c/projects/DEV/boards/3?modal=detail&selectedIssue=DEV-1952)
No
N/A

DEV-1952 | React app view failed to retrieve RP by subdomain support

---

README.md
apps/api/urls.py
apps/contributions/views.py
poetry.lock
pyproject.toml
revengine/settings/base.py

Installs Swagger and ReDoc as options to have a browsable view of the API
- It will allow users of the DRF API to have an easier time browsing/exploring the API
- I'm hopeful it will help us self-document the API better
1. `export ENABLE_API_BROWSER=True`
2. Visit /api/redoc/ and /api/swagger/ for two different interfaces to the API
No.
No, it was mostly settings and boilerplate copied from the instructions for drf-yasg. 
No.
No. I did make decision here about trying to move toward a flat settings file instead of multiple files. For now there's a mix. 
I also tried out a similar package called drf-spectacular. I pushed that up as a separate branch if you'd like to take a look at that one. I also opted to make this only available locally for now, partly because I had to disable CSP on the …

install and enable drf-yasg for browsable api

---

spa/cypress/integration/03 - donation-page-list.spec.js
spa/src/components/content/pages/AddPageModal.js

n/a
Removes the template drop-down menu when adding a new page, even if templates exist. (The dropdown is already hidden if there are no templates available.)
We're rethinking this functionality.
This is a little tricky as it needs to be done on a deploy that has pre-existing templates, and a page created from a template.
Two test plans:
1. Log into the dashboard and go to `/pages`.
2. Choose to add a new donation page.
3. Confirm that there is no template dropdown menu.
1. View a page that was previously created from a template. Make sure it displays and functions correctly.
2. Edit the page that was previously created from a template and confirm editing works as usual.
It doesn't look like we mention templates in our knowledge …

DEV-1493: Hide template functionality in add page modal

---

apps/organizations/models.py
apps/organizations/tests/test_org_views.py
apps/organizations/urls.py
apps/organizations/views.py
apps/users/models.py

This one of 3 planned stacked PRs to deliver [DEV-1106](https://news-revenue-hub.atlassian.net/jira/software/c/projects/DEV/boards/3?modal=detail&selectedIssue=DEV-1106).
The base for this PR is `DEV-1106-main`, which was initially the result of merging (a then not yet merged) `dev-2199n-connect-to-stripe-new` into (a then not yet merged) `dev-1679-create-account`, and then merging `main`.
This PR contains the server-side changes required to facilitate the new Stripe Account link flow.
The next PR will be SPA-focused, hooking up existing UI components to the endpoints created in this PR. This PR will also be into `DEV-1106-main`.
Finally, there will be a third PR of `DEV-1106-main` into `main`, where final merge conflicts can be …

DEV-1106: Server Side Changes 

---

apps/contributions/serializers.py
apps/contributions/tests/test_serializers.py

Fixes bug ticket [DEV-2421](https://news-revenue-hub.atlassian.net/browse/DEV-2421)
Specifically, fixes a regression caused by refactoring of conditionally required form elements. The pre-existing code had a default empty list when there were no `.requiredFields` for a given dynamic page element ([see here](https://github.com/newsrevenuehub/rev-engine/blob/6ab98b4e56d65be709d42ca13f85024cfaaf5ca9/apps/contributions/serializers.py#L186)). This PR brings back a default empty list for `.requiredFields`.
Fixes bug ticket [DEV-2421](https://news-revenue-hub.atlassian.net/browse/DEV-2421)
~Go to https://billypenn-dev-2421.revengine-review.org/donate. It should succeed, and shouldn't generate Sentry errors. You can also take a look at …

handle page elements that don't have requiredFields

---

spa/cypress/integration/01 - donation-page.spec.js
spa/cypress/support/commands.js
spa/cypress/support/util.js
spa/src/components/paymentProviders/stripe/StripePaymentForm.js
spa/src/components/paymentProviders/stripe/stripeFns.js
spa/src/components/paymentProviders/stripe/stripeFns.test.js

Merge this into DEV-2183-root-branch, then deploy that to test. Once passes UAT, PR DEV-2183-root-branch into main.
This solves a bug identified in [DEV-2435](https://news-revenue-hub.atlassian.net/browse/DEV-2435).
The root cause of the bug had to do with how a convenience function called `getPaymentSuccessUrl` was dealing with being passed the value `'\'` for its `pathname` parameter. That parameter ultimately determines redirection behavior of the PaymentSuccess component ([see here](https://github.com/newsrevenuehub/rev-engine/blob/DEV-2183-root-branch/spa/src/components/donationPage/live/PaymentSuccess.js#L106-L117)). 
The bug narrowly could be caused by default donation pages (note that billypenn.revengine-test.org/donate …

DEV-2435 | fix bug around next url for default donation page

---

apps/contributions/models.py
apps/contributions/tests/test_models.py
apps/contributions/tests/test_serializers.py
apps/contributions/tests/test_views.py
apps/contributions/tests/test_webhooks.py
apps/contributions/views.py
apps/contributions/webhooks.py

This fixes a bug discovered in UAT for DEV-2183. It should be merged into DEV-2183-root-branch, and that branch will eventually be merged into main.
This PR fixes a bug that was causing Stripe webhooks to fail for recurring contributions ("Subscriptions" in Stripe lingo).
The root cause of the bug was that we were not saving the Stripe Customer ID back on to the NRE contribution after creating a Stripe PaymentIntent or Subscription. In our webhooks code, for subscriptions, we were attempting to retrieve by customer ID instead of subscription ID.
To solve for this, this PR changes the contribution retrieval behavior of our webhook so that it searches contributions by Stripe subscription ID for subscriptions. It also updates the …

DEV-2408: Stripe webhooks fail for subscriptions

---

spa/src/components/account/Profile/InfoTooltip.js
spa/src/components/account/Profile/InfoTooltip.styled.js
spa/src/components/account/Profile/InfoTooltip.test.js
spa/src/components/account/Profile/Profile.js
spa/src/components/account/Profile/ProfileForm.js
spa/src/components/account/Profile/ProfileForm.styled.js
spa/src/components/base/Button/Button.js
spa/src/components/base/Button/Button.stories.js
spa/src/components/base/Button/Button.test.js
spa/src/components/base/TextField/TextField.js
spa/src/components/base/TextField/TextField.stories.js
spa/src/components/base/TextField/TextField.test.js
spa/src/components/base/Tooltip/Tooltip.js
spa/src/components/base/Tooltip/Tooltip.stories.js
spa/src/components/base/Tooltip/Tooltip.test.js
spa/src/components/base/index.js

n/a
This is stacked on DEV-2028 for clarity.
The headline feature here is that this adds an icon beside the Company Tax Status field that can be clicked to show more information. It also contains improvements to the form layout and controls so that they are closer to Figma.
Under the covers, I also added a new directory, `components/base`. These contain some basic building-block components that I use in this PR but I am hoping we can gradually adopt across the app. They have Storybook demos (`npm run storybook`) and should match Figma, and are definitely a first pass/not comprehensive for all possible uses.
The tooltip is there to better inform users as to what implications choosing a tax status will have.
The new components have …

DEV-2387: Add info tooltip to Tax Status field, refactor components

---

spa/src/components/account/SignUp/SignUp.js

Removes the disclaimer about agreeing to the code of ethics on the signup screen.
Since we don't have it written yet and there's no link to it we shouldn't have the statement there yet.
Visit the signup screen to confirm there's no mention of the code of ethics: https://dev-2510.revengine-review.org/sign-in 
Maybe if there are screenshots that won't be current.
Not sure if it's necessary for a one-line change, but if it is since this is FE I'd need help.
N/A
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-2510
No.
No.

remove code of ethics disclaimer since it isn't written yet and there's no link to it

---

apps/users/tests/test_views.py
apps/users/views.py

Fixes acute bug described in ticket whereby org users were getting an error message after returning from stripe account connect flow. 
The underlying cause was that while we were creating an org, an rp, and a role assignment, we were not creating a payment provider.
We now create a payment provider and attach it to the RP at account customization time.
There is also a test that asserts this is so.
Fixes a blocking bug for self service onboarding
Do the Stripe onboarding flow. After creating steps on Stripe, when you get back to the site, you shouldn't see an error, and apps should work as expected.
No
Yes
N/A
No
No
[DEV-2524](https://news-revenue-hub.atlassian.net/jira/software/c/projects/DEV/boards/3?modal=detail&selectedIssue=DEV- …

DEV-2524 | Create payment provider as part of account customization step

---

spa/package.json
spa/src/components/donationPage/DonationPage.js
spa/src/components/donationPage/amountUtils.js
spa/src/components/donationPage/amountUtils.test.js
spa/src/components/donationPage/pageContent/DAmount.js
spa/src/components/donationPage/pageContent/DFrequency.js

n/a
This fixes a bug with how fee calculation works on a contribution page at pageload. This bug only affects older contribution pages that have contribution amounts stored as strings.
I refactored out two contribution amount-related utility functions into a separate module to help with testability. I tried leaving them in the `<DAmount>` component but Jest does not like importing a module named `constants` because our own module conflicts with one in node_modules, and this also helps start to detangle some circular dependencies we have in our code (I think).
I also fixed the `npm run test:coverage` command so it outputs accurate info.
Fixes a bug with older donation pages.
Repeat the steps below with the following contribution …

DEV-2530: Fix bug with fees at page load

---

spa/cypress/e2e/03-donationPageList.cy.js
spa/src/components/common/Button/GrabLink/GrabLink.js
spa/src/components/common/Button/PublishButton/PublishButton.js
spa/src/components/content/pages/AddPageModal.js

n/a
Fixes bug in which Org Admin user doesn't redirected to new page on page creation
Fixes the Create new page flow
- Create a new account
- Verify email and fill in profile inputs
- Create new page
- Make sure the flow works as expected (page gets created and user is redirected to edit page)
- User cannot create a second page and error pops up for the user to know what happened
No
No, the create page modal/flow will be updated in the next ticket (DEV-2299 Update and Enhance "New page" modal)
n/a
Create Page modal/flow isn't really well written. Will be addressed in DEV-2299
no
https://news-revenue-hub.atlassian.net/browse/DEV-2595
no
https://news-revenue-hub.atlassian.net/browse/DEV-2299

DEV-2595: Fix redirect link and update error handling

---

.github/workflows/test-js.yml
spa/src/components/account/Profile/Profile.js
spa/src/components/account/Profile/Profile.test.js
spa/src/components/base/OffscreenText/OffscreenText.js
spa/src/components/base/OffscreenText/OffscreenText.stories.js
spa/src/components/base/OffscreenText/OffscreenText.test.js
spa/src/components/base/Stepper/StepperDots.js
spa/src/components/base/Stepper/StepperDots.stories.js
spa/src/components/base/Stepper/StepperDots.test.js
spa/src/components/base/Stepper/index.js
spa/src/components/base/index.js
spa/src/components/dashboard/connectStripe/ConnectStripeElements.js
spa/src/components/dashboard/connectStripe/ConnectStripeElements.styled.js
spa/src/components/dashboard/connectStripe/ConnectStripeElements.test.js

n/a
- Adds a `<StepperDots>` component that is noninteractive and shows progress through a process.
- Adds a `<OffscreenText>` component for wrapping text that should be perceivable through assistive technology only.
- Puts progress indicators on the profile finalization and Stripe setup modals.
The progress indicators were part of the original design for these modals, and give users a sense of where they are in the setup process.
1. Create a new account and verify its email.
2. Confirm that the design of the profile finalization modal that appears once you've confirmed your email matches Figma.
3. (if you have a Mac or have other assistive technology available) Turn on VoiceOver/AX tech and confirm that the modal reads "Step 1 of …

DEV-2390: Add progress indicator to setup modals

---

spa/src/components/donationPage/pageContent/DAmount.js
spa/src/components/donationPage/pageContent/DAmount.test.js
spa/src/components/pageEditor/elementEditors/amount/AmountEditor.js
spa/src/components/pageEditor/elementEditors/swag/SwagEditor.js
spa/src/utilities/validateInputPositiveFloat.js
spa/src/utilities/validateInputPositiveFloat.test.js

n/a
Fixes a bug with deleting out a number from the other donation amount field.
I refactored the validation function `validateInputPositiveFloat` and changed it to reject empty strings. This is a change from previous behavior, but I think this makes the function usage clearer--I would not have expected it to accept `''` as a positive float. This had small knock-on effects in other places it's used.
Improves UX of the donation form.
To test the proximate bug:
1. Go to a donation page.
2. Click the Other donation amount and enter a number.
3. Hit the delete key and clear the field.
4. Confirm you're able to completely empty the field.
5. Enter a number again and confirm that the Stripe fees amount and total amount on the submit …

DEV-2588: Fix bug with deleting other amount completely

---

Dockerfile
spa/jsconfig.json
spa/package-lock.json
spa/package.json
spa/src/components/DonationPageRouter.test.tsx
spa/src/components/DonationPageRouter.tsx
spa/src/test-utils.tsx
spa/tsconfig.json

n/a
This fixes a bug where requests to `/:donationSlug/thank-you/` were not getting routed properly.
This also adds TypeScript support to the project 🌈 and adds unit tests for the donation page router.
Fixes a very confusing situation for contributors where donating from a page with a slug didn't show a confirmation page.
Repeat the steps below for both a page with a donation slug (like `/donate/`) and one using the default donation page (at the top-level domain, no subdirectories).
1. Go to the donation page.
2. Complete a test donation.
3. Confirm that after doing so, you see a thank you page. When you start at `/donate/`, the browser address bar should be `/donate/thank-you/`. When starting at the top-level domain, the browser …

DEV-2596: Restore /:pageSlug/thank-you/ route

---

spa/cypress/e2e/09-styles.cy.js
spa/src/components/content/Customize.js
spa/src/components/content/styles/Styles.js
spa/src/components/content/styles/Styles.test.js
spa/src/hooks/useStyleList.test.tsx
spa/src/hooks/useStyleList.ts

Fixes a bug revealed in QA of DEV-1865.  Base for this PR is DEV-1863-restrict-page-creation-via-org-plan, which itself is queued up to be merged into main.
Ensures that new styles appear in Customize page list view after creation
- Adds a new hook `useStyleList` that follows pattern from `usePageList` and uses that hook in place of pre-existing AJAX functionality to retrieve styles
- After a style is created, invalidates the styles list query, causing them to be re-retrieved.
Fixes bug and allows us to release DEV-1863 and DEV-1865
Create a style in review app and you should immediately see it reflected in the customize list view without refreshing.
No
yes
N/A
N/A
N/A
https://news-revenue-hub.atlassian.net/browse/DEV-2650
No
As …

DEV 2650 | style not appearing after clicking new style button reload

---

apps/contributions/serializers.py
apps/contributions/tests/test_serializers.py
apps/contributions/tests/test_views.py

Fixes a bug where the total amount (that is, donor selected amount + fee amount in case of agreeing to pay fees) was being recorded as value for `donor_selected_amount` whereas it should be the selected amount without fee tacked on.
Fixes Salesforce reporting
Make a contribution and agree to pay fees.
In Django admin, you should see that the contribution amount includes pay fees.
Look at the payment intent or subscription in Stripe. Its metadata should have a `donor_selected_amount` value, which should be the amount without fee included.
No
Yes. Existing ones have been updated to ensure this field has correct value.
N/A
No
N/A
https://news-revenue-hub.atlassian.net/browse/DEV-2699
No
N/A

DEV-2699 | fix donor_selected_amount in Stripe metadata

---

spa/cypress/e2e/02-donationPageEdit.cy.js
spa/cypress/fixtures/pages/live-page-element-validation.json
spa/src/components/pageEditor/PageEditor.js

n/a
Puts the page editor into the edit state after loading the page. It can't be in edit mode absolutely immediately because the page is loading initially.
Improves UX.
1. Edit an existing page from the admin dashboard. Confirm the page starts in edit mode.
2. Create a new page from the admin dashboard. Confirm the page starts in edit mode.
3. Confirm that toggling between edit mode and preview works.
4. Confirm that toggling between preview mode and edit works.
We might need to change docs around page editing to reflect that users don't need to go into edit mode.
Yes.
n/a?
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-2764
No.
No.

DEV-2764: put page in editable state after loading

---

apps/pages/tests/test_viewsets.py
apps/pages/views.py

This PR fixes a bug that was causing the API to respond with a 500 when the SPA attempted to patch a donation page, sending an empty list as the value for `sidebar_elements`.
The cause of the bug was this line of code in `apps.pages.views.PageViewSet.partial_udpate`:
```
if request.FILES and request.data.get("sidebar_elements", None):
```
That conditional block was being triggered even when an empty list was being sent whereas the intention was for an empty list to not meet the condition. This is because instead of looking at the serialized value for `sidebar_elements` as created in the immediately preceding line of code, the raw request data was being looked at, in which case the empty list was "stringified" as `'[]'`, which is …

DEV-2487 | Fix integrity error on donation page patch

---

apps/pages/tests/test_viewsets.py
apps/pages/views.py

This fixes a bug that caused an integrity error when a user edited page elements on an existing page that already had an Image element in sidebar elements.
There is a [long explanatory comment in the code](https://github.com/newsrevenuehub/rev-engine/pull/829/files#diff-44087ac156d7cc64c8aaf6cf545f87cf3de6289c2cafdb02f7047ed160da226bR176-R197) that provides context for the cause of the bug.
In addition to fixing the bug, this PR adds a test for the specific edge case that caused the bug. If you keep that test in place but revert the change to the view code, you will get a test failure with the integrity error we saw "in the wild".
Makes page editor functional.
1. Edit a page, adding an image to sidebar elements and save.
2. Edit …

DEV-2861 | Fix integrity error bug for sidebar elements

---

apps/contributions/filters.py
apps/contributions/serializers.py
apps/contributions/tests/test_serializers.py

This small PR makes backend changes to support required front end changes in parent ticket ([DEV-1332 | Add Revenue Program to the contributions table display](https://news-revenue-hub.atlassian.net/browse/DEV-1332)).
UAT will happen in DEV-1332, and the base for this ticket is DEV-1332, which will later be merged into main. 
Adds revenue program as a property to `ContributionSerializer`, using inlined `RevenueProgramSerializer`, which exposes id, name, and slug . Via parent ticket (DEV-1332) the contributions table in SPA is meant to display RP name for each row, in certain situations, so this representation of the RP will provide everything needed.
Also makes contributions sortable by revenue program name.
Make it easier for …

DEV-2633 | Add revenue program to contribution serializer

---

spa/src/components/dashboard/Dashboard.js
spa/src/components/dashboard/Dashboard.test.tsx

This PR makes a minor change such that `Dashboard`'s displays the `GlobalLoading` component instead of the main body if `useConnectStripeAccount`'s return value for `isLoading` is `true`.  This solves for the issue in the ticket — namely, it ensures that the display of the 'Connect to Stripe' modal and toast is not delayed, and instead displays immediately on load of the main body of `Dashboard` (assuming that the account is indeed in need of Stripe connection).
Better UX for self-onboarded users.
Create a new account [here in the review app](https://dev-2750.revengine-review.org/sign-in/). 
After going through the account customization step, when taken to the `Dashboard`, you should immediately see the "Connect to Stripe" modal …

DEV-2750 | Stripe onboarding modal transition is delayed

---

spa/cypress/e2e/02-donationPageEdit.cy.js
spa/src/components/pageEditor/editInterface/EditTabHeader.stories.tsx
spa/src/components/pageEditor/editInterface/EditTabHeader.styles.ts
spa/src/components/pageEditor/editInterface/EditTabHeader.test.tsx
spa/src/components/pageEditor/editInterface/EditTabHeader.tsx
spa/src/components/pageEditor/editInterface/pageElements/PageElements.js
spa/src/components/pageEditor/editInterface/pageSidebarElements/PageSidebarElements.js

n/a
Removes the floating + buttons on the two block editing tabs in favor of a labelled button up top. Also removed the "Click the plus button" prompt when a content area is blank.
Because of weirdness I saw working with the page editor Cypress tests, I did some editing there to make tests independent of each other, to make debugging failing tests easier.
Clearer UX for the button. It's a [Cypress best practice](https://docs.cypress.io/guides/references/best-practices#Having-tests-rely-on-the-state-of-previous-tests) (and generally a testing best practice) to keep tests independent.
1. Edit a contribution page.
2. Add a block to the main content and confirm it saves properly.
3. Add a block to the sidebar and confirm it saves …

Dev 2767 move new block button to top

---

apps/contributions/admin.py
apps/contributions/models.py
apps/contributions/payment_managers.py
apps/contributions/tests/fixtures/payment-method-attached-webhook.json
apps/contributions/tests/test_models.py
apps/contributions/tests/test_payment_managers.py
apps/contributions/tests/test_views.py
apps/contributions/tests/test_webhooks.py
apps/contributions/views.py
apps/contributions/webhooks.py
revengine/settings/base.py

This PR fixes a bug that was identified in UAT for DEV-2342, which is also the base for this PR.
Once the code here has been approved, and UAT passes, this should be merged into DEV-2342 which — barring any additional bugs being identified — should be ready to merge into `main`.
The underlying cause of the bug stemmed from the `Contribution.cancel` method ([here](https://github.com/newsrevenuehub/rev-engine/pull/801/files#diff-80bc4fbf647c521d99e0b1e9e38a568c928ed7477e600e7bd110a8e9bc870ae1R373-R377)) as refactored in DEV-2342. As it turns out, you cannot cancel a `SetupIntent` whose status is processing (which is what the setup intents we create have as status after user supplies payment method and confirms payment in Stripe …

DEV-2880 | Fix bug preventing rejecting flagged recurring contributions (via DEV-2342) 

---

.github/workflows/chromatic.yml

n/a
- Blocks Chromatic CI from running on the branches listed in the YAML below. I kept `main` in for now with the idea that it is a baseline for comparison. We can revisit that later if we find ourselves bumping against the snapshot limit.
- Doesn't run Chromatic in CI for PRs that don't modify code in `spa/`.
Faster CI, prevents useless snapshots.
n/a I think since it only runs in CI. You can see Chromatic not running in this PR, but we need to check once merged that Chromatic does run on SPA commits. Alternatively, we could do a test commit on this PR that changes SPA code to show it does the right thing.
No.
No, CI only.
Not needed.
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-2897
No.
No.

DEV-2897: Limit Chromatic runs based on branch name and code changed

---

apps/contributions/models.py
apps/contributions/serializers.py
apps/contributions/tests/test_models.py
apps/contributions/tests/test_serializers.py

Fixes a bug that was causing the `contribution.contribution_metadata` field to be empty in Django admin. The underlying cause was that we simply weren't saving `contribution_metadata`, which probably happened with the far-reaching changes that accompanied supporting the new checkout flow using the Stripe Payment element.
This PR adds a `Contribution.stripe_metadata` static method that can be used to generate metadata that gets attached to Stripe payment intent and subscription and gets set as the `contribution_metadata` field on `Contribution` instances.
Make it easier to compare Stripe entities and their NRE contribution counterparts.
In the review app, go through checkout flow to create a new contribution.
Log in to the Django …

DEV-2755 |  contribution_metadata not being added to contribution instances

---

spa/cypress/e2e/02-donationPageEdit.cy.js
spa/cypress/fixtures/pages/live-page-1.json
spa/src/components/base/ImageUpload/ImageUpload.stories.tsx
spa/src/components/base/ImageUpload/ImageUpload.styled.ts
spa/src/components/base/ImageUpload/ImageUpload.test.tsx
spa/src/components/base/ImageUpload/ImageUpload.tsx
spa/src/components/pageEditor/PageEditor.js
spa/src/components/pageEditor/editInterface/EditInterface.js
spa/src/components/pageEditor/editInterface/pageSetup/PageSetup.js
spa/src/components/pageEditor/editInterface/pageSetup/PageSetup.styled.js
spa/src/components/pageEditor/editInterface/pageStyles/PageStyles.js
spa/src/components/pageEditor/editInterface/pageStyles/StylesChooser.js

n/a
- Improves the Undo functionality on the Setup and Style tabs so that it resets the fields on the respective tabs to match the original data, and no longer changes tab.
- Adds an ImageUpload base component. We have an existing one, ImageWithPreview, but it's not a controlled component so it's not possible to reset the field value. I created ImageUpload to handle this. We need to keep ImageWithPreview around for a little longer as it is also used by the Image block, and I wanted to limit PR scope.
Better UX in the page editor, better functionality in our component library.
Testing disabled state of Undo button:
1. Edit a page.
2. Confirm the Undo button is disabled in both Setup and Styles tab.
Testing Setup tab:
1. Edit a page …

Dev 2962 improve undo in editor

---

apps/emails/helpers.py
apps/emails/tasks.py
apps/emails/templates/nrh-default-contribution-base-template.html
apps/emails/tests/test_helpers.py
apps/emails/tests/test_tasks.py

This is the **third** of **3** planned stacked PRs to deliver the ticket [DEV-2783](https://news-revenue-hub.atlassian.net/browse/DEV-2783)
1. (https://github.com/newsrevenuehub/rev-engine/pull/851) (corresponding to [DEV-2783 | Update layout in receipt emails (add required tax information, contributor portal link, and refer to RP in copyright)](https://news-revenue-hub.atlassian.net/browse/DEV-2783) 
2. (https://github.com/newsrevenuehub/rev-engine/pull/868) (corresponding to [DEV-2892 | provide requested data for receipt emails](https://news-revenue-hub.atlassian.net/browse/DEV-2892))  
3. (https://github.com/newsrevenuehub/rev-engine/pull/884) (corresponding to [DEV-1758](https://news-revenue-hub.atlassian.net/browse/DEV-1758) …

DEV-1758: Include timezone in receipt emails

---

spa/src/components/common/Hero/Hero.stories.tsx
spa/src/components/common/Hero/Hero.test.tsx
spa/src/components/common/Hero/Hero.tsx

This is the **second** of **2** stacked PRs to deliver the ticket [DEV-2783](https://news-revenue-hub.atlassian.net/browse/DEV-2783)
- (https://github.com/newsrevenuehub/rev-engine/pull/879) (corresponding to [DEV-2836](https://news-revenue-hub.atlassian.net/browse/DEV-2836) Enhancement: Export contributions system notification  - **THE CURRENT PR**
- (https://github.com/newsrevenuehub/rev-engine/pull/901) (corresponding to [DEV-2231](https://news-revenue-hub.atlassian.net/browse/DEV-2974) Export button does not display when contributions table empty - **THE CURRENT PR**
Shows Export button in Contributions dashboard even if there aren't any transactions yet
Consistently show the user the Export Button so that they are aware of the functionality
Login with a user with 0 contributions (if …

DEV-2974: Export button does not display when contributions table empty

---

spa/cypress/e2e/02-donationPageEdit.cy.js
spa/cypress/fixtures/pages/live-page-1.json
spa/src/components/base/ImageUpload/ImageUpload.stories.tsx
spa/src/components/base/ImageUpload/ImageUpload.styled.ts
spa/src/components/base/ImageUpload/ImageUpload.test.tsx
spa/src/components/base/ImageUpload/ImageUpload.tsx
spa/src/components/base/Tabs/TabPanel.test.tsx
spa/src/components/base/Tabs/TabPanel.tsx
spa/src/components/donationPage/DonationPageNavbar.js
spa/src/components/donationPage/pageContent/SGraphic.js
spa/src/components/pageEditor/PageEditor.js
spa/src/components/pageEditor/editInterface/EditInterface.js
spa/src/components/pageEditor/editInterface/EditInterface.styled.ts
spa/src/components/pageEditor/editInterface/EditInterfaceTabs.styled.ts
spa/src/components/pageEditor/editInterface/EditInterfaceTabs.tsx
spa/src/components/pageEditor/editInterface/EditSaveControls.stories.tsx
spa/src/components/pageEditor/editInterface/EditSaveControls.styles.ts
spa/src/components/pageEditor/editInterface/EditSaveControls.test.tsx
spa/src/components/pageEditor/editInterface/EditSaveControls.tsx
spa/src/components/pageEditor/editInterface/pageElements/ElementProperties.js
spa/src/components/pageEditor/editInterface/pageSetup/PageSetup.js
spa/src/components/pageEditor/editInterface/pageSetup/PageSetup.styled.js
spa/src/components/pageEditor/editInterface/pageStyles/PageStyles.js
spa/src/components/pageEditor/editInterface/pageStyles/PageStyles.styled.ts
spa/src/components/pageEditor/editInterface/pageStyles/StylesChooser.js
spa/src/components/pageEditor/elementEditors/image/ImageEditor.js
spa/src/utilities/fileToDataUrl.test.ts
spa/src/utilities/fileToDataUrl.ts

n/a
- Replaces the label-less save/cancel buttons in the page editor with new designs.
- Updates page editor tabs so that they stay on top of a panel when it scrolls. This looks weird locally because the Django code at the top of the page, but should look OK in a review app (and a real one).
- Adds a `className` prop to the base TabPanel component for styling purposes.
Better UX.
1. Edit a contribution page.
2. Confirm that the Update/Undo buttons on the Setup and Style tabs match the Figma comp.
3. Make a change on the Setup tab and hit Undo. Confirm that it reverts the change.
4. Make a change on the Setup tab and hit Update. Confirm that it updates the page preview.
5. Make a change on the Style tab and hit Undo. Confirm that it …

DEV-2761: Improve save/cancel buttons

---

spa/cypress/e2e/02-donationPageEdit.cy.js
spa/src/components/pageEditor/PageEditor.js
spa/src/components/pageEditor/editInterface/pageSetup/PageSetup.js

n/a
- Fixes a bug where removing an image from the Setup tab of a contribution page doesn't save properly.
- Resolves problems with Cypress tests that don't seem related to the PR.
Fixes a bug and improves CI.
1. Edit a contribution page.
2. Add images to all possible fields on the Setup tab.
3. Save changes to the page.
4. Confirm the images show on the live page.
5. Edit the page again.
6. Remove all images you added in step 2 and make a text change to another field, like Form Panel Heading.
7. Save changes to the page.
8. Confirm that the page now shows no images and the text change you made shows correctly.
No.
Yes.
n/a
In the Cypress tests:
- I did a basic text compare to assert that the data being submitted to the API is …

DEV-3094: Fix image removal in contribution page

---

spa/.storybook/preview.js
spa/cypress/e2e/02-donationPageEdit.cy.js
spa/src/components/base/ImageUpload/__mocks__/ImageUpload.tsx
spa/src/components/donationPage/pageContent/DAmount.test.tsx
spa/src/components/donationPage/pageContent/DAmount.tsx
spa/src/components/pageEditor/PageEditor.js
spa/src/components/pageEditor/editInterface/EditInterface.js
spa/src/components/pageEditor/editInterface/pageSetup/PageSetup.js
spa/src/components/pageEditor/editInterface/pageSetup/PageSetup.test.js
spa/src/components/pageEditor/editInterface/pageStyles/PageStyles.tsx
spa/src/hooks/useContributionPage/pageUpdateToFormData.test.ts
spa/src/hooks/useContributionPage/pageUpdateToFormData.ts
spa/src/hooks/useEditablePageBatch.test.tsx
spa/src/hooks/useEditablePageBatch.ts

1. https://github.com/newsrevenuehub/rev-engine/pull/843
2. https://github.com/newsrevenuehub/rev-engine/pull/882 
3. https://github.com/newsrevenuehub/rev-engine/pull/938
4. https://github.com/newsrevenuehub/rev-engine/pull/955 (this PR)
5. 🏁 
- Adds a new hook, useEditablePageBatch. The idea of the hook is that it manages a local set of page changes that can either be committed (set in the shared context) or reset (discarded).
- Refactored the Setup and Style tabs in the page editor to use this hook. The Layout and Sidebar tabs don't have changes because they don't have the same Undo/Update buttons.
- Adds comprehensive Jest coverage of the Setup tab. I didn't do this for Style because we're going to get rid of the tab in the …

DEV-2867: Add useEditablePageBatch

---

spa/src/components/donationPage/DonationPage.d.ts
spa/src/components/donationPage/pageContent/DAmount.test.tsx
spa/src/components/donationPage/pageContent/DAmount.tsx

n/a
Fixes the issue with selecting amounts on donation pages if the frequency options list came in as an array of "strings" instead of the expected array of numbers.
Because we have an issue that if the donation page had the array of strings options the user was unable to select any of the pre-existing amount options.
- Log into the admin dashboard
- Go to `Pages > Donation Pages`
- Select a page
- Go to Elements field
- Find `type: DAmount` and go to the next `options` that you find
- Check the fields `year, month, one_time`
- Make sure at least one option has only numbers: ex `year: [200, 500, 1000]`
- Make sure at least one option has only strings (number wrapped by `"`): ex: `month: ["100", "200", "500"]`
- Save changes
- …

DEV-3166: Fix select amount when options are strings

---

spa/cypress/e2e/01-donationPage.cy.js
spa/src/components/donationPage/live/PaymentSuccess.js
spa/src/components/paymentProviders/stripe/StripePaymentForm.js
spa/src/components/paymentProviders/stripe/stripeFns.test.ts
spa/src/components/paymentProviders/stripe/stripeFns.ts

This is a stacked PR:
1. https://github.com/newsrevenuehub/rev-engine/pull/985
2. This PR
- Remove function that sends successful payment signal to BE in interstitial page 
- BE already handles payment success by listening to web hooks, so this function is no longer needed.
- Create contributions (one time & with subscription) and make sure the contribution flow remains unchanged.
no
yes
n/a
no
no
https://news-revenue-hub.atlassian.net/browse/DEV-2899
no
Related to ticket on epic:
https://news-revenue-hub.atlassian.net/browse/DEV-2744

DEV-2899: Remove signal payment success

---

spa/cypress/e2e/02-donationPageEdit.cy.js
spa/src/components/base/Checkbox/Checkbox.tsx
spa/src/components/base/FormControlLabel/FormControlLabel.tsx
spa/src/components/donationPage/pageContent/DDonorAddress.stories.tsx
spa/src/components/donationPage/pageContent/DDonorAddress.test.tsx
spa/src/components/donationPage/pageContent/DDonorAddress.tsx
spa/src/components/pageEditor/editInterface/ElementEditor.tsx
spa/src/components/pageEditor/elementEditors/donorAddress/DonorAddressEditor.js
spa/src/components/pageEditor/elementEditors/donorAddress/DonorAddressEditor.stories.tsx
spa/src/components/pageEditor/elementEditors/donorAddress/DonorAddressEditor.styled.js
spa/src/components/pageEditor/elementEditors/donorAddress/DonorAddressEditor.styled.ts
spa/src/components/pageEditor/elementEditors/donorAddress/DonorAddressEditor.styles.ts
spa/src/components/pageEditor/elementEditors/donorAddress/DonorAddressEditor.test.tsx
spa/src/components/pageEditor/elementEditors/donorAddress/DonorAddressEditor.tsx
spa/src/hooks/useContributionPage/useContributionPage.types.ts

n/a
Updates the contributor address block editor so that it can take on additional labels.
Better UX for non-USians.
1. Edit a contribution page and the Contribution Address block.
2. Check the Province checkbox and save changes.
3. Confirm that the field now shows as "State/Province" in the published page and that state is saved properly in a contribution.
4. Edit the page/block.
5. Check the Region checkbox and save changes.
6. Confirm that that the field now shows as "State/Province/Region" in the published page and that state is saved properly.
7. Create a new contribution page.
8. Confirm that the page only shows "State" as the label in the contributor address block.
We probably want to document this new functionality.
Yes. …

DEV-3135: Add state label configurability

---

spa/src/components/donationPage/pageContent/DDonorAddress.styled.ts
spa/src/styles/defaultTheme.d.ts

n/a
Fixes appearance of the address fields on contribution pages that have styles.
Fixes design bugs.
1. Create or edit a page with the default style. Confirm that fields on the page have the correct appearance (background color and outline) in the page editor.
2. Confirm the appearance is correct in the published version of the page.
3. Create a custom style and apply it to the page.
4. Confirm that the fields on the page have the correct colors in the page editor.
5. Confirm that the fields on the page have the correct colors in the published version of the page.
No.
No; changes are visual only.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-2947
No.
No.

DEV-2947: Fix input field colors on contribution page

---

spa/cypress/e2e/04-donations.cy.js
spa/src/components/common/Modal/MaxPagesReachedModal/MaxPagesReachedModal.test.tsx
spa/src/components/common/Modal/MaxPagesReachedModal/MaxPagesReachedModal.tsx
spa/src/components/content/pages/AddPage.test.tsx
spa/src/components/content/pages/AddPage.tsx
spa/src/constants/helperUrls.ts

n/a
Updates the URL that the max pages published modal points to for the Core upgrade.
Gives users a better path to upgrade.
As a free plan user:
1. Try to create too many pages.
2. Confirm the Upgrade button in the modal that appears goes to the proper URL.
As a Core plan user:
1. Try to create too many pages.
2. Confirm the Upgrade button in the modal that appears goes to the main pricing page.
No.
Yes.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-3456
No.
No.

DEV-3456: Update URL for Core plan

---

spa/cypress/e2e/01-donationPage.cy.js
spa/cypress/e2e/02-donationPageEdit.cy.js
spa/package-lock.json
spa/package.json
spa/src/components/base/Select/CountrySelect.test.tsx
spa/src/components/base/Select/CountrySelect.tsx
spa/src/components/donationPage/pageContent/DDonorAddress.test.tsx
spa/src/components/donationPage/pageContent/DDonorAddress.tsx
spa/src/hooks/useContributionPage/useContributionPage.types.ts

Updates CountrySelect to use ISO-3166-1 alpha-2 country codes instead of FIPS ones.
This is what the Stripe API expects (see Jira for more backstory).
This tests countries whose FIPS codes are different from their ISO codes.
1. Go to a contribution page.
2. Fill out fields as usual. Select Spain as your country. (The address fields don't need to match up to a real address in Spain.)
3. Confirm you're able to complete the contribution as normal.
4. Repeat steps 1-3, but selecting Poland as the country.
5. Repeat steps 1-3, but selecting United Kingdom as the country.
No.
Yes.
n/a
CI started flagging some Cypress issues that aren't related to this PR. To keep scope on this small, I created a followup story to address those and …

DEV-3322: FIPS code -> ISO code for countries

---

spa/src/components/DashboardRouter.tsx
spa/src/components/authentication/ProtectedRoute.test.tsx
spa/src/components/authentication/ProtectedRoute.tsx
spa/src/components/dashboard/Dashboard.js
spa/src/components/settings/Subscription/Subscription.styled.ts
spa/src/components/settings/Subscription/Subscription.test.tsx
spa/src/components/settings/Subscription/Subscription.tsx
spa/src/components/settings/Subscription/SubscriptionPlan.styled.ts
spa/src/components/settings/Subscription/SubscriptionPlan.test.tsx
spa/src/components/settings/Subscription/SubscriptionPlan.tsx
spa/src/components/settings/Subscription/index.ts
spa/src/constants/orgPlanConstants.ts
spa/src/routes.ts
spa/src/utilities/isAuthenticated.js
spa/src/utilities/isAuthenticated.test.ts
spa/src/utilities/isAuthenticated.ts

n/a
- Adds a route at `/settings/subscription` that shows the user their current plan. This route is only accessibly directly by URL in this PR. Note that the PR doesn't implement the entire page as it appears in Figma. See Jira discussion.
- Converts some related modules to TypeScript and adds tests around them.
Part of our Core plan work, and continues the TS/Jest migration.
Happy path, for an org admin:
1. Visit `/settings/subscription/`.
2. Confirm the plan shown and its pricing is accurate.
3. Confirm the "View full pricing comparison" link opens in a new window and goes to our pricing page.
4. Confirm the "Support" link under "Downgrade or Cancel" goes to the support page.
5. Repeat steps 1-4 for orgs with all pricing plans. …

DEV-3390: add subscription settings

---

spa/src/components/base/Table/TableRow.tsx

n/a
Fixes styles in the table base component to use a white background for even rows instead of being transparent.
Fixes appearance of donation table on styled contributor portal pages.
1. Edit a revenue program's default page and assign it background colors (both main background and form panel background).
2. Make at least two contributions using the page.
3. Sign into the contributor portal for the revenue program.
4. Confirm that table of contributions looks correct (e.g. always gray/white background colors).
5. Repeat steps 1-4 for a revenue program whose default page uses the default style.
No.
No, this is CSS only.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-2956
No.
No.

DEV-2956: Fix color of contributor dashboard table rows

---

apps/organizations/serializers.py
apps/organizations/tests/test_serializers.py

Makes `MailchimpRevenueProgramForSwitchboard.data["stripe_account_id"]` nullable 
API was choking on non-null values for stripe account ID
1. Log in as a superuser via SPA or /api/v1/token/
2. Find the ID of an RP that doesn't have stripe account ID.
3. Go to /api/v1/revenue-programs/YOUR-ID/mailchimp/.  It should 200, and there should be a key for `stripe_account_id` with the value null.
No
Updated existing
N/A
No
N/A
[DEV-3594
](https://news-revenue-hub.atlassian.net/jira/software/c/projects/DEV/boards/3?modal=detail&selectedIssue=DEV-3594)
No
N/A

DEV-3594 | make stripe_account_id nullable in MailchimpRevenueProgramForSwitchboard serializer

---

spa/src/components/settings/Subscription/Subscription.test.tsx
spa/src/components/settings/Subscription/Subscription.tsx

n/a
Handles the case when a user has no organizations. This shouldn't happen in real life, but did occur when we were doing internal testing.
Defensive coding.
I'm not sure--the gist is that we would need to create a user that is able to log in, but is not tied to an organization.
No.
Yes.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-3614
No.
No.

DEV-3614: Handle user with no organization in <Subscription>

---

spa/src/hooks/useConnectStripeAccount.test.tsx
spa/src/hooks/useConnectStripeAccount.ts

n/a
Fixes a bug in the useConnectStripeAccount hook where a user with multiple revenue programs (e.g. a Hub admin) could end seeing an infinite spinner. The gist is that there was competing logic; if you are a Hub admin, Stripe status is never retrieved, but we didn't override the loading property in the hook result to tell consumers we had nothing to load.
Makes life better for Hub admins.
I have this deployed to the dev tier, because there is data there that triggered the bug. I don't think the bug/fix will manifest on the review app.
To test the regression:
1. Log into the admin dashboard as a Hub admin.
2. See you're able to edit as usual.
To test that things continue to work for regular user:
1. Create a new user.
2. Confirm …

DEV-3332: Special case Stripe connection status for users with > 1 RP

---

spa/cypress/e2e/01-donationPage.cy.js
spa/src/components/ContributorRouter.test.tsx
spa/src/components/account/Profile/InfoTooltip.test.js
spa/src/components/base/Link/Link.test.tsx
spa/src/components/base/Modal/ModalHeader.tsx
spa/src/components/base/Tooltip/Tooltip.test.tsx
spa/src/components/common/Button/ExportButton/ExportButton.test.tsx
spa/src/components/common/Modal/AudienceListModal/AudienceListModal.test.tsx
spa/src/components/common/Modal/MaxPagesPublishedModal/MaxPagesPublishedModal.tsx
spa/src/components/common/SendTestEmail/SendTestEmail.test.tsx
spa/src/components/common/TextField/Searchbar/Searchbar.test.tsx
spa/src/components/donationPage/pageContent/DDonorAddress.test.tsx
spa/src/components/donationPage/pageContent/DSwag.js
spa/src/components/donations/DonationUpgradePrompts/DonationUpgradePrompts.test.tsx
spa/src/components/errors/ChunkErrorBoundary.test.tsx
spa/src/components/errors/GenericErrorBoundary.test.js
spa/src/components/paymentProviders/stripe/stripeFns.test.ts
spa/src/components/paymentProviders/stripe/stripeFns.ts
spa/src/components/settings/Organization/Organization.test.tsx
spa/src/elements/buttons/CircleButton.test.js
spa/src/hooks/useStyleList.test.tsx

n/a
Updates the swag block to send a `comp_subscription` value of `nyt` instead of a boolean. This is done in https://github.com/newsrevenuehub/rev-engine/pull/1154/commits/41c2051afdd7ed4f74074183c32cf08171c1900d.
Cleans up Jest warnings--not all of them, but those where I could find a fix through unit tests, or where the change was superficial. The cleanup is in f91514cabad51c68ef2a60d5cb5a2bb411aba491.
This fell out of sync with the rest of the application.
I made the test updates because I was seeing repeated CI Jest failures and the output was hard to sort through.
To test that NYT subscription options work:
1. Enable the NYT sub option on a contribution page.
2. Complete a contribution, choosing to receive an NYT …

DEV-3355: Change swag element to send nyt value

---

apps/organizations/admin.py

n/a
Makes revenue program name and slugs searchable in Django admin.
Helps support staff.
To test new functionality:
1. Log into the Django admin and go to the revenue programs page.
2. Do a search for a revenue program by name.
3. Confirm the correct results are returned.
4. Do a search for a revenue program by slug.
5. Confirm the correct results are returned.
To test existing functionality:
1. Log into the Django admin and go to the revenue programs page.
2. Do a search for a revenue program by its Stripe payment provider ID.
3. Confirm the correct results are returned.
No.
No. This is a config change and it doesn't appear we have test around this kind of thing.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-3625 …

DEV-3625: Make RP name and slug searchable

---

apps/users/serializers.py
apps/users/tests/test_serializers.py

n/a
Brings back logic related to superusers and revenue programs that was temporarily commented out for perf in c0eb862850994807070a366089fbb459cde6e416.
Fixes a bug with the style editor.
To test the proximate bug:
1. Log in as a super user.
2. Click the Customize section.
3. Create a new style.
4. Associate it to a revenue program.
5. Save changes.
6. Confirm you can apply this style to a page in the revenue program.
This change brings back functionality that had performance problems initially, so careful testing in the app for slowness is important here. We probably want to deploy this to staging ahead of prod for this reason. We should test the areas where we saw timeouts and other sluggishness previously.
No.
Yes.
n/a
No.
No. …

DEV-3611: Bring back revenue_programs for superusers

---

spa/src/components/common/Button/PublishButton/UnpublishModal/UnpublishModal.stories.tsx
spa/src/components/common/Button/PublishButton/UnpublishModal/UnpublishModal.styled.ts
spa/src/components/common/Button/PublishButton/UnpublishModal/UnpublishModal.test.tsx
spa/src/components/common/Button/PublishButton/UnpublishModal/UnpublishModal.tsx

n/a
Changes the text in the unpublish modal for pages that are the default for their revenue program.
Improved UX.
I noticed some visual glitches locally when testing with a page with a custom font set, but they should be fixed now--think it would be good to QA this with pages with custom styles.
To test the default behavior is still present:
1. Edit a published page.
2. Unpublish it.
3. Confirm the modal header and content match the existing appearance (e.g. compare with a deployed tier).
4. Click Cancel.
5. Confirm that the modal closes and the page isn't unpublished.
6. Repeat steps 1-3 but click Unpublish.
7. Confirm the page is now unpublished.
To test new behavior:
1. Edit a published page that is the default for its revenue …

DEV-3688: Change unpublish modal for default page

---

spa/src/hooks/useConnectMailchimp.test.tsx
spa/src/hooks/useConnectMailchimp.tsx

n/a
Adds additional logic to the Mailchimp hook so that only Core users can connect to it.
See Jira for more details--tl;dr is it will speed up Core onboarding.
I'll make a table here with different user configurations and expected outcome--although laborious, we should test them all.
| Plan | Has Feature Flag? | Mailchimp toggle on Integrations page                         |
| ---- | ----------------- | ------------------------------------------------------------- |
| Free | No                | Disabled and does nothing when clicked                        |
| Free | Yes               | Disabled and does nothing when clicked                        |
| Core | No                | Disabled and does nothing when clicked …

DEV-3717: Prevent Plus users from connecting to Mailchimp

---

apps/contributions/admin.py
apps/contributions/models.py
apps/contributions/tests/test_admin.py
apps/contributions/tests/test_models.py

This PR fixes an n+1 query in the list view for Contributor admin. 
It retires a property on the Contributor model — `contributions_count` — that was only used by the admin in favor of annotating contributions count on the queryset in the modeladmin. This solves for the n+1 query.
FIx a bug in prod that causes the contributor admin not to load (which is blocking importing legacy contributions into revengine).
Yes
No
Yes
N/A
No
N/A
- [DEV-3651](https://news-revenue-hub.atlassian.net/browse/DEV-3651)
- [DEV-3897](https://news-revenue-hub.atlassian.net/browse/DEV-3897)
No
[DEV-3897](https://news-revenue-hub.atlassian.net/browse/DEV-3897)
[DEV-3651]: https://news-revenue-hub.atlassian.net/browse/DEV-3651?atlOrigin=eyJpIjoiNWRkNTljNzYxNj …

DEV-3651 | Solve for n+1 query on contributor admin

---

apps/organizations/models.py
apps/organizations/tests/test_models.py

n/a
Raises the style limit for free plans to 2. This is to facilitate each page having a style, now that we are linking pages to styles directly.
Allows users to create two fully-fledged pages.
Yes.
No.
Updated test around style limit.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-3942
No.
No.

DEV-3942: Bump style quota for free plan to 2

---

apps/contributions/payment_managers.py
apps/contributions/tests/test_payment_managers.py

This PR fixes a bug that caused accepting flagged payments in Django admin to fail.
The problem was that there was code that incorrectly assumed that value being passed was a string instead of an object (specifically, it assumed that the value for subscription.latest_invoice.payment_intent was an ID, not an object, when in reality that value is an object because we expand latest_invoice.payment_intent when creating the sub).
Make accepting flagged payments work
Yes
No
Just updated existing ones
Tell Tristan he can accept payments from Django admin again.
No
N/A
[DEV-3659](https://news-revenue-hub.atlassian.net/browse/DEV-3659)
No
No
[DEV-3659]: https://news-revenue-hub.atlassian.net/browse/DEV-3659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVm …

DEV-3659 | Complete recurring payment fails in Django admin

---

spa/src/components/pageEditor/PageName/PageName.styled.ts

n/a
Fixes appearance of page name field in the editor.
Users can't see the text when the field is focused right now.
Yes.
No.
No, appearance changes only.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-4104
No.
No.

DEV-4104: Fix page name field appearance

---

spa/src/components/common/Button/ContributionPageButton/ContributionPageButton.styled.ts
spa/src/components/common/Button/ContributionPageButton/ContributionPageButton.test.tsx
spa/src/components/common/Button/ContributionPageButton/ContributionPageButton.tsx
spa/src/hooks/useContributionPageList.ts

n/a
- Adds a stale time to page list retrieval to avoid duplicate requests when loading the admin dashboard.
- Reworks page previews to use [lazy-loaded images](https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading#images_and_iframes).
Speeds up load time for hub admins.
Yes.
No.
Updated existing tests.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-3798
No.
No.

DEV-3798: hub admin spa optimizations

---

spa/src/components/common/Button/ContributionPageButton/__mocks__/ContributionPageButton.tsx
spa/src/components/content/pages/Pages.test.tsx
spa/src/components/content/pages/Pages.tsx
spa/src/hooks/useContributionPage/useContributionPage.types.ts
spa/src/hooks/usePayment.test.ts
spa/src/hooks/usePayment.ts

n/a
- Updates the type declaration of contribution page slugs to reflect that they might be `null`.
- Updates page search on the pages list to:
- Not try to search on null slugs (core problem in this story).
- Memoize the results to avoid unnecessary work.
- Flatten the results; previously we were creating a dictionary indexed by RP name, but we don't need that for display.
- Updates page list to move the loading spinner lower on the page, to the pages list, so that more of the UI loads upfront. 
- Adds logic to handle this scenario on a contribution page (but it should never happen in practice).
Fixes a bug.
Yes.
No.
Yes.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-3971
No.
No.

DEV-3971: Fix page list search

---

spa/cypress/e2e/01-donationPage.cy.js
spa/src/components/donationPage/pageContent/DDonorAddress.tsx

n/a
Changes the country field in the donor address field to select options with the Return key.
Prevents a bug where the Return key is interpreted as a form submission instead.
Yes.
No.
Yes.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-4203
No.
No.

DEV-4203: Select country with return key

---

spa/src/components/common/Button/PublishButton/PublishButton.test.tsx
spa/src/components/common/Button/PublishButton/PublishButton.tsx

n/a
Allows Hub admins and superusers to see the error message returned by the API if publishing a page fails.
Helps staff troubleshoot problems.
Yes.
No.
Updated existing.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-4145
No.
No.

DEV-4145: Show specific error to Hub admins if publish limit exceeded

---

apps/contributions/models.py
apps/contributions/tests/test_models.py
apps/contributions/tests/test_serializers.py

The underlying bug we're trying to solve for is this:  a Stripe account can set its preferences around Stripe-sent receipt emails. Orgs want to be able to turn off Stripe sent receipt emails, and they have that ability in the Stripe dashboard.
However, we learned that in our code for creating payment intents in revengine, we are setting a `receipt_email` property. This has an undesired side-effect of causing the account-level receipt email to be overridden (in case that it's set to false).
In this PR, we no longer pass through a value for optional `receipt_email` parameter when creating a stripe.PaymentIntent. This will solve the problem moving forward.
That still leaves solving the problem for all existing PIs. We'll do that in …

DEV-3509 | No longer set receipt_email when creating payment intent

---

apps/contributions/tests/test_types.py
apps/contributions/types.py

Truncates all string values in Stripe metadata on creation if over 500 characters. Otherwise Stripe complains because that's max length allowed for metadata fields.
This came up as a bug (specifically with the referer field).
Solve for bug.
Yes
No
Yes
Can let affected orgs know they can accept contributions again.
No
No
[DEV-4257](https://news-revenue-hub.atlassian.net/browse/DEV-4257)
No
N/A
[DEV-4257]: https://news-revenue-hub.atlassian.net/browse/DEV-4257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEV-4257 | Truncate string fields in Stripe metadata at > 500 characters

---

spa/src/components/common/Button/PublishButton/PublishButton.test.tsx
spa/src/components/common/Button/PublishButton/PublishButton.tsx

If Pendo is previously initialized, sends an event when a user publishes a page.
Provides better app analytics.
Yes.
No.
Yes.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-4191
No.
https://news-revenue-hub.atlassian.net/browse/DEV-4192

DEV-4191: Send Pendo event on page publish

---

spa/cypress/e2e/01-donationPage.cy.js
spa/public/static/locales/en/translation.json
spa/public/static/locales/es/translation.json
spa/src/components/donationPage/live/LiveErrorFallback.stories.tsx
spa/src/components/donationPage/live/LiveErrorFallback.styled.ts
spa/src/components/donationPage/live/LiveErrorFallback.test.tsx
spa/src/components/donationPage/live/LiveErrorFallback.tsx
spa/src/hooks/usePayment.test.ts
spa/src/hooks/usePayment.ts
spa/vite.config.js

n/a
- Sets user data in Sentry right before a payment is created on a donation page.
- Updates appearance of error message.
- Gives us additional info in Sentry to track down issues.
- Removes spurious/confusing "500" heading.
Yes.
No.
Yes.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-4305
No.
No.

DEV-4305: Identify user in Sentry upon payment creation

---

revengine/settings/base.py

n/a
- Adds configuration to make request_id enabled for services that can’t generate the X-Request-Id header at the web server level (GKE/Google)
- Enables request ID to be logged in GKE envs
yes
no
n/a
n/a
no
no
https://news-revenue-hub.atlassian.net/browse/DEV-3207
Yes, https://news-revenue-hub.atlassian.net/browse/ITS-2125
no

DEV-3207: Add support for request id logs in GKE envs

---

spa/src/components/donationPage/FinishPaymentModal/StripePaymentForm.test.tsx
spa/src/components/donationPage/FinishPaymentModal/StripePaymentForm.tsx

n/a
Memoize stripe's PaymentElement `options` so that it doesn't trigger re-renders that might break stripe create payment function.
Fix issue that avoids users from donating
n/a
no
No, no changes in functionality were made. 
n/a
no
n/a
https://news-revenue-hub.atlassian.net/browse/DEV-2945
no
no

DEV-2945: Fix IntegrationError: Invalid value for `(): elements should have a mounted Payment Element or Pay 

---

spa/src/components/PortalRouter.test.tsx
spa/src/components/PortalRouter.tsx
spa/src/components/portal/ContributionsList/ContributionsList.styled.ts
spa/src/components/portal/ContributionsList/ContributionsList.test.tsx
spa/src/components/portal/ContributionsList/ContributionsList.tsx
spa/src/components/portal/PortalPage.styled.ts
spa/src/components/portal/PortalPage.test.tsx
spa/src/components/portal/PortalPage.tsx
spa/src/components/portal/__mocks__/PortalPage.tsx
spa/src/utilities/isPortalAppPath.test.ts
spa/src/utilities/isPortalAppPath.ts

n/a
- Makes `<PortalPage>` stylable by adding a `className` prop.
- Styles `<ContributionList>` so that the background is white on mobile viewports.
Improves visual appearance.
Yes.
No.
Yes.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-4355
No.
No.

DEV-4355: Add className to PortalPage for styling

---

spa/src/components/paymentProviders/stripe/StripePaymentWrapper.test.tsx
spa/src/components/paymentProviders/stripe/StripePaymentWrapper.tsx

n/a
Makes the client secret optional in `StripePaymentWrapper`.
For payment method updates, we are going to use Stripe's Card element which doesn't require a payment or setup intent. The client secret is only used with intents. I've POC'd the approach and want to split this change out because 4408 is going to be a large PR.
Yes.
No.
Yes.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-4436
No.
https://news-revenue-hub.atlassian.net/browse/DEV-4408

DEV-4436: Make Stripe client secret optional

---

spa/src/components/settings/Subscription/ManageSubscription.test.tsx
spa/src/components/settings/Subscription/ManageSubscription.tsx

n/a
- Add sentry breadcrumbs with the "self upgrade stripe url"
- Consoles an error or warning depending on the url
- Helps understand issues that come from "manage my plan" feature
- yes
no
yes
n/a
no
no
https://news-revenue-hub.atlassian.net/browse/DEV-4443
no
no

DEV-4443: Create sentry alert for manage my plan

---

spa/src/components/donationPage/FinishPaymentModal/FinishPaymentModal.test.tsx
spa/src/components/donationPage/FinishPaymentModal/FinishPaymentModal.tsx
spa/src/components/paymentProviders/stripe/StripePaymentWrapper.test.tsx
spa/src/components/paymentProviders/stripe/StripePaymentWrapper.tsx
spa/src/components/paymentProviders/stripe/__mocks__/StripePaymentWrapper.tsx

n/a
Tries to fix possible issues with Stripe elements in the contribution page payment modal. I wasn't able to repro the bug exactly, but I applied the best practices we used in https://news-revenue-hub.atlassian.net/browse/DEV-2945:
- Move `StripePaymentWrapper` higher in the component hierarchy in `CompletePaymentModal` to avoid it being potentially conditionally rendered
- Memoize the `options` object passed to Stripe's Elements component to avoid re-renders
Addresses bug with contribution pages.
Yes.
No.
Yes.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-4007
No.
No.

DEV-4007: Improve Stripe handling in modal

---

apps/contributions/models.py
apps/contributions/tests/test_models.py
spa/src/ajax/portal-axios.test.ts
spa/src/ajax/portal-axios.ts
spa/src/components/portal/ContributionsList/ContributionsList.styled.ts
spa/src/components/portal/ContributionsList/ContributionsList.tsx
spa/src/hooks/usePortalContribution.test.tsx
spa/src/hooks/usePortalContribution.tsx
spa/src/hooks/usePortalContributionList.test.ts
spa/src/hooks/usePortalContributionList.ts

n/a
- Align the loading, error, empty contribution components in the correct place on screen
- Refetches data 15 seconds after update or cancel contribution
- Redirects to magic link page if not logged in
- Remove sentry alert from being triggered if stripe returns "card declined" error
- Refining new portal for launch
- yes
- no
- yes
- n/a
- no
- no
- https://news-revenue-hub.atlassian.net/browse/DEV-4467
- no
- New Portal UI Updates Epic: https://news-revenue-hub.atlassian.net/browse/DEV-3780

DEV-4467: Portal pre-release refinements

---

.pre-commit-config.yaml
apps/api/error_messages.py
apps/common/management/commands/create_stripe_webhooks.py
apps/common/secrets.py
apps/contributions/tests/test_models.py
apps/contributions/tests/test_webhooks.py
apps/contributions/tests/test_webhooks_integration.py
apps/contributions/views.py
apps/emails/tasks.py
apps/emails/tests/test_tasks.py
apps/organizations/models.py
apps/organizations/views.py
apps/users/forms.py
apps/users/views.py
poetry.lock
pyproject.toml
revengine/settings/base.py

- Sprintly server-side dependencies upgrade
- Pins pytest to v7 for now, because of incompatibility of 8 with pytest asyncio, which is a sub dependency.  ([See here in GH for pytest, for more details](https://github.com/pytest-dev/pytest/issues/11868)).
- Makes small change to `apps/users/views.py::password_reset_token_created` because that function broke in case of non-authed request with upgrade of django-rest-passwordreset
- All of the remaining changes are formatting changes introduced by updating pre-commit
Sprintly process to help with security and bug fixes of third party packages.
N/A
No
N/A
N/A
No
N/A
[DEV-4435](https://news-revenue-hub.atlassian.net/browse/DEV-4435)
No
N/A
[DEV-4435]: …

DEV-4435 | sprintly dependencies upgrade

---

spa/src/components/portal/ContributionsList/ContributionDetail/ContributionDetail.styled.ts
spa/src/components/portal/ContributionsList/ContributionDetail/ContributionDetail.test.tsx
spa/src/components/portal/ContributionsList/ContributionDetail/ContributionDetail.tsx
spa/src/components/portal/ContributionsList/ContributionDetail/DetailSection/DetailSection.tsx
spa/src/components/portal/ContributionsList/ContributionDetail/LoadingSkeleton/LoadingSkeleton.stories.tsx
spa/src/components/portal/ContributionsList/ContributionDetail/LoadingSkeleton/LoadingSkeleton.test.tsx
spa/src/components/portal/ContributionsList/ContributionDetail/LoadingSkeleton/LoadingSkeleton.tsx
spa/src/components/portal/ContributionsList/ContributionDetail/LoadingSkeleton/index.ts
spa/src/hooks/usePortalContribution.tsx

n/a
- Improves loading indicator for contribution detail
- Improve UX
- yes
- yes
- yes
- n/a
- no 
- no
- https://news-revenue-hub.atlassian.net/browse/DEV-4347
- no
- Parent ticket: https://news-revenue-hub.atlassian.net/browse/DEV-3780

DEV-4347: Show placeholders for contribution detail instead of spinner in new portal

---

spa/src/components/dashboard/sidebar/SidebarCoreUpgradePrompt/SidebarCoreUpgradePrompt.styled.ts
spa/src/components/dashboard/sidebar/SidebarCoreUpgradePrompt/SidebarCoreUpgradePrompt.test.tsx
spa/src/components/dashboard/sidebar/SidebarCoreUpgradePrompt/SidebarCoreUpgradePrompt.tsx

n/a
Updates the Core upgrade CTA in the nav bar to point to the subscription settings page instead of the public site pricing page.
Makes it easier to upgrade.
Yes.
No.
Updated existing.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-4206
No.
No.

DEV-4206: Update wording around Core upgrade

---

apps/contributions/tests/test_views.py
apps/contributions/views.py

n/a
Filters out rejected and processing contributions from new endpoints. They don't appear in contribution lists and trying interact with detail (GET, PATCH, DELETE) returns a 404.
These shouldn't be visible to contributors.
Yes.
No..?
Yes.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-4482
No.
No.

DEV-4482: Don't let contributors see rejected or processing contributions

---

apps/contributions/stripe_import.py
apps/contributions/tests/test_stripe_import.py

This PR changes two lines of code that were lowercasing currency on contributions when importing/upserting from Stripe so that they instead uppercase.
I made the change that used .lower() in the PR for [DEV-4595](https://github.com/newsrevenuehub/rev-engine/pull/1462) because I mistakenly thought that all NRE contributions used lowercase currency on contribution creation (through donation page flow), and that by upserting data from Stripe (which uses uppercase currency) we would be making an unneeded change across all touched contributions. I also mistakenly thought that Stripe was storing currency as uppercase, when in fact it stores as lowercase.
As it turns out, the vast majority of our contributions made through donation pages …

DEV-4627 | Force currency to uppercase in stripe import command

---

README.md
apps/common/admin.py
apps/config/admin.py
apps/contributions/admin.py
apps/contributions/stripe_import.py
apps/contributions/tests/test_stripe_import.py
apps/organizations/admin.py
apps/pages/admin.py
apps/users/admin.py
apps/users/tests/test_admin.py

- Fixes a bug in `StripeTransactionsImporter` that caused it to exclude PIs that didn't have conforming payment metadata. This was a relic of earlier iteration of that code that used a different strategy for retrieving subscriptions and payment intents for one-time contributions (earlier, that exclusion made sense because we didn't look to PIs to determine which subscriptions to retrieve). This bug was causing subscriptions and therefore recurring contributions to be excluded from upsertion.
- Updates `RevEngineBaseAdmin` to inherit from `CompareVersionAdmin` and replaces inline usage of modeladmins inheriting from CompareVersionAdmin/VersionAdmin. This standardizes the reversion behavior across modeladmins that inherit from …

DEV-4634 | Fix bug with metadata validation for payment intents in Stripe transactions import command

---

apps/common/utils.py
apps/contributions/stripe_import.py
apps/contributions/tasks.py
apps/contributions/tests/test_stripe_import.py

This PR refactors the Stripe import code so we do not use an excessive amount of memory. It does this by collecting required data and upserting transactions one a time instead of retrieving all required data, storing in memory, and then upserting all transactions at the end.
Some specific changes:
- Adds `apps.common.utils.stripe_call_with_backoff` which can be used to make Stripe API calls that will retry with exponential backoff if Stripe returns a rate limit error. I encountered a Stripe rate limit error one time when running this code in the review app, which prompted this change.
- No longer "unravels" the iterable returned by .`auto_paging_iter` in place in methods that use `.list` methods from Stripe. This means that we …

DEV-4638 | reimplemented to use less memory

---

apps/contributions/stripe_import.py
apps/contributions/tests/test_stripe_import.py

Fixes a bug in import stripe transactions code that caused payments to not be created or updated.
Specifically, the bug stemmed from attempting to iterate results of a generator (charges returned by using stripe.Charge.list.auto_paging_iter) more than once. On the second time through the generator was empty, and that second run through was what fed the charges that are used to attempt to create payments.
Additionally, this PR removes a method that was no longer used that I missed removing in DEV-4638.
Makes import transactions data command usable. Unblocks portal.
Yes
No
Yes: current test updated to have mock return a generator instead of a list, to better capture actual implementation

DEV-4644 | fix bug around payment creation, remove unused method

---

apps/common/utils.py
apps/contributions/management/commands/import_stripe_transactions_data.py
apps/contributions/stripe_import.py
apps/contributions/tasks.py
apps/contributions/tests/test_stripe_import.py
apps/contributions/tests/test_tasks.py
poetry.lock
pyproject.toml

This PR adds an option to the Stripe transaction import command (defaulting to false) to skip processing for retrieved payment intents that already a.) have a corresponding contribution; and b.) have at least one payment for that corresponding contribution.
Additionally:
- Retires `stripe_call_with_backoff` in favor of using the (newly added) [backoff](https://pypi.org/project/backoff/) library for handling API rate limit errors from Stripe
- Changes log message from warning to info when a charge or refund is encountered that does not have a balance transaction. It turns out this is a normal/expected occurrence and we don't need this polluting Sentry.
- Solves for [DEV-4648](https://news-revenue-hub.atlassian.net/browse/DEV-4648) …

DEV-4645 | add option to backfill command to skip updates of payment and contributions only do inserts for speed

---

apps/contributions/models.py
apps/contributions/stripe_import.py
apps/contributions/tests/test_models.py
apps/contributions/tests/test_stripe_import.py

This PR solves for a bug that caused the Stripe transactions import command to fail when it encountered a balance transaction that was already associated with an existing contribution. Because `stripe_balance_transaction_id` has a uniqueness constraint, that caused the upsert to fail, and the exception was not caught, so it crashed the command.
This PR narrowly addresses the uncaught exception, making it caught, and logging. It is up to a different tickets (DEV-4609 / DEV-4666) to solve for the root cause.
Additionally, this PR makes a small change to `Contribution.__str__` — adding the contribution id to its string representation — because that would have been helpful when running down this bug.
Unblock data import, which unblocks …

Dev 4660 stripe data import fails when 1 charge with same balance transaction

---

spa/src/ajax/endpoints.ts
spa/src/components/portal/ContributionsList/ContributionDetail/BillingHistory/BillingHistory.test.tsx
spa/src/components/portal/ContributionsList/ContributionDetail/BillingHistory/BillingHistory.tsx
spa/src/components/portal/ContributionsList/ContributionDetail/BillingHistory/__mocks__/BillingHistory.tsx
spa/src/components/portal/ContributionsList/ContributionDetail/ContributionDetail.test.tsx
spa/src/components/portal/ContributionsList/ContributionDetail/ContributionDetail.tsx
spa/src/hooks/usePortalContribution.test.tsx
spa/src/hooks/usePortalContribution.tsx

Stacked PRs:
[main <- DEV-3878](https://github.com/newsrevenuehub/rev-engine/pull/1490) <- DEV-3879 (this)
- Implements "Resend Receipt" button in Portal
- Allow for donors to get the receipt email if they lost the original one
- yes
- yes
- yes
- Contributors now are allowed to resend receipts
- no
- no 
- https://news-revenue-hub.atlassian.net/browse/DEV-3879
- no
- no

DEV-3879: Implement "Resend Receipt" button in Portal

---

apps/contributions/tests/test_views.py
apps/contributions/views.py
spa/src/ajax/endpoints.ts
spa/src/components/portal/ContributionsList/ContributionDetail/BillingHistory/BillingHistory.test.tsx
spa/src/components/portal/ContributionsList/ContributionDetail/BillingHistory/BillingHistory.tsx
spa/src/components/portal/ContributionsList/ContributionDetail/BillingHistory/__mocks__/BillingHistory.tsx
spa/src/components/portal/ContributionsList/ContributionDetail/ContributionDetail.test.tsx
spa/src/components/portal/ContributionsList/ContributionDetail/ContributionDetail.tsx
spa/src/hooks/usePortalContribution.test.tsx
spa/src/hooks/usePortalContribution.tsx

Stacked PRs:
main <- [DEV-3878 <- DEV-3879](https://github.com/newsrevenuehub/rev-engine/pull/1492)
Adds endpoint for donors to send a receipt email from a contribution
Allow for re-sending of receipts
yes
no
yes
n/a
no
no
https://news-revenue-hub.atlassian.net/browse/DEV-3878
no
Yes, here is the parent ticket: https://news-revenue-hub.atlassian.net/browse/DEV-3782

DEV-3878: Add send contribution receipt endpoint

---

spa/package-lock.json
spa/package.json
spa/src/components/base/RichTextEditor/RichTextEditor.test.tsx
spa/src/components/base/RichTextEditor/RichTextEditor.tsx

n/a
Fixes issue when pasting text into RichTextEditor 
Makes copy&paste work as expected
yes
no
yes
Copy&Paste to RichTextEditor now keeps original's text formatting
no
no
https://news-revenue-hub.atlassian.net/browse/DEV-4632
no
no

DEV-4632: Fix RichTextEditor paste losing formatting issue

---

apps/contributions/stripe_import.py
apps/contributions/tests/test_stripe_import.py

The base for this PR is initially DEV-4776 because this branch presupposes those changes. After DEV-4776 has been merged, this should point to main.
This PR makes some small changes to `apps.contributions.stripe_import` in order to improve logging around API rate limiting from Stripe, as encountered by backoff, which is the decorator we use to manage exponential backoff when facing rate limits.
- Adds a customer logging handler in `stripe_import.py` that prepends a timestamp to all logs
- Adds a custom logging function as argument for `on_backoff` param of `_STRIPE_API_BACKOFF_ARGS` which will cause custom logging that includes relevant details from Stripe (such as status code, user message, etc.) when a rate limit is encountered. …

DEV-4789 | better logging when backoff for stripe rate limit

---

apps/contributions/stripe_import.py
apps/contributions/tests/test_stripe_import.py

This PR uses `@cached_property` in several places to store the results of costly (in terms of time) calls to `redis.scan_iter`. 
Additionally, adds log that indicates how many total contributions to be processed (subscription count + 1-time PI count) and logs for each individual contribution being processed indicating which number transaction currently being processed.
Greatly speed up transaction importer command.
Not for review app. This will of necessity need to be tested vis a vis prod.
Existing updated
N/A
No
N/A
[DEV-4852](https://news-revenue-hub.atlassian.net/browse/DEV-4852)
No
N/A
[DEV-4852]: https://news-revenue-hub.atlassian.net/browse/DEV-4852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHV …

DEV-4852 | Memoize redis.scan_iter key lookups to speed up subscription processing in Stripe transactions importer

---

apps/contributions/stripe_import.py

Fixes a bug where we called `update_payment_stats` when a payment was neither created nor found.  This bug didn't crash the import, but it did cause noise in Sentry logs.
No. Getting Stripe in required state to reproduce in review app is difficult.
No
No. I don't think we want unit tests about something this specific (namely that `update_payment_stats` does not get called in certain circumstances).
N/A
No
N/A
[DEV-4859](https://news-revenue-hub.atlassian.net/browse/DEV-4859)
No
No
[DEV-4859]: https://news-revenue-hub.atlassian.net/browse/DEV-4859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEV-4859 | Fix bug with `update_payment_stats`

---

apps/contributions/stripe_import.py
apps/contributions/tests/test_stripe_import.py

Fixes a bug in code that retrieves refunds for a subscription. That code was — due to a recent regression — returning all the refunds for the account, not only the ones for the specific subscription.
Fix stripe import, which is currently broken by regression.
Yes.
No
Updated existing
N/A
No
No
[DEV-4862](https://news-revenue-hub.atlassian.net/browse/DEV-4862)
[ITS-2395](https://news-revenue-hub.atlassian.net/browse/ITS-2395) should be run before merging. That will zero out the bunk set of payments created, and then we can redo import for the effected account.
No
[DEV-4862]: https://news-revenue-hub.atlassian.net/browse/DEV-4862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEV-4862 | Fix bug with getting refunds per subscription

---

apps/organizations/models.py
apps/organizations/tests/test_models.py

n/a
Fixes a bug where trying to retrieve a Mailchimp product for a disconnected revenue program raises an exception instead of returning None.
Fixes a regression in DEV-4244 affecting the switchboard endpoint.
Yes.
No.
Yes.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-4865
https://news-revenue-hub.atlassian.net/browse/DEV-4244
No.
No.

DEV-4865: Return None for Mailchimp products when not connected

---

spa/cypress/e2e/12-account.cy.js
spa/src/components/account/SignUp/SignUpForm.styled.ts
spa/src/components/account/SignUp/SignUpForm.test.tsx
spa/src/components/account/SignUp/SignUpForm.tsx

n/a
Moves account signup form to use react-hook-form.
Moves us toward using a consistent approach on validation.
Yes.
No.
Yes.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-4892
No.
Continue migrating other account forms.

DEV-4892: Use react-hook-form with signup form

---

apps/contributions/management/commands/fix_recurring_contribution_missing_provider_subscription_id.py
apps/contributions/tests/test_management_commands.py

Adds a management command to locate contributions that are missing subscription IDs, and attempts to repair the data by walking through other Stripe objects.
Fixes a data issue that occurred in the past.
I tried out adding a Jupyter notebook to the ticket. Not sure if I did it the correct way as it requires filling in IDs into the notebook for it work.
No.
Yes.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-4772
No.
Root cause investigation for the data issue.

DEV-4772: Add management command to fix contributions w/o sub IDs

---

apps/contributions/tests/test_webhooks.py
apps/contributions/webhooks.py

Hotfix a bug to unbreak prod. Come back later and figure out tests and any other next steps.  We'll specifically want to run down which circumstances cause a charge.succeeded with no PI.
Solves for a bug whereby:
- We attempt to update contributions for a charge.succeeded event even if payment intent for the charge is null
- We retrieve the PM from stripe for each contribution in our db that has null value for provider payment ID
Unbreak prod
No
No
No. This is urgent hotfix.
TBD. Will need to determine if affected transactions.
Not testing new conditional paths introduced just yet, but can do in followup.
No
ITS-2445
No
No tickets yet but we will continue ongoing discussion in Slack and create tickets as needed.

Hotfix: solve for payment_intent id is null causing recurring calls to retreive PM id and update all null provider payment id contributions

---

spa/src/components/portal/ContributionsList/ContributionDetail/BillingHistory/BillingHistory.test.tsx
spa/src/components/portal/ContributionsList/ContributionDetail/BillingHistory/BillingHistory.tsx
spa/src/hooks/usePortalContribution.test.tsx
spa/src/hooks/usePortalContribution.tsx

n/a
Changes the billing history section to show transaction time instead of creation time where available. **If transaction time is unset, this falls back to showing the creation time.**
Shows correct dates in portal.
Yes.
No.
Yes.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-5035
No.
No.

DEV-5035: Show transaction date, not payment creation date, in billing history

---

spa/src/components/portal/ContributionsList/ContributionDetail/BillingHistory/BillingHistory.stories.tsx
spa/src/components/portal/ContributionsList/ContributionDetail/BillingHistory/BillingHistory.styled.ts
spa/src/components/portal/ContributionsList/ContributionDetail/BillingHistory/BillingHistory.test.tsx
spa/src/components/portal/ContributionsList/ContributionDetail/BillingHistory/BillingHistory.tsx
spa/src/components/portal/ContributionsList/ContributionDetail/common.styled.ts

n/a
Handles when Billing History is empty in Portal
Improves usability for donors that have active payments, but no payment history to understand what is going on
yes
yes
yes
n/a
no
no
https://news-revenue-hub.atlassian.net/browse/DEV-4868
no
no

DEV-4868: Handle empty Billing History section in Portal

---

apps/contributions/models.py
apps/contributions/tests/test_models.py

Adds abandoned to set of excluded statuses in `having_org_viewable_status` method.
Orgs should not see abandoned contributions, and we missed this when originally adding that status.
Yes.
No
Yes
N/A
No
No
[DEV-5060](https://news-revenue-hub.atlassian.net/browse/DEV-5060)
No
No
[DEV-5060]: https://news-revenue-hub.atlassian.net/browse/DEV-5060?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEV-5060 | Exclude abandoned contributions from org dashboard

---

apps/contributions/models.py
apps/contributions/tests/test_models.py
apps/contributions/tests/test_views.py
apps/contributions/views.py

This PR makes a small code change to exclude contributions from portal where both of following are true:
- recurring
- missing provider_subscription_id
For a lengthy explanation of reasoning behind this, [please see this comment in JIRA](https://news-revenue-hub.atlassian.net/browse/DEV-5037?focusedCommentId=120074)
Unblocks portal release and removes potentially confusing data from portal.
Yes.
N/A
Yes
N/A
No
No
- [DEV-5037](https://news-revenue-hub.atlassian.net/browse/DEV-5037)
- [DEV-5059](https://news-revenue-hub.atlassian.net/browse/DEV-5059)
- [DEV-5062](https://news-revenue-hub.atlassian.net/browse/DEV-5062)
No
- [DEV-5059](https://news-revenue-hub.atlassian.net/browse/DEV-5059)
- …

DEV-5037 | Short term fix for excluding duplicated recurring contributions

---

apps/contributions/serializers.py
apps/contributions/tests/test_serializers.py
apps/contributions/tests/test_views.py

- `PortalContributionBaseSerializer` updated so that `first_payment_date` value in serialized object is equal to the date conversion of the first payment's transaction time or else the contribution's created.
- Fixes referential integrity of contribution.first_payment_date, which unblocks portal release.
Coming soon
No
Yes
N/A
No
No
- [DEV-5161](https://news-revenue-hub.atlassian.net/browse/DEV-5161)
- [DEV-5173](https://news-revenue-hub.atlassian.net/browse/DEV-5173)
- [DEV-5174](https://news-revenue-hub.atlassian.net/browse/DEV-5174)
- [DEV-5175](https://news-revenue-hub.atlassian.net/browse/DEV-5175)
No
- [DEV-5173](https://news-revenue-hub.atlassian.net/browse/DEV-5173)
- …

DEV-5161 | derive value instead of getting from db

---

apps/contributions/models.py
apps/contributions/serializers.py
apps/contributions/tests/test_models.py
apps/contributions/tests/test_serializers.py
apps/contributions/tests/test_views.py
apps/contributions/views.py
spa/src/components/portal/ContributionsList/ContributionsList.test.tsx
spa/src/components/portal/ContributionsList/ContributionsList.tsx

n/a
- Moves the `first_payment_date` serializer field to an annotation created by a new method on `ContributionQuerySet`.
- Changes the ordering of contributions to use `first_payment_date` instead of `created`.
- We need `first_payment_date` to exist on the queryset instead of the serializer so that it can be sorted on.
- Sorts migrated contributions correctly.
Yes.
No.
Updated existing.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-5162
No.
No.

DEV-5162: Sort contributions in list by first_payment_date

---

spa/src/appSettings.ts
spa/src/components/donationPage/DonationPage.jsx
spa/src/components/paymentProviders/stripe/stripeFns.test.ts
spa/src/components/paymentProviders/stripe/stripeFns.ts
spa/src/hooks/usePayment.test.ts

This is stacked on top of PR https://github.com/newsrevenuehub/rev-engine/pull/1600
`main <- DEV-5105 <- DEV-5119`
Sends "mc_campaign_id" from URL query param to the BE 
Add support for "mc_campaign_id" to stripe and contribution metadata
yes
no
yes
Added support for “mc_campaign_id”
no
no
https://news-revenue-hub.atlassian.net/browse/DEV-5119
no
https://news-revenue-hub.atlassian.net/browse/DEV-4357

DEV-5119: Add support for “mc_campaign_id” to the 1.4 metadata schema in NRE - SPA

---

apps/common/utils.py
apps/organizations/models.py
apps/organizations/tests/test_models.py
apps/users/serializers.py

This PR fixes a bug that allowed an uncaught integrity error around a uniquness constraint on slug to bubble up to org user as a generic error with no further information.   For more detail on the bug, please see the [JIRA ticket](https://news-revenue-hub.atlassian.net/browse/DEV-5080).
- Refactors `Organization.generate_unique_name` to make case insensitive queries (which I believe would have prevented the bug we're seeing in the first place had we been doing this before)
- Refactors `Organization.generate_slug_from_name` to make case insensitive query and raise Validation error if generated slug already exists. 
Better signup experience for orgs
Yes.
No
Yes
N/A
No
No
[DEV-5080](https://news-revenue-hub.atlassian.net/browse/DEV-508 …

DEV-5080 | Account for case variation in org name

---

spa/src/components/donationPage/pageContent/DDonorAddress.test.tsx
spa/src/components/donationPage/pageContent/DDonorAddress.tsx

n/a
Adds a check for the `google.maps` object to address autocomplete on a contribution page.
In some instances, we see that although an error isn't reported by useGoogleMaps, the API nevertheless isn't present or available in the global environment. This probably is caused by browser ad blockers or other privacy-related software. This handles this scenario more gracefully.
Yes.
No.
Yes.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-4654
No.
No.

DEV-4654: Be more careful about presence of Google Maps API

---

spa/src/components/portal/ContributionsList/ContributionDetail/ContributionDetail.test.tsx
spa/src/components/portal/ContributionsList/ContributionDetail/ContributionDetail.tsx

n/a
Changes the criteria for who is allowed to change their contribution amount to all RPs on a paid plan.
New portal rollout.
Yes.
Maybe need to document availability?
Yes.
Announcement re: rollout.
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-5309
No.
No.

DEV-5309: Allow Core org contributors to change contribution amount

---

apps/api/permissions.py
apps/contributions/tests/test_views.py
apps/contributions/views.py

Changes permissions on portal contributions list view such that superuser's can access the endpoint in order to help debug contributor issues.
Better respond to bug reports about portal
Yes
No
Yes: existing updated
We should create a confluence that explains how to do this (for less technical folks)
No
No, but see above about how to communicate.
[DEV-5449](https://news-revenue-hub.atlassian.net/browse/DEV-5339)
No
No
[DEV-5339]: https://news-revenue-hub.atlassian.net/browse/DEV-5339
[DEV-5449]: https://news-revenue-hub.atlassian.net/browse/DEV-5449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEV-5339 | allow superusers to access contributions list endpoint (via API)

---

apps/contributions/models.py
apps/contributions/serializers.py
apps/contributions/tests/test_models.py
apps/contributions/tests/test_serializers.py
apps/contributions/tests/test_views.py
spa/src/components/portal/ContributionsList/ContributionDetail/BillingDetails/BillingDetails.test.tsx
spa/src/components/portal/ContributionsList/ContributionDetail/BillingDetails/BillingDetails.tsx
spa/src/components/portal/ContributionsList/ContributionDetail/BillingDetails/__mocks__/BillingDetails.tsx
spa/src/components/portal/ContributionsList/ContributionDetail/ContributionDetail.test.tsx
spa/src/components/portal/ContributionsList/ContributionDetail/ContributionDetail.tsx
spa/src/hooks/usePortalContribution.tsx

n/a
- Adds a `donor_selected_amount` that is only available when PATCHing an individual contribution. Sending a value here updates the contribution metadata.
- Changes the SPA to send both `amount` and `donor_selected_amount`.
Corrects a problem where donor_selected_amount is getting to set to an amount in cents rather than dollars.
I went with this approach to minimize the amount of math we are doing to amounts, to avoid possible problem sources re: rounding.
Yes.
No.
Yes.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-5429
No.
No.

Dev 5429 set amount metadata correctly

---

spa/cypress/e2e/01-donationPage.cy.js
spa/src/components/donationPage/DonationPage.jsx
spa/src/components/donationPage/FinishPaymentModal/FinishPaymentModal.test.tsx
spa/src/components/donationPage/FinishPaymentModal/FinishPaymentModal.tsx
spa/src/hooks/usePayment.test.ts
spa/src/hooks/usePayment.ts

n/a
- Changes `usePayment` to expose the delete mutation instead of an async function.
- Disables the back button in the payment modal while the payment is being deleted.
Prevents an error where clicking the button repeatedly causes network errors (the payment is attempted to be deleted multiple times) and gets the page into a stuck state.
Yes.
No.
Yes.
n/a
I created https://news-revenue-hub.atlassian.net/browse/DEV-5567 to track work on making the modal loading process more bulletproof/faster.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-5499
No.
No.

DEV-5499: Disable exiting payment modal if payment is deleting

---

spa/cypress/e2e/04-donations.cy.js
spa/src/components/donations/Donations.jsx
spa/src/components/donations/DonationsTable.jsx

n/a
Reverts admin-facing part of https://github.com/newsrevenuehub/rev-engine/pull/1674/
We are in fact seeing null first payment dates and it's causing problems in the UI.
TBD
This is a reversion of a change to previous behavior.
Updated Cypress.
n/a?
No.
No.
- https://news-revenue-hub.atlassian.net/browse/DEV-5599
- https://news-revenue-hub.atlassian.net/browse/DEV-5502
No.
More comprehensive fix.

DEV-5599: Revert Contributions section part of DEV-5502

---

apps/contributions/stripe_import.py
apps/contributions/tests/test_stripe_import.py

n/a
Map "past_due" to FAILED.  The initial impetus for this was to respond to an issue we found with `audit_recurring_contributions` management command on first run. There were a number of contributions it flagged as having an unexpected status.  See [this comment in JIRA](https://news-revenue-hub.atlassian.net/browse/DEV-5511?focusedCommentId=132870) for more context.
The method in question (`StripeTransactionsImporter.get_status_for_subscription`) is used in 3 places:
- audit_recurring_contributions 
- when accepting a flagged contribution in Django admin
- in Stripe transaction import when upserting a recurring contribution
In each case, we want subscriptions with "past_due" status to map to "failed" in our system.
This will …

DEV-5538: Past due maps to FAILED

---

spa/cypress/e2e/01-donationPage.cy.js
spa/src/components/donationPage/pageContent/DReason.jsx

n/a
Corrects the field that the text input for reason for giving looks at to display a validation error.
Shows the user an error message they should see.
Yes.
No.
I added Cypress tests because it seemed like the fastest route forward.
n/a
I created https://news-revenue-hub.atlassian.net/browse/DEV-5640 to overhaul this component.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-5617
No.
https://news-revenue-hub.atlassian.net/browse/DEV-5640

DEV-5617: Band-aid fix for error validation

---

apps/contributions/models.py
apps/contributions/tests/test_models.py

Fixes a bug whereby we were logging a warning, thereby creating Sentry noise when the `Contribution.canceled_at` property was referenced on one-time contributions.
Yes.
No
Yes
N/A
No
N/A
[DEV5281](https://news-revenue-hub.atlassian.net/browse/DEV-5281)
No
N/A

DEV-5281 | Fix bug with canceled_at on one-time contributions

---

apps/organizations/models.py
apps/organizations/serializers.py
apps/organizations/tests/test_models.py
apps/organizations/tests/test_serializers.py
apps/organizations/tests/test_typings.py
apps/organizations/typings.py

n/a
- Makes `mailchimp_connection_ready` looser
- Restores the `mailchimp_recurring_contribution_product` field on RevenueProgram
Fixes issues for existing integrations.
TBD
No.
Yes.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-5939
No.
Backfill missing data.

DEV-5939: Loosen criteria for Mailchimp ready, re-add recurring product field to model

---

apps/contributions/models.py
apps/contributions/serializers.py
apps/contributions/tests/views/test_switchboard.py
apps/contributions/views/switchboard.py

This PR adds validation to the contribution creation API endpoint used by Switchboard so that contributions cannot be created without a contributor, and cannot be updated such that contributor would be nullfieid.
There is no use case for contributor-less contributions, but it's an affordance of the API as currently implemented.
Yes.
No.
yes
N/A
No, but this is a short term fix and I've created a follow up ticket to make contribution.contributor non-nullable at DB level ([DEV-5953](https://news-revenue-hub.atlassian.net/browse/DEV-5953)).
Also noting that in devising QA for this ticket, I encountered a bug whereby it's possible to create a contribution via the endpoint, requesting receipt email to be sent, and for the contribution …

DEV-5896 | make contributor non-nullable at serializer level

---

spa/src/components/base/ImageUpload/ImageUpload.tsx

n/a
Removes SVG as a possible image format to upload.
Django's ImageField doesn't support this.
Yes.
No.
No, changing a config string only.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-5897
No.
No.

DEV-5897: Remove SVG as supported image type

---

apps/contributions/tests/views/test_switchboard.py
apps/contributions/views/switchboard.py

N/A
This PR adds filtering capabilities to the Switchboard API endpoints:
1. Adds filtering by `provider_subscription_id` and `provider_payment_id` to `SwitchboardContributionsViewSet`
2. Adds filtering by `stripe_balance_transaction_id` to `SwitchboardPaymentsViewSet` 
I opted for DjangoFilterBackend instead SearchFilter as it is more in line with other api filtering standards (including Stripe's, which I consider one of the best out there).
This initial implementation was motivated by Switchboard's need to upsert payment or contribution records. Switchboard needs to be able to check if there is an existing contribution or payment to guarantee idempotency.
Yes
API only change
Yes
N/A - This is an internal API change that only affects Switchboard integration.
Nope
N/A
[DEV-5972]
N/A …

DEV-5972: allow filtering of contributions and payments

---

apps/contributions/tasks.py
apps/contributions/tests/test_tasks.py

Updates process_stripe_webhook_task such that we only pass known kwargs to StripeEventData constructor.  This is because we encountered a bug where there is a new `context` property in the passed data, and the `StripeEventData` constructor doesn't know what to do with this argument.
Solves for a bug that broke webhook processing for contributions related events.
Yes.
No.
Yes.
We'll need to do client-facing comms re: the outage.
No
No
- [DEV-6079](https://news-revenue-hub.atlassian.net/browse/DEV-6079)
- [ITS-3046](https://news-revenue-hub.atlassian.net/browse/ITS-3046)
- [DEV-6080](https://news-revenue-hub.atlassian.net/browse/DEV-6080)
No
- [ITS-3046](https://news-revenue-hub.atlassian.net/browse/ITS-3046)
- …

DEV-6079 | Fix stripe webhook processing

---

apps/contributions/admin.py
apps/contributions/static/admin/css/quarantine-admin.css
apps/contributions/tests/test_admin.py

n/a
- Refactors HTML for admin quarantine actions into a shared function.
- Display admin quarantine actions on flagged contribution detail pages in Django admin.
- Streamlines custom CSS.
Allows admins to process quarantined contributions faster.
Yes.
Not sure if we're documenting admin UI.
Yes but I'm unsure they're complete.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-6227
No.
No.

DEV-6227: Add quarantine actions in Django admin detail

---

apps/contributions/admin.py
apps/contributions/tests/test_admin.py

n/a
Fixes admin view of contribution detail so that flagged contributions show all fields, not just quarantine actions.
Fixes a bug.
Yes.
No.
Yes.
n/a
No.
No.
https://news-revenue-hub.atlassian.net/browse/DEV-6280
No.
No.

DEV-6280: Show other fields on quarantined contributions

---

apps/contributions/views/switchboard.py
apps/organizations/tests/views/test_revengine.py
apps/organizations/tests/views/test_switchboard.py
apps/organizations/views/revengine.py
apps/organizations/views/switchboard.py

Adds token auth to the following endpoints (while preserving existing JWTHttpOnlyCookieAuthentication auth already allowed by those endpoints, so that SB won't break in interim before we update it to auth with token for same endpoints):
- `api/v1/revenue-programs/<pk>/mailchimp/`
- `api/v1/switchboard/revenue-programs/<pk>/activecampaign/`
All other endpoints used by SB already use token auth.
So we can eventually consolidate to having all SB authentication to RE be via token auth
Yes
No
Yes
N/A
No
N/A
- [DEV-5569](https://news-revenue-hub.atlassian.net/browse/DEV-5569)
- [DEV-5570](https://news-revenue-hub.atlassian.net/browse/DEV-5570)
- [DEV-5571](https://news-revenue-hub.atlassian.net/browse/DEV-5571)
No
- …

DEV-5569 | Add token auth to SB-related endpoints that don't already have it
